-- Office of Readings: the second readings (Liturgy of the Hours, one-year cycle).
-- Origin: the four-volume USA edition's index (parked/epub/data/office-readings/us-one-year-index-candidates.json,
-- from catholic-resources.org); converted by parked/epub/migrate/office.py.
-- [<index row id>] = { author (tag author.<id>), work (tag work.<id>), locator,
-- label (the index's assignment, for curators), us_only }.
return {
    ["oor-001024af874a97f0"] = { author = "augustine-of-hippo", label = "33rd Week in Ord. Time, Wednesday", locator = "21, 1-4", work = "sermon" },
    ["oor-002ea3a2a2d0c37d"] = { author = "anonymous", label = "Holy Saturday", work = "ancient-homily-on-holy-saturday" },
    ["oor-003d4d3f6f78733b"] = { author = "letter-of-barnabas", label = "18th Sunday in Ord. Time", locator = "1, 1-8; 2, 1-5", work = "letter" },
    ["oor-0043d8695dbe4dba"] = { author = "peter-damian", label = "June 19: Romuald, abbot", locator = "31.69", work = "the-life-of-saint-romuald" },
    ["oor-00f92567fb194a3a"] = { author = "faustus-luciferanus", label = "12th Sunday in Ord. Time", locator = "39-40", work = "on-the-trinity" },
    ["oor-01258e20a1826f83"] = { author = "hippolytus-of-rome", label = "Dec. 23", locator = "9-12", work = "against-the-heresy-of-noetus" },
    ["oor-0179c9e647ec445d"] = { author = "guerric-of-igny", label = "Memorial of the Blessed Virgin Mary on Saturday, alt.", locator = "1 on the Assumption", work = "sermon" },
    ["oor-0216ce6972555d0a"] = { author = "gregory-nazianzen", label = "5th Week of Lent, Saturday", locator = "45, 23-24", work = "discourse" },
    ["oor-024dcb91e4f9bc28"] = { author = "anonymous", label = "4th Week in Ord. Time, Friday", locator = "18, 7-11", work = "of-a-fourth-century-author" },
    ["oor-0278e99711d8867e"] = { author = "ephrem-the-syrian", label = "1st Week of Advent, Thursday", locator = "18, 15-17", work = "on-the-diatessaron" },
    ["oor-02a9bb371a7f8f85"] = { author = "augustine-of-hippo", label = "29th Week in Ord. Time, Monday", locator = "130 to Proba 9, 18—10, 20", work = "letter" },
    ["oor-02cdce8038230e82"] = { author = "gregory-the-great", label = "3rd Week of Lent, Friday", locator = "13, 21-23", work = "moral-reflections-on-job" },
    ["oor-02f2e60d3556e986"] = { author = "cyprian-of-carthage", label = "Oct. 14: Callistus I, pope & martyr", locator = "13", work = "to-fortunatus" },
    ["oor-033bf413dd01d590"] = { author = "augustine-of-hippo", label = "19th Week in Ord. Time, Wednesday", locator = "48, 7", work = "on-psalm" },
    ["oor-037a0d1d4ec0354c"] = { author = "imitation-of-christ", label = "22nd Week in Ord. Time, Monday", locator = "3, 3", work = "book" },
    ["oor-03a73425e5fc610a"] = { author = "irenaeus-of-lyons", label = "3rd Week of Easter, Thursday", locator = "5, 2, 2-3", work = "against-heresies" },
    ["oor-04e78cb5c276e6d5"] = { author = "augustine-of-hippo", label = "16th Week in Ord. Time, Friday", locator = "10, 43, 68-70", work = "the-confessions" },
    ["oor-052123fbbc271a3f"] = { author = "angela-merici", label = "Jan. 27: Angela Merici, virgin", work = "spiritual-testament" },
    ["oor-0571cf20f94d98f7"] = { author = "leo-the-great", label = "4th Week of Lent, Tuesday", locator = "10, 3-5", work = "sermon" },
    ["oor-0605309e82ec252d"] = { author = "chromatius-of-aquileia", label = "June 11: Barnabas, apostle", locator = "5, 1.3-4", work = "on-the-gospel-of-matthew" },
    ["oor-06168f65cc19806d"] = { author = "sophronius-of-jerusalem", label = "Feb. 2: Presentation of the Lord", locator = "3 on the presentation 6.7", work = "discourse" },
    ["oor-062f59fd05c34b66"] = { author = "origen", label = "5th Week in Ord. Time, Tuesday", locator = "8, 6.8.9", work = "on-genesis" },
    ["oor-06aa779438b4a330"] = { author = "second-vatican-council", label = "Common of the Blessed Virgin Mary, alt.", locator = "61-62", work = "dogmatic-constitution-on-the-church" },
    ["oor-071e223d24f29749"] = { author = "mary-magdalene-anguillaria", label = "Mar. 9: Frances of Rome, religious", locator = "6-7", work = "the-life-of-saint-frances-of-rome-by-m-m-anguillaria" },
    ["oor-0735412091e7ff5c"] = { author = "gregory-of-nyssa", label = "12th Week in Ord. Time, Thursday", locator = "6 on the Beatitudes (PG 44, 1263-66)", work = "discourse" },
    ["oor-07815b936098f1ad"] = { author = "boniface-of-mainz", label = "June 5: Boniface, bishop & martyr", locator = "78", work = "letter" },
    ["oor-07c78b95a8ea8d85"] = { author = "jerusalem-catecheses", label = "Thursday within the Octave of Easter", locator = "21, Mystagogica 2, 4-6", work = "catecheses" },
    ["oor-0925c23956bc67b1"] = { author = "diadochus-of-photice", label = "2nd Week in Ord. Time, Friday", locator = "12.13.14", work = "on-spiritual-perfection" },
    ["oor-09d55837e703afe7"] = { author = "augustine-of-hippo", label = "2nd Week of Lent, Tuesday", locator = "140, 4-6", work = "on-psalm" },
    ["oor-0a774cd8bf525301"] = { author = "paul-vi", label = "June 3: Charles Lwanga & Companions, martyrs", work = "homily-at-the-canonization-of-the-martyrs-of-uganda" },
    ["oor-0a8b382dd6c2b07b"] = { author = "john-chrysostom", label = "May 14: Matthias, apostle", locator = "3, 1.2.3", work = "on-the-acts-of-the-apostles" },
    ["oor-0afc9605f3eaf23d"] = { author = "augustine-of-hippo", label = "From Jan. 2 to Epiphany, Tuesday", locator = "17, 7-9", work = "on-the-gospel-of-john" },
    ["oor-0b6d9ab3fc97e57c"] = { author = "ambrose-of-milan", label = "20th Week in Ord. Time, Friday", locator = "48, 13-14", work = "on-the-psalms" },
    ["oor-0baea5de4b4b6cfe"] = { author = "john-chrysostom", label = "Common of Saints, for those who worked for the underprivileged", locator = "15, 6", work = "on-the-letter-to-the-romans" },
    ["oor-0c2aa26897413786"] = { author = "vincent-de-paul", label = "Sept. 27: Vincent de Paul, priest", locator = "2546", work = "writings-letter" },
    ["oor-0d11305f7101384a"] = { author = "didymus-the-blind", label = "6th Week of Easter, Monday", locator = "2, 12", work = "on-the-trinity" },
    ["oor-0ddc60a471617fcb"] = { author = "ambrose-of-milan", label = "Dec. 7: Ambrose, bishop and doctor", locator = "2, 1-2.4-5.7", work = "letter" },
    ["oor-0dff2a49f403a1b1"] = { author = "augustine-of-hippo", label = "June 29: Peter & Paul, apostles", locator = "295, 1-2.4.7-8", work = "sermon" },
    ["oor-0e47b34f2ad4e54d"] = { author = "rose-of-lima", label = "Aug. 23: Rose of Lima, virgin", work = "letter-to-a-doctor-at-castille" },
    ["oor-0ec029395434ae8e"] = { author = "margaret-mary-alacoque", label = "Oct. 16: Margaret Mary Alacoque, virgin", work = "from-the-letters" },
    ["oor-0ec621958609369a"] = { author = "dominic-de-guzman", label = "Aug. 8: Dominic, priest", work = "various-writings-on-the-history-of-the-order-of-preachers" },
    ["oor-0f5ba7aca8ac00fa"] = { author = "john-eudes", label = "Aug. 19: John Eudes, priest", locator = "1, 5", work = "on-the-admirable-heart-of-jesus" },
    ["oor-10079f6fc5da6e7f"] = { author = "bruno-the-carthusian", label = "Oct. 6: Bruno, priest", locator = "1-3", work = "letter-to-his-carthusian-sons" },
    ["oor-105e8f077362e46e"] = { author = "john-damascene", label = "July 26: Joachim & Ann, Parents of Mary", locator = "6 on the birthday of Mary", work = "discourse" },
    ["oor-1146f2536aaad817"] = { author = "second-vatican-council", label = "31st Week in Ord. Time, Tuesday", locator = "88-90", work = "pastoral-constitution-on-the-church-in-the-modern-world" },
    ["oor-1278d1debe6fe6b4"] = { author = "gregory-the-great", label = "8th Week in Ord. Time, Thursday", locator = "10, 7-8.10", work = "moral-reflections-on-job" },
    ["oor-127fe3ee37363419"] = { author = "jerusalem-catecheses", label = "Friday within the Octave of Easter", locator = "21, Mystagogica 3, 1-3", work = "catecheses" },
    ["oor-1284b7740281fc7d"] = { author = "theodore-the-studite", label = "2nd Week of Easter, Friday", work = "sermon-on-the-adoration-of-the-cross" },
    ["oor-132fd5d927cb04dd"] = { author = "john-chrysostom", label = "July 25: James, apostle", locator = "65, 2-4", work = "on-the-gospel-of-matthew" },
    ["oor-142d675dc569c290"] = { author = "gregory-the-great", label = "27th Sunday in Ord. Time", locator = "2, 4", work = "pastoral-guide" },
    ["oor-144b29cbaf13c945"] = { author = "francis-xavier", label = "Dec. 3: Francis Xavier, priest", work = "letter-to-saint-ignatius" },
    ["oor-1450d45b01409c15"] = { author = "columban", label = "7th Week in Ord. Time, Thursday", locator = "1, 3-5", work = "instruction" },
    ["oor-15d5acaa9ca725d3"] = { author = "clement-of-rome", label = "2nd Week in Ord. Time, Tuesday", locator = "49-50", work = "letter-to-the-corinthians" },
    ["oor-166fa7c6b4dd3cfe"] = { author = "second-vatican-council", label = "31st Week in Ord. Time, Monday", locator = "82-83", work = "pastoral-constitution-on-the-church-in-the-modern-world" },
    ["oor-1686985c0774f849"] = { author = "isaac-of-stella", label = "5th Week of Easter, Friday", locator = "42", work = "sermon" },
    ["oor-16e4f158e367516b"] = { author = "cyril-of-alexandria", label = "June 27: Cyril of Alexandria, bishop of doctor", locator = "1", work = "letter" },
    ["oor-179fbeb7a33764ba"] = { author = "ambrose-of-milan", label = "31st Week in Ord. Time, Saturday", locator = "3, 9; 4, 15", work = "on-death-as-a-blessing" },
    ["oor-17a00277de31df6c"] = { author = "irenaeus-of-lyons", label = "2nd Week of Lent, Wednesday", locator = "4, 14, 2-3; 15, 1", work = "against-heresies" },
    ["oor-17d44919ac19cd4a"] = { author = "augustine-of-hippo", label = "29th Week in Ord. Time, Friday", locator = "130 to Proba 14, 27—15, 28", work = "letter" },
    ["oor-180212fb1a86c2cb"] = { author = "ignatius-of-antioch", label = "16th Week in Ord. Time, Monday", locator = "6, 1—9, 2", work = "to-the-magnesians" },
    ["oor-1838621bc434d6c1"] = { author = "leo-the-great", label = "34th Week in Ord. Time, Monday", locator = "92, 1.2.3", work = "sermon" },
    ["oor-18d18b25169dadab"] = { author = "aphraates-of-persia", label = "1st Week of Lent, Wednesday", locator = "11, 11-12", work = "demonstration" },
    ["oor-19397d2859e726c3"] = { author = "diadochus-of-photice", label = "4th Week in Ord. Time, Wednesday", locator = "6.26.27.30", work = "on-spiritual-perfection" },
    ["oor-1a76c1e20b2bf119"] = { author = "clement-of-rome", label = "30th Week in Ord. Time, Monday", locator = "21, 1—22, 5; 23, 1-2", work = "letter-to-the-corinthians" },
    ["oor-1a9eb47cef0252bc"] = { author = "robert-bellarmine", label = "Sept. 17: Robert Bellarmine, bishop & doctor", locator = "1", work = "on-the-ascent-of-the-mind-to-god-grad" },
    ["oor-1ad18f603e8f8607"] = { author = "bernard-of-clairvaux", label = "May 12: Pancras, martyr", locator = "17, 4.6, on Psalm 91", work = "sermon" },
    ["oor-1b83ff4466ec0712"] = { author = "john-of-the-cross", label = "2nd Week of Advent, Monday", locator = "2, 22", work = "on-the-ascent-of-mount-carmel" },
    ["oor-1c2b70d03802f46b"] = { author = "anastasius-of-sinai", label = "Aug. 6: Transfiguration", locator = "6-10", work = "sermon-on-the-transfiguration-of-the-lord" },
    ["oor-1cc53bf63321efd4"] = { author = "gregory-of-nyssa", label = "7th Sunday of Easter", locator = "15", work = "on-the-song-of-songs" },
    ["oor-1ebc7304bd5ebf0d"] = { author = "clement-of-rome", label = "30th Week in Ord. Time, Tuesday", locator = "24, 1-5; 27, 1—29, 1", work = "letter-to-the-corinthians" },
    ["oor-20030d60efbd6233"] = { author = "john-the-serene", label = "3rd Week in Ord. Time, Thursday", locator = "7", work = "sermon" },
    ["oor-20c829071d5af303"] = { author = "bernard-of-clairvaux", label = "Sept. 15: Our Lady of Sorrows", locator = "14-15", work = "sermon-on-the-sunday-within-the-octave-of-the-assumption" },
    ["oor-20d92b226f71df77"] = { author = "irenaeus-of-lyons", label = "4th Week in Ord. Time, Tuesday", locator = "3, 19, 1.3—20, 1", work = "against-heresies" },
    ["oor-20e4b474f7149979"] = { author = "cyprian-of-carthage", label = "Aug. 7: Sixtus II, pope & martyr, & Companions, martyrs", locator = "80", work = "letter" },
    ["oor-215809943df1c085"] = { author = "tertullian", label = "May 3: Philip & James, apostles", locator = "20, 1-9; 21, 3; 22, 8-10", work = "on-the-prescription-of-heretics" },
    ["oor-21630fdf30738778"] = { author = "peter-chrysologus", label = "2nd Week of Advent, Thursday", locator = "147 (On love and seeing God)", work = "sermon" },
    ["oor-21d15fc9a2bd650d"] = { author = "fulgentius-of-ruspe", label = "Common of Pastors, alt., particularly for a bishop", locator = "1, 2-3", work = "sermon" },
    ["oor-21f2b185d415c93b"] = { author = "ambrose-of-milan", label = "Oct. 9: Denis, bishop & martyr, & Companions, martyrs", locator = "20, 47-50", work = "on-the-psalms" },
    ["oor-2225e68cad3acda4"] = { author = "ambrose-of-milan", label = "16th Week in Ord. Time, Thursday", locator = "44, 89-90", work = "on-the-psalms" },
    ["oor-226a8afbf8e37353"] = { author = "augustine-of-hippo", label = "8th Week in Ord. Time, Wednesday", locator = "10, 26.37—29, 40", work = "the-confessions" },
    ["oor-22d859c4d7b9056a"] = { author = "john-damascene", label = "Dec. 4: John Damascene, priest and Dictor", locator = "1", work = "explanation-of-the-faith" },
    ["oor-23dcccd120182bdb"] = { author = "anonymous", label = "32nd Week in Ord. Time, Wednesday", locator = "10, 1—12, 1; 13, 1", work = "of-a-second-century-author" },
    ["oor-2473a27dca888468"] = { author = "augustine-of-hippo", label = "June 24: Birth of John the Baptist", locator = "293, 1-3", work = "sermon" },
    ["oor-249234347c267c38"] = { author = "francis-of-assisi", label = "Oct. 4: Francis of Assisi", work = "letter-written-to-all-the-faithful" },
    ["oor-253c539bdb295836"] = { author = "pius-x", label = "Aug. 21: Pius X, pope", work = "apostolic-constitution-divino-afflatu" },
    ["oor-257c630edea7c5c0"] = { author = "clement-of-rome", label = "Nov. 23: Clement I, pope & martyr", locator = "35.36.37.38", work = "letter-to-the-corinthians" },
    ["oor-2631ebc41535410e"] = { author = "anselm-of-canterbury", label = "Apr. 21: Anselm, bishop & doctor", locator = "14.16.26", work = "proslogium" },
    ["oor-26556d15c542222e"] = { author = "pacian-of-barcelona", label = "19th Week in Ord. Time, Friday", locator = "5-6", work = "on-baptism" },
    ["oor-26e8b9cb4c4ccd61"] = { author = "john-chrysostom", label = "20th Sunday in Ord. Time", locator = "15, 6.7", work = "on-the-gospel-of-matthew" },
    ["oor-26faff928fe64fec"] = { author = "gregory-nazianzen", label = "1st Week of Advent, Tuesday", locator = "45, 9.22.26.28", work = "discourse" },
    ["oor-2724f7142d50cb86"] = { author = "ambrose-of-milan", label = "15th Week in Ord. Time, Saturday", locator = "52-54.58", work = "on-the-mysteries" },
    ["oor-28b6244c2a079f9a"] = { author = "cyprian-of-carthage", label = "Sept. 16: Cornelius, pope & martyr, & Cyprian, bishop & martyr", locator = "60, 1-2.5", work = "letter" },
    ["oor-28c385cd667e10ca"] = { author = "cyprian-of-carthage", label = "11th Week in Ord. Time, Thursday", locator = "18.22", work = "on-the-lords-prayer" },
    ["oor-28e182345bf9f813"] = { author = "anonymous", label = "32nd Week in Ord. Time, Monday", locator = "3, 1—4, 5; 7, 1-6", work = "of-a-second-century-author" },
    ["oor-290f4387a73d7425"] = { author = "pseudo-chrysostom", label = "Friday after Ash Wednesday", locator = "6 on Prayer", work = "supp-homily" },
    ["oor-298d42e24c2fd126"] = { author = "francis-de-sales", label = "Jan. 24: Francis de Sales, bishop & doctor", work = "introduction-to-the-devout-life" },
    ["oor-29f7971d56cd8867"] = { author = "jane-frances-de-chantal", label = "Dec. 12: Jane Frances de Chantal, religious", work = "life-of-jane-frances-de-chantal-by-de-chaugy" },
    ["oor-2b01af8b5253a3e1"] = { author = "augustine-of-hippo", label = "29th Week in Ord. Time, Tuesday", locator = "130 to Proba 11, 21—12, 22", work = "letter" },
    ["oor-2b762ecee6d5a694"] = { author = "eusebius-of-caesarea", label = "Dec. 31: Sylvester I, pope", locator = "10, 1-3", work = "ecclesiastical-history" },
    ["oor-2ba9759e82a68887"] = { author = "augustine-of-hippo", label = "6th Week of Easter, Saturday", locator = "124, 5.7", work = "on-the-gospel-of-john" },
    ["oor-2c684a1342109416"] = { author = "augustine-of-hippo", label = "Common of One Martyr", locator = "329, 1.2", work = "sermon" },
    ["oor-2c823e0f02690322"] = { author = "basil-the-great", label = "From Jan. 2 to Epiphany, Monday", locator = "26, 61-64", work = "on-the-holy-spirit" },
    ["oor-2ca3f55dfee8294c"] = { author = "augustine-of-hippo", label = "3rd Sunday of Lent", locator = "15, 10-12.16-17", work = "on-the-gospel-of-john" },
    ["oor-2cd7978735657f06"] = { author = "augustine-of-hippo", label = "25th Week in Ord. Time, Thursday", locator = "46, On Pastors, 24-25.27", work = "sermon" },
    ["oor-2cdc5813d8c2e120"] = { author = "gregory-the-great", label = "8th Week in Ord. Time, Monday", locator = "3, 15-16", work = "moral-reflections-on-job" },
    ["oor-2cf5b5d7a3f65a2a"] = { author = "augustine-of-hippo", label = "3rd Week of Easter, Tuesday", locator = "34, 1-3.5-6", work = "sermon" },
    ["oor-2e0bd5b23ab9736c"] = { author = "athanasius-of-alexandria", label = "1st Week in Ord. Time, Friday", locator = "42-43", work = "against-the-pagans" },
    ["oor-2e780e51b1694b18"] = { author = "martin-i", label = "Apr. 13: Martin I, pope & martyr", locator = "17", work = "letter" },
    ["oor-2ea46493227c5aef"] = { author = "athanasius-of-alexandria", label = "23rd Week in Ord. Time, Saturday", locator = "10", work = "discourse-on-the-incarnation-of-the-word" },
    ["oor-2fa6583ba8671bf0"] = { author = "athanasius-of-alexandria", label = "Jan. 17: Anthony, abbot", locator = "2-4", work = "the-life-of-saint-anthony" },
    ["oor-3067105e0de0aefa"] = { author = "paul-vi", label = "Sunday in the Octave of Christmas", locator = "1964", work = "address-at-nazareth" },
    ["oor-30a77f0842b15919"] = { author = "isaac-of-stella", label = "2nd Week of Advent, Saturday", locator = "51", work = "sermon" },
    ["oor-323cf245200dcf2f"] = { author = "leo-the-great", label = "Feb. 22: Chair of Peter, apostle", locator = "4, 2-3", work = "sermon-on-his-own-birthday" },
    ["oor-3241d87c2793d7c3"] = { author = "second-vatican-council", label = "Common of Doctors of the Church, alt.", locator = "7-8", work = "dogmatic-constitution-on-divine-revelation" },
    ["oor-327a66e6fd803d6f"] = { author = "ambrose-of-milan", label = "Jan. 20: Sebastian, pope & martyr", locator = "119, 43-45.48", work = "on-the-psalms" },
    ["oor-32f0b6faf89b07c9"] = { author = "john-chrysostom", label = "Jan. 25: Conversion of Paul, apostle", locator = "2, In praise of Saint Paul (PG 50, 477-480)", work = "homily" },
    ["oor-34299c584167f139"] = { author = "augustine-of-hippo", label = "May 12: Nereus & Achilleus, martyrs", locator = "61, 4", work = "on-psalm" },
    ["oor-3432b3898bfd04ce"] = { author = "leo-the-great", label = "22nd Week in Ord. Time, Thursday", locator = "95 on the Beatitudes 1-2", work = "sermon" },
    ["oor-348e703543d695ec"] = { author = "second-vatican-council", label = "4th Week in Ord. Time, Saturday", locator = "35-36", work = "pastoral-constitution-on-the-church-in-the-modern-world" },
    ["oor-34b75b307a8ef681"] = { author = "stephen-of-hungary", label = "Aug. 16: Stephen of Hungary", locator = "1.2.10", work = "admonitions-to-his-son" },
    ["oor-3534cd2839ba657b"] = { author = "augustine-of-hippo", label = "25th Week in Ord. Time, Monday", locator = "46, On Pastors, 14-15", work = "sermon" },
    ["oor-3555944688ad185b"] = { author = "albert-the-great", label = "Nov. 15: Albert the Great, bishop & doctor", locator = "22, 19", work = "on-the-gospel-of-luke" },
    ["oor-356b91d4fd50fe6e"] = { author = "ambrose-of-milan", label = "10th Week in Ord. Time, Saturday", locator = "1, 9-12", work = "on-the-psalms" },
    ["oor-35a63ee855be44a6"] = { author = "augustine-of-hippo", label = "24th Week in Ord. Time, Monday", locator = "46, On Pastors, 3-4", work = "sermon" },
    ["oor-35ee5da79d578e1d"] = { author = "teresa-of-avila", label = "Oct. 15: Teresa of Avila, virgin & doctor", locator = "22, 6-7.14", work = "the-book-of-life" },
    ["oor-3657d1f2e31f4491"] = { author = "hippolytus-of-rome", label = "Dec. 30: Octave of Christmas, Sixth Day", locator = "10, 33-34", work = "on-the-refutation-of-all-heresies" },
    ["oor-36bce13768b08d04"] = { author = "cyril-of-alexandria", label = "6th Sunday of Easter", locator = "5:5—6:2", work = "on-the-second-letter-to-the-corinthians" },
    ["oor-378f9daeb743eb7b"] = { author = "second-vatican-council", label = "3rd Sunday in Ord. Time", locator = "7-8.106", work = "constitution-on-the-sacred-liturgy" },
    ["oor-38753d93db2ad82c"] = { author = "cyprian-of-carthage", label = "1st Week of Lent, Tuesday", locator = "1-3", work = "on-the-lords-prayer" },
    ["oor-388e893bc34ffc56"] = { author = "columban", label = "21st Week in Ord. Time, Wednesday", locator = "13, 1-2", work = "on-christ-the-font-of-life-instruction" },
    ["oor-38ec4c7899487515"] = { author = "leo-the-great", label = "Nov. 18: Dedication of the Churches of Peter & Paul, apostles", locator = "82 on the feast of the apostles, Peter and Paul", work = "sermon" },
    ["oor-394c1f23f05ec154"] = { author = "proclus-of-constantinople", label = "Memorial of the Blessed Virgin Mary on Saturday", locator = "1-2", work = "sermon-on-the-lords-birth" },
    ["oor-39a6e0f961e58be1"] = { author = "basil-the-great", label = "17th Week in Ord. Time, Tuesday", locator = "6, 3.6", work = "homily" },
    ["oor-39ef7b806044ac51"] = { author = "jerusalem-catecheses", label = "Saturday within the Octave of Easter", locator = "22, Mystagogica 4, 1.3-6.9", work = "catecheses" },
    ["oor-3a8ed2afa900c10d"] = { author = "clement-of-rome", label = "14th Week in Ord. Time, Monday", locator = "46, 2—47, 4; 48, 1-6", work = "letter-to-the-corinthians" },
    ["oor-3aa1b3d7c9e7e85f"] = { author = "augustine-of-hippo", label = "22nd Sunday in Ord. Time", locator = "23A, 1-4", work = "sermon" },
    ["oor-3ac1f6ab7887accc"] = { author = "pacian-of-barcelona", label = "19th Week in Ord. Time, Saturday", locator = "6-7", work = "on-baptism" },
    ["oor-3af1f5a73e832b10"] = { author = "ignatius-of-antioch", label = "4th Sunday in Ord. Time", locator = "1—4, 1", work = "to-the-church-of-smyrna" },
    ["oor-3b1bea9da8aed462"] = { author = "ambrose-of-milan", label = "Nov. 2: All Souls", locator = "2", work = "on-the-death-of-his-brother" },
    ["oor-3b42704eb1bf294c"] = { author = "augustine-of-hippo", label = "29th Week in Ord. Time, Thursday", locator = "130 to Proba 14, 25-26", work = "letter" },
    ["oor-3b7e977e726294c2"] = { author = "isaac-of-stella", label = "23rd Week in Ord. Time, Friday", locator = "11", work = "sermon" },
    ["oor-3d311adb0f8cba08"] = { author = "asterius-of-amasea", label = "1st Week of Lent, Thursday", locator = "13", work = "homily" },
    ["oor-3e06c39dc0837283"] = { author = "church-of-smyrna", label = "Feb. 23: Polycarp, bishop & martyr", locator = "13, 2—15, 3", work = "letter-from-smyrna-on-the-martyrdom-of-st-polycarp" },
    ["oor-3e16e1f8dbb755f8"] = { author = "second-vatican-council", label = "21st Sunday in Ord. Time", locator = "39", work = "pastoral-constitution-on-the-church-in-the-modern-world" },
    ["oor-3e85e3e35afec5ba"] = { author = "ambrose-of-milan", label = "15th Week in Ord. Time, Tuesday", locator = "12-16.19", work = "on-the-mysteries" },
    ["oor-3f2f84a4c4c42700"] = { author = "irenaeus-of-lyons", label = "2nd Week of Lent, Friday", locator = "4, 16, 2-5", work = "against-heresies" },
    ["oor-403554d4db1b8349"] = { author = "anonymous", label = "Wednesday within the Octave of Easter", locator = "35, 6-9", work = "easter-homily-by-an-ancient-author" },
    ["oor-41af43745c79bd44"] = { author = "gregory-the-great", label = "27th Week in Ord. Time, Saturday", locator = "17, 3.14", work = "on-the-gospels" },
    ["oor-41ed6296027531ad"] = { author = "augustine-of-hippo", label = "5th Week of Lent, Wednesday", locator = "85, 1", work = "on-psalm" },
    ["oor-41f6bc330b90a3e9"] = { author = "augustine-of-hippo", label = "Holy Week, Wednesday", locator = "84, 1-2", work = "on-the-gospel-of-john" },
    ["oor-4253bf85eea312d8"] = { author = "john-xxiii", label = "Nov. 3: Martin de Porres, religious", work = "homily-at-the-canonization-of-saint-martin-de-porres" },
    ["oor-42cf374a6f60f169"] = { author = "bede-the-venerable", label = "May 31: Visitation", locator = "4", work = "homily" },
    ["oor-42d3fb6eac95da11"] = { author = "cyprian-of-carthage", label = "11th Sunday in Ord. Time", locator = "4-6", work = "on-the-lords-prayer" },
    ["oor-42e249731f2f65b8"] = { author = "dorotheus-of-gaza", label = "9th Week in Ord. Time, Monday", locator = "7, 1-2", work = "teaching" },
    ["oor-432fd5fe90f4a5af"] = { author = "gregory-nazianzen", label = "Jan. 2: Basil the Great and Gregory Nazianzen, bishops and doctors", locator = "43, 15-16-17.19-21", work = "discourse" },
    ["oor-44644bdd0b511cf3"] = { author = "augustine-of-hippo", label = "5th Week in Ord. Time, Thursday", locator = "37.38", work = "on-the-letter-to-the-galatians" },
    ["oor-44a971186d649bb7"] = { author = "acts-of-justin", label = "June 1: Justin, martyr", locator = "1-5", work = "acts-of-the-martyrdom-of-saint-justin-martyr" },
    ["oor-4558821700d931e2"] = { author = "irenaeus-of-lyons", label = "2nd Week of Advent, Friday", locator = "5, 19, 1; 20, 2; 21, 1", work = "against-heresies" },
    ["oor-4558959a120b7920"] = { author = "andrew-of-crete", label = "Sept. 14: Triumph of the Cross", locator = "10", work = "discourse" },
    ["oor-464d2faf5b9df00a"] = { author = "augustine-of-hippo", label = "Aug. 10: Lawrence, Deacon & martyr", locator = "304, 1-4", work = "sermon" },
    ["oor-46c6f90000ec2213"] = { author = "augustine-of-hippo", label = "May 26: Philip Neri, priest", locator = "171, 1-3.5", work = "sermon" },
    ["oor-46e1f042db362d30"] = { author = "augustine-of-hippo", label = "25th Week in Ord. Time, Tuesday", locator = "46, On Pastors, 18-19", work = "sermon" },
    ["oor-4795837cb3bfec4b"] = { author = "augustine-of-hippo", label = "Holy Week, Monday", locator = "3", work = "sermon-guelferbytanus" },
    ["oor-47fb28f98e2651dd"] = { author = "irenaeus-of-lyons", label = "Pentecost Sunday", locator = "3, 17, 1-3", work = "against-heresies" },
    ["oor-4861be276b87c924"] = { author = "ambrose-of-milan", label = "2nd Week of Lent, Saturday", locator = "6, 36; 7, 44; 8, 45; 9, 52", work = "on-flight-from-the-world" },
    ["oor-489182410cb270d7"] = { author = "john-of-avila", label = "May 18: John I, pope & martyr", locator = "58", work = "letter-to-his-friends" },
    ["oor-48fe68ae26eebaf6"] = { author = "augustine-of-hippo", label = "5th Week of Easter, Saturday", locator = "148, 1-2", work = "on-psalm" },
    ["oor-49660d8184f0529d"] = { author = "anthony-zaccaria", label = "July 5: Anthony Zaccaria, priest", work = "sermon-to-his-fellow-members" },
    ["oor-499138e5284e1399"] = { author = "polycarp-of-smyrna", label = "26th Sunday in Ord. Time", locator = "1, 1—2, 3", work = "to-the-philippians" },
    ["oor-4a61d7b8890f5639"] = { author = "john-fisher", label = "5th Week of Lent, Monday", locator = "129", work = "on-psalm" },
    ["oor-4b11a6b614b731cd"] = { author = "john-chrysostom", label = "Good Friday", locator = "3, 13-19", work = "catecheses" },
    ["oor-4b9318b57fa208c0"] = { author = "augustine-of-hippo", label = "28th Week in Ord. Time, Thursday", locator = "26, 4-6", work = "on-the-gospel-of-john" },
    ["oor-4bb645f554447ef4"] = { author = "anonymous", label = "July 13: Henry", work = "the-life-of-saint-henry" },
    ["oor-4cb29cd9c12aec10"] = { author = "bernard-of-clairvaux", label = "Dec. 20", locator = "4, 8-9", work = "in-praise-of-the-virgin-mother" },
    ["oor-4d05b48f628da357"] = { author = "anastasius-of-antioch", label = "Office of the Dead", locator = "5, On the Resurrection of Christ 6.7-9", work = "discourse" },
    ["oor-4d75bce39dfc86c0"] = { author = "ignatius-of-antioch", label = "2nd Week in Ord. Time, Monday", locator = "13—18, 1", work = "to-the-ephesians" },
    ["oor-4daf30b9181dce94"] = { author = "gregory-vii", label = "May 25: Gregory VII, pope", locator = "64", work = "letter" },
    ["oor-4f06fe76129d95b6"] = { author = "gregory-of-nyssa", label = "7th Week in Ord. Time, Tuesday", locator = "6", work = "on-ecclesiastes" },
    ["oor-4f16a8dfd52d3573"] = { author = "maximus-the-confessor", label = "From Jan. 2 to Epiphany, Wednesday", locator = "1, 8-13", work = "five-hundred-chapters" },
    ["oor-4fe8f4af21bdf5b7"] = { author = "pseudo-hippolytus", label = "After Epiphany to the Baptism of the Lord, Tuesday", locator = "2.6-8.10", work = "sermon-on-the-epiphany" },
    ["oor-500392331a6c705a"] = { author = "cyril-of-alexandria", label = "7th Week of Easter, Thursday", locator = "10", work = "on-the-gospel-of-john" },
    ["oor-5032ffaced7715ee"] = { author = "quodvultdeus", label = "Dec. 28: Holy Innocents, martyrs", locator = "2 on the Creed", work = "sermon" },
    ["oor-50af17330c26896b"] = { author = "augustine-of-hippo", label = "Dec. 11: Damasus I, pope", locator = "20, 21", work = "against-faustus" },
    ["oor-50b3c6f9eb593531"] = { author = "andrew-of-crete", label = "33rd Week in Ord. Time, Tuesday", locator = "9 (PG 97 1002)", work = "discourse" },
    ["oor-50c9a6649c0832cd"] = { author = "bernard-of-clairvaux", label = "Oct. 2: Guardian Angels", locator = "91, 12, 3.6-8", work = "on-psalm" },
    ["oor-50f052c6587b67ad"] = { author = "proclus-of-constantinople", label = "After Epiphany to the Baptism of the Lord, Wednesday", locator = "7 on Epiphany 1-3", work = "discourse" },
    ["oor-511f0b26683026a8"] = { author = "origen", label = "10th Week in Ord. Time, Thursday", locator = "6, 4", work = "on-the-book-of-joshua" },
    ["oor-51380f1ab9393e7c"] = { author = "second-vatican-council", label = "28th Week in Ord. Time, Saturday", locator = "40.45", work = "pastoral-constitution-on-the-church-in-the-modern-world" },
    ["oor-5146792a7b86a9c7"] = { author = "thomas-more", label = "June 22: John Fisher, bishop & martyr, & Thomas More, martyr", work = "letter-to-his-daughter" },
    ["oor-51aa724992297905"] = { author = "gaudentius-of-brescia", label = "2nd Week of Easter, Thursday", locator = "2 (CSEL 68, 30-32)", work = "treatise" },
    ["oor-51ff8d1ad26d3e60"] = { author = "second-vatican-council", label = "May 1: Joseph the Worker", locator = "33-34", work = "pastoral-constitution-on-the-church-in-the-modern-world" },
    ["oor-523b8a643baf8613"] = { author = "john-neumann", label = "Jan. 5 [USA]: John Neumann", us_only = true, work = "letter-to-cardinal-barnabo" },
    ["oor-5256e1eabfaf3d95"] = { author = "eusebius-of-caesarea", label = "2nd Sunday of Advent", locator = "40", work = "on-isaiah" },
    ["oor-52a3610ca67d37ed"] = { author = "augustine-of-hippo", label = "6th Week in Ord. Time, Friday", locator = "4", work = "on-the-first-letter-of-john" },
    ["oor-52aa2353ac2a9adf"] = { author = "john-chrysostom", label = "17th Sunday in Ord. Time", locator = "14, 1-2", work = "on-the-second-letter-to-the-corinthians" },
    ["oor-54716c4d92394ac5"] = { author = "ephrem-the-syrian", label = "3rd Week of Easter, Friday", locator = "3-4.9", work = "sermon-on-our-lord" },
    ["oor-54d2e139ebd8975a"] = { author = "basil-the-great", label = "3rd Week of Lent, Monday", locator = "20, 3", work = "homily" },
    ["oor-55295a031f7e7123"] = { author = "augustine-of-hippo", label = "29th Sunday in Ord. Time", locator = "130 to Proba 8, 15.17—9, 18", work = "letter" },
    ["oor-558faacf206442fe"] = { author = "clare-of-assisi", label = "Aug. 11: Clare, virgin", work = "letter-to-blessed-agnes-of-prague" },
    ["oor-55f5b63759b4bf77"] = { author = "cajetan-of-thiene", label = "Aug. 7: Cajetan, priest", work = "letter-to-elizabeth-porto" },
    ["oor-5662e43487ab31d9"] = { author = "gregory-of-agrigentum", label = "7th Week in Ord. Time, Friday", locator = "8, 6", work = "on-ecclesiastes" },
    ["oor-5676970e4d2985b0"] = { author = "joseph-calasanz", label = "Aug. 25: Joseph Calasanz, priest", work = "the-writings-passim" },
    ["oor-56d1a3bbb23e749c"] = { author = "gregory-of-nyssa", label = "12th Week in Ord. Time, Monday", locator = "PG 46, 254-255)", work = "on-christian-perfection" },
    ["oor-56f492205157b97e"] = { author = "augustine-of-hippo", label = "28th Week in Ord. Time, Friday", locator = "10, 6", work = "the-city-of-god" },
    ["oor-571dd87c407c3487"] = { author = "leo-the-great", label = "Nov. 10: Leo the Great, pope & doctor", locator = "4,1-2", work = "sermon" },
    ["oor-57cc10edbd905e0c"] = { author = "basil-the-great", label = "Holy Week, Tuesday", locator = "15, 35", work = "on-the-holy-spirit" },
    ["oor-5843d10255edc249"] = { author = "second-vatican-council", label = "2nd Week of Advent, Tuesday", locator = "48", work = "dogmatic-constitution-on-the-church" },
    ["oor-585b21c676bdb446"] = { author = "second-vatican-council", label = "Nov. 16: Margaret of Scotland", locator = "48", work = "pastoral-constitution-on-the-church-in-the-modern-world" },
    ["oor-58616e93c0d3cdfa"] = { author = "john-fisher", label = "3rd Week in Ord. Time, Friday", locator = "102", work = "on-psalm" },
    ["oor-58cdaea2f869c452"] = { author = "gregory-nazianzen", label = "31st Week in Ord. Time, Friday", locator = "7, 23-24", work = "discourse" },
    ["oor-59027128061dfac7"] = { author = "isaac-of-stella", label = "5th Week in Ord. Time, Saturday", locator = "31", work = "sermon" },
    ["oor-5978545f7bc49224"] = { author = "anonymous", label = "32nd Sunday in Ord. Time", locator = "1, 1—2, 7", work = "of-a-second-century-author" },
    ["oor-5ad14cc20eee4ecf"] = { author = "procopius-of-gaza", label = "6th Week in Ord. Time, Wednesday", locator = "9", work = "on-the-book-of-proverbs" },
    ["oor-5b2e919d480e6e06"] = { author = "pius-xii", label = "July 6: Maria Goretti, virgin & martyr", work = "homily-at-the-canonization-of-saint-maria-goretti" },
    ["oor-5b435a2d01ca98bd"] = { author = "ambrose-of-milan", label = "20th Week in Ord. Time, Saturday", locator = "48, 14-15", work = "on-the-psalms" },
    ["oor-5b4dd5a1df10a457"] = { author = "hilary-of-poitiers", label = "Common of Pastors, for the founder of a church", locator = "127, 7-10", work = "on-psalm" },
    ["oor-5c74b0aa30ac67db"] = { author = "irenaeus-of-lyons", label = "Apr. 25: Mark, evangelist", locator = "1, 10, 1-3", work = "against-heresies" },
    ["oor-5cc9ab99632f2bec"] = { author = "gregory-the-great", label = "May 27: Augustine of Canterbury, bishop", locator = "9, 36", work = "letter" },
    ["oor-5d2ed6d88a99841c"] = { author = "justin-martyr", label = "3rd Sunday of Easter", locator = "66-67", work = "first-apology-in-defense-of-the-christians" },
    ["oor-5dcf7edde06da1e3"] = { author = "cyril-of-alexandria", label = "After Epiphany to the Baptism of the Lord, Thursday", locator = "5, 2", work = "on-the-gospel-of-john" },
    ["oor-5e6d4b1fcea71be2"] = { author = "anonymous", label = "32nd Week in Ord. Time, Tuesday", locator = "8, 1—9, 11", work = "of-a-second-century-author" },
    ["oor-5f6e87cbeb857b2e"] = { author = "gregory-of-nyssa", label = "26th Week in Ord. Time, Saturday", locator = "PG 46, 295-298)", work = "on-christian-formation" },
    ["oor-5f781c40ea320c69"] = { author = "second-vatican-council", label = "3rd Week of Advent, Thursday", locator = "3-4", work = "dogmatic-constitution-on-divine-revelation" },
    ["oor-5fa8192e87bd7755"] = { author = "ambrose-of-milan", label = "Jan. 21: Agnes, virgin & martyr", locator = "1, 2.5.7-9", work = "on-virgins" },
    ["oor-604a3ecf0e03cbbe"] = { author = "mary-magdalene-de-pazzi", label = "May 25: Mary Magdalene de Pazzi, virgin", locator = "186.264; IV, 716", work = "on-revelation-and-on-trials-iii" },
    ["oor-609cdba941131609"] = { author = "cyril-of-jerusalem", label = "Mar. 18: Cyril of Jerusalem, bishop & doctor", locator = "3, 1-3", work = "catechetical-instruction" },
    ["oor-614d584530b261a1"] = { author = "athanasius-of-alexandria", label = "1st Week in Ord. Time, Thursday", locator = "40-42", work = "against-the-pagans" },
    ["oor-61ee7e4ad26d8fa0"] = { author = "john-chrysostom", label = "Jan. 26: Timothy & Titus, bishops", locator = "2, In praise of Saint Paul (PG 50, 480-484)", work = "homily" },
    ["oor-6239acd0dc8da64f"] = { author = "cyprian-of-carthage", label = "11th Week in Ord. Time, Wednesday", locator = "13-15", work = "on-the-lords-prayer" },
    ["oor-62499ff9b6724572"] = { author = "leo-the-great", label = "6th Week of Easter, Friday", locator = "2, 1-4", work = "sermon-on-the-ascension" },
    ["oor-62795fd20d1b96bb"] = { author = "wenceslaus", label = "Sept. 28: Wenceslaus, martyr", work = "first-old-slavic-legend" },
    ["oor-62bfa3c9a54d831f"] = { author = "second-vatican-council", label = "5th Week of Lent, Thursday", locator = "9", work = "dogmatic-constitution-on-the-church" },
    ["oor-63861a58241e975b"] = { author = "second-vatican-council", label = "2nd Week in Ord. Time, Wednesday", locator = "2.16", work = "dogmatic-constitution-on-the-church" },
    ["oor-642ce4910cb25bd2"] = { author = "peter-canisius", label = "Dec. 21: Peter Canasius, priest and doctor", work = "from-his-writings" },
    ["oor-64fa12151198eb5e"] = { author = "andrew-of-crete", label = "Passion Sunday (Palm Sunday)", locator = "9 (PG 97, 990-994)", work = "discourse" },
    ["oor-6698e6b65b0dcf89"] = { author = "jerome", label = "Sept. 30: Jerome, priest & doctor", locator = "1.2", work = "prologue-of-the-commentary-on-isaiah" },
    ["oor-66a2341221b8e64d"] = { author = "marie-bernadette-soubirous", label = "Feb. 11: Our Lady of Lourdes", locator = "1861", work = "letter" },
    ["oor-66a509a293ecbd38"] = { author = "john-chrysostom", label = "21st Week in Ord. Time, Saturday", locator = "50, 3-4", work = "on-the-gospel-of-matthew" },
    ["oor-66a9d2614a3c087e"] = { author = "augustine-of-hippo", label = "3rd Sunday of Advent", locator = "293, 3", work = "sermon" },
    ["oor-6709cbb831db73c9"] = { author = "ephrem-the-syrian", label = "6th Sunday in Ord. Time", locator = "1, 18-19", work = "on-the-diatessaron" },
    ["oor-676c27aa8f296995"] = { author = "augustine-of-hippo", label = "24th Sunday in Ord. Time", locator = "46, On Pastors, 1-2", work = "sermon" },
    ["oor-68042c5807edfcc4"] = { author = "anonymous", label = "Feb. 14: Cyril, Monk, & Methodius, bishop", locator = "18", work = "an-old-slavonic-life-of-constantine" },
    ["oor-6830c3523a577947"] = { author = "augustine-of-hippo", label = "14th Sunday in Ord. Time", locator = "19, 2-3", work = "sermon" },
    ["oor-6866a72cd21d0187"] = { author = "benedict-xiv", label = "Apr. 24: Fidelis of Sigmaringen, priest & martyr", work = "eulogy-for-saint-fidelis" },
    ["oor-6868d1913d73eac6"] = { author = "fulgentius-of-ruspe", label = "Dec. 26: Stephen, First martyr", locator = "3, 1-3.5-6", work = "sermon" },
    ["oor-68a40e697beeabff"] = { author = "leo-the-great", label = "23rd Sunday in Ord. Time", locator = "95, 6-8", work = "sermon" },
    ["oor-68b7eba94dd86f55"] = { author = "gregory-nazianzen", label = "3rd Week of Lent, Saturday", locator = "14, 38.40", work = "discourse" },
    ["oor-6941ee9ba08ac095"] = { author = "athanasius-of-alexandria", label = "5th Sunday of Lent", locator = "14, 1-2", work = "easter-letter" },
    ["oor-6a12ce3619d0332a"] = { author = "ambrose-of-milan", label = "Dec. 21", locator = "2, 19.22-23.26-27", work = "on-the-gospel-of-luke" },
    ["oor-6a4619ff2eea6a5e"] = { author = "leo-the-great", label = "4th Week of Lent, Thursday", locator = "15, 3-4", work = "sermon-on-the-passion" },
    ["oor-6ac446e37a41b085"] = { author = "second-vatican-council", label = "1st Week of Lent, Saturday", locator = "9-10", work = "pastoral-constitution-on-the-church-in-the-modern-world" },
    ["oor-6b20f2e5a775734d"] = { author = "letter-of-barnabas", label = "18th Week in Ord. Time, Wednesday", locator = "19, 1-3.5-7.8-12", work = "letter" },
    ["oor-6b281ba6f084270b"] = { author = "baldwin-of-canterbury", label = "18th Week in Ord. Time, Thursday", locator = "10 (PL 204513-14, 516)", work = "treatise" },
    ["oor-6b7b7aeae7ac0a63"] = { author = "paul-of-the-cross", label = "Oct. 19: Paul of the Cross, priest", locator = "1, 43", work = "letter" },
    ["oor-6be069260719f72d"] = { author = "jerome-emiliani", label = "Feb. 8: Jerome Emiliani", work = "letter-to-his-fellow-members" },
    ["oor-6c36953b7fb6fe6e"] = { author = "methodius-of-sicily", label = "Feb. 5: Agatha, virgin & martyr", work = "homily-on-saint-agatha" },
    ["oor-6cf4d8d1a5d28d9f"] = { author = "leo-the-great", label = "5th Week of Lent, Tuesday", locator = "8, 6-8", work = "sermon-on-the-passion" },
    ["oor-6d19a9161ac81110"] = { author = "augustine-of-hippo", label = "Dec. 27: John, apostle and evangelist", locator = "1, 1.3", work = "on-the-first-letter-of-john" },
    ["oor-6d1d4ec5cf9f9837"] = { author = "gregory-the-great", label = "8th Sunday in Ord. Time", locator = "1, 2.36", work = "moral-reflections-on-job" },
    ["oor-6d7cf283691a2d50"] = { author = "augustine-of-hippo", label = "Apr. 30: Pius V, pope", locator = "124, 5", work = "on-the-gospel-of-john" },
    ["oor-6d8b090684e1a9a3"] = { author = "baldwin-of-canterbury", label = "9th Week in Ord. Time, Friday", locator = "6 (PL 204, 466-67)", work = "sermon" },
    ["oor-6ed1109e039c627e"] = { author = "athanasius-of-alexandria", label = "4th Week of Lent, Friday", locator = "5, 1-2", work = "easter-letter" },
    ["oor-6ee1faee4ed6a0e2"] = { author = "paulinus-of-nola", label = "June 22: Paulinus of Nola, bishop", locator = "3 to Alypius 1.5.6", work = "letter" },
    ["oor-6f19a2ec16e56cad"] = { author = "gregory-of-agrigentum", label = "7th Week in Ord. Time, Saturday", locator = "10, 2", work = "on-ecclesiastes" },
    ["oor-6f31650c1a48e262"] = { author = "bernardine-of-siena", label = "Mar. 19: Joseph, Husband of Mary", locator = "2", work = "sermon" },
    ["oor-6fcc04945ec94fae"] = { author = "cyprian-of-carthage", label = "11th Week in Ord. Time, Saturday", locator = "28-30", work = "on-the-lords-prayer" },
    ["oor-7127da129dc1fa0b"] = { author = "athanasius-of-alexandria", label = "Jan. 1: Solemnity of Mary, Mother of God", locator = "5-9", work = "letter-to-epictetus" },
    ["oor-713865f820ca2336"] = { author = "letter-of-barnabas", label = "18th Week in Ord. Time, Monday", locator = "2, 6-10; 3, 1.3; 4, 10-14", work = "letter" },
    ["oor-72145f67e5f1f932"] = { author = "augustine-of-hippo", label = "14th Week in Ord. Time, Tuesday", locator = "33, 29", work = "on-psalm" },
    ["oor-724bf5d19dfebc36"] = { author = "imitation-of-christ", label = "3rd Week of Advent, Tuesday", locator = "2, 2-3", work = "book" },
    ["oor-7271de4a2dab6a81"] = { author = "augustine-of-hippo", label = "5th Sunday in Ord. Time", work = "on-the-letter-to-the-galatians-preface" },
    ["oor-72c45a2f72f8c753"] = { author = "polycarp-of-smyrna", label = "26th Week in Ord. Time, Thursday", locator = "12, 1—14", work = "to-the-philippians" },
    ["oor-73b67e73543c21af"] = { author = "letter-to-diognetus", label = "5th Week of Easter, Wednesday", locator = "5-6", work = "letter" },
    ["oor-73bd9c3b49dce7e9"] = { author = "john-chrysostom", label = "Sept. 13: John Chrysostom, bishop & doctor", locator = "1-3", work = "homily-before-his-exile" },
    ["oor-7431714d0e734a91"] = { author = "ignatius-of-antioch", label = "10th Week in Ord. Time, Tuesday", locator = "6, 1—9, 3", work = "to-the-romans" },
    ["oor-743a4eec8216f646"] = { author = "augustine-of-hippo", label = "Nov. 21: Presentation of Mary", locator = "25, 7-8", work = "sermon" },
    ["oor-743b40c1806f4c4d"] = { author = "gregory-of-nyssa", label = "12th Week in Ord. Time, Friday", locator = "6 on the Beatitudes (PG 44, 1266-67)", work = "discourse" },
    ["oor-749fb5ab22e44c05"] = { author = "bonaventure", label = "5th Week in Ord. Time, Monday", work = "breviloquium-prologue" },
    ["oor-74de0981745663bd"] = { author = "second-vatican-council", label = "Common of Virgins, alt.", locator = "1.5.6.12.25", work = "on-the-renewal-of-religious-life" },
    ["oor-75a777b358c2c88e"] = { author = "fulgentius-of-ruspe", label = "28th Week in Ord. Time, Monday", locator = "28, 16-19", work = "against-fabianus" },
    ["oor-75d60c77a635aac9"] = { author = "irenaeus-of-lyons", label = "3rd Week of Advent, Wednesday", locator = "4, 20, 4-5", work = "against-heresies" },
    ["oor-767d336d1e92c8c7"] = { author = "ignatius-of-antioch", label = "Oct. 17: Ignatius of Antioch, bishop & martyr", locator = "4, 1-2; 6, 1—8, 3", work = "to-the-romans" },
    ["oor-76971e45e90c39e0"] = { author = "peter-claver", label = "Sept. 9 [USA]: Peter Claver, priest", us_only = true, work = "letter-to-his-superior" },
    ["oor-76bf4dd085195a9e"] = { author = "teaching-of-the-twelve-apostles", label = "14th Week in Ord. Time, Wednesday", locator = "9, 1—10, 6; 14, 1-3", work = "didache" },
    ["oor-77466a2cc092aba7"] = { author = "cuthbert-of-lindisfarne", label = "May 25: Venerable Bede, priest & doctor", locator = "4-6", work = "from-a-letter-on-the-death-of-bede-the-venerable" },
    ["oor-779afe7e99d5cd7c"] = { author = "clement-of-rome", label = "1st Week in Ord. Time, Monday", locator = "59, 2—60, 4; 61, 3", work = "letter-to-the-corinthians" },
    ["oor-78cda71fe2e94532"] = { author = "augustine-of-hippo", label = "8th Week in Ord. Time, Tuesday", locator = "10, 1, 1—2, 2; 5, 7", work = "the-confessions" },
    ["oor-79e54db1752662df"] = { author = "justin-martyr", label = "3rd Week of Easter, Wednesday", locator = "61", work = "first-apology-in-defense-of-the-christians" },
    ["oor-7a15f9d0740b7461"] = { author = "william-of-saint-thierry", label = "Common of Doctors of the Church", work = "the-mirror-of-faith" },
    ["oor-7a1b2515bcdd4b27"] = { author = "leo-the-great", label = "6th Week of Easter, Wednesday", locator = "1, 2-4", work = "sermon-on-the-ascension" },
    ["oor-7a2ad51bd001e1ac"] = { author = "john-of-the-cross", label = "Dec. 14: John of the Cross, priest and doctor", locator = "36-37", work = "spiritual-canticle-red-b-str" },
    ["oor-7acfd5a8317dcba7"] = { author = "thomas-aquinas", label = "21st Week in Ord. Time, Monday", locator = "10, 3", work = "on-the-gospel-of-john" },
    ["oor-7b3aeb415d424cd4"] = { author = "john-leonardi", label = "Oct. 9: John Leonardi, priest", work = "letter-to-paul-v" },
    ["oor-7b8c9800f1669f03"] = { author = "augustine-of-hippo", label = "33rd Sunday in Ord. Time", locator = "96, 14.15", work = "on-psalm" },
    ["oor-7cbac5e19e39b6bd"] = { author = "lawrence-justinian", label = "Sat. after the 2nd Sun. after Pentecost: Immaculate Heart of Mary", locator = "8 on the purification of Mary", work = "sermon" },
    ["oor-7d6b9954f30406ce"] = { author = "augustine-of-hippo", label = "24th Week in Ord. Time, Tuesday", locator = "46, On Pastors, 4-5", work = "sermon" },
    ["oor-7da0dd1fb492774a"] = { author = "athanasius-of-alexandria", label = "6th Week in Ord. Time, Tuesday", locator = "2, 78.81-82", work = "against-the-arians" },
    ["oor-7e15fc874cda2e28"] = { author = "cyril-of-alexandria", label = "Aug. 5: Dedication of St. Mary Major", locator = "4 delivered at the Council of Ephesus", work = "homily" },
    ["oor-7e334f790df98ef9"] = { author = "augustine-of-hippo", label = "Nov. 22: Cecilia, virgin & martyr", locator = "33, 7-8", work = "on-psalm" },
    ["oor-7e589358035cf904"] = { author = "ignatius-of-antioch", label = "10th Week in Ord. Time, Monday", locator = "3, 1-5, 3", work = "to-the-romans" },
    ["oor-7e895fe475b50efa"] = { author = "catherine-of-siena", label = "30th Week in Ord. Time, Saturday", locator = "134", work = "dialogue-on-divine-providence" },
    ["oor-7f140600c7d0b3e5"] = { author = "cyril-of-jerusalem", label = "31st Week in Ord. Time, Wednesday", locator = "5, 10-11", work = "catechetical-instruction" },
    ["oor-7f1dc715968a1a97"] = { author = "baldwin-of-canterbury", label = "30th Week in Ord. Time, Friday", locator = "6 (PL 204, 451-53)", work = "treatise" },
    ["oor-7f474093c80f4a19"] = { author = "anonymous-servite", label = "Feb. 17: Seven Founders of the Order of Servites", locator = "1, 3.5.6.9.11", work = "an-account-of-the-origin-of-the-servite-order" },
    ["oor-7f7bff413fbd4ff6"] = { author = "ignatius-of-loyola", label = "July 31: Ignatius of Loyola, priest", locator = "1, 5-9", work = "life-of-st-ignatius-of-loyola-in-his-own-words-by-l-gonzalez" },
    ["oor-7f9ee11aaaaef835"] = { author = "basil-the-great", label = "3rd Week in Ord. Time, Tuesday", work = "detailed-rules-for-monks" },
    ["oor-7fceb3d229124e35"] = { author = "irenaeus-of-lyons", label = "18th Week in Ord. Time, Saturday", locator = "4, 17, 4-6", work = "against-heresies" },
    ["oor-7fec553298e1f820"] = { author = "basil-the-great", label = "7th Week of Easter, Tuesday", locator = "9, 22.23", work = "on-the-holy-spirit" },
    ["oor-8062e636b5a14a96"] = { author = "elizabeth-ann-seton", label = "Jan. 4 [USA]: Elizabeth Ann Seton", us_only = true, work = "conference-to-her-spiritual-daughters" },
    ["oor-80a53078c888e549"] = { author = "john-of-capistrano", label = "Oct. 23: John of Capistrano, priest", work = "on-the-mirror-of-the-clergy" },
    ["oor-812682837e10bdf8"] = { author = "bernard-of-clairvaux", label = "Nov. 1: All Saints", locator = "2", work = "sermon" },
    ["oor-8128b8b1717c6bea"] = { author = "ignatius-of-antioch", label = "27th Week in Ord. Time, Tuesday", locator = "1, 1—3, 2; 4, 1-2; 6, 1; 7, 1—8, 1", work = "to-the-trallians" },
    ["oor-818363d9d5d3fcc2"] = { author = "macarius-of-egypt", label = "34th Week in Ord. Time, Wednesday", locator = "28", work = "homily" },
    ["oor-81973b243fd4dad4"] = { author = "athanasius-of-alexandria", label = "Sunday after Pentecost: Trinity Sunday", locator = "1, 28-30", work = "letter-to-serapion" },
    ["oor-81ee4eee5a38dd48"] = { author = "augustine-of-hippo", label = "Common of Holy Men, alt.", locator = "96, 1.4.9", work = "sermon" },
    ["oor-822e39ef308bb614"] = { author = "leo-the-great", label = "22nd Week in Ord. Time, Friday", locator = "95, 2-3", work = "sermon" },
    ["oor-82596228eb1780bc"] = { author = "anonymous", label = "32nd Week in Ord. Time, Friday", locator = "15, 1—17, 2", work = "of-a-second-century-author" },
    ["oor-82fb61e255836c91"] = { author = "cyril-of-alexandria", label = "6th Week of Easter, Tuesday", locator = "11, 11", work = "on-the-gospel-of-john" },
    ["oor-83a2ce9370793483"] = { author = "acts-of-paul-miki", label = "Feb. 6: Paul Miki & Companions, martyrs", locator = "14, 109-110", work = "history-of-their-martyrdom" },
    ["oor-83c60e5cd59ea9bb"] = { author = "second-vatican-council", label = "7th Week of Easter, Wednesday", locator = "4 & 12", work = "dogmatic-constitution-on-the-church" },
    ["oor-83db00d0802387e4"] = { author = "origen", label = "June 2: Marcellinus & Peter, martyrs", locator = "41-42", work = "exhortation-to-martyrdom" },
    ["oor-83f2c3d925e44c3c"] = { author = "tertullian", label = "3rd Week of Lent, Thursday", locator = "28-29", work = "on-prayer" },
    ["oor-84a742f0612d34e4"] = { author = "leo-the-great", label = "23rd Week in Ord. Time, Monday", locator = "95, 8-9", work = "sermon" },
    ["oor-84acac2186d278fe"] = { author = "aelred-of-rievaulx", label = "1st Week of Lent, Friday", locator = "3, 5", work = "the-mirror-of-love" },
    ["oor-84bf49f882f2127d"] = { author = "augustine-of-hippo", label = "Dec. 6: Nicholas, bishop", locator = "123, 5", work = "on-the-gospel-of-john" },
    ["oor-84e191283cd9c138"] = { author = "leo-the-great", label = "Jan. 6 or the Sunday between Jan. 2 and 8: Epiphany", locator = "3, 1-3.5", work = "sermon-on-the-epiphany" },
    ["oor-851d5416ec009c17"] = { author = "cyril-of-alexandria", label = "3rd Week of Easter, Saturday", locator = "4:2", work = "on-the-gospel-of-john" },
    ["oor-858f1f05501f90c3"] = { author = "leo-the-great", label = "22nd Week in Ord. Time, Saturday", locator = "95, 4-6", work = "sermon" },
    ["oor-85b59b4b9ad49d84"] = { author = "second-vatican-council", label = "Mar. 23: Turibius de Mongrovejo, bishop", locator = "12-13.16", work = "on-the-pastoral-office-of-bishops" },
    ["oor-85ff74813dab983b"] = { author = "ambrose-of-milan", label = "15th Week in Ord. Time, Monday", locator = "8-11", work = "on-the-mysteries" },
    ["oor-86345d2ef3064359"] = { author = "bonaventure", label = "Friday after the 2nd Sunday after Pentecost: Sacred Heart", work = "on-the-tree-of-life" },
    ["oor-8639b62b793d4798"] = { author = "peter-damian", label = "Feb. 21: Peter Damian, bishop & doctor", locator = "8, 6", work = "letter" },
    ["oor-86530ec6ca897e18"] = { author = "none", label = "Easter Sunday", work = "the-readings-of-the-easter-vigil" },
    ["oor-86b0df4b76f04c55"] = { author = "charles-borromeo", label = "Nov. 4: Charles Borromeo, bishop", work = "sermon-given-at-his-last-synod" },
    ["oor-86bceadffe6fc51e"] = { author = "gregory-the-great", label = "9th Week in Ord. Time, Thursday", locator = "29, 2-4", work = "moral-reflections-on-job" },
    ["oor-8776a280f697f491"] = { author = "camillus-of-lellis", label = "July 14: Camillus de Lellis, priest", work = "the-life-of-saint-camillus-by-s-cicatelli" },
    ["oor-87b0cba33eb4d40a"] = { author = "leo-the-great", label = "2nd Sunday of Lent", locator = "51, 3-4.8", work = "sermon" },
    ["oor-891a62d93b2b2029"] = { author = "augustine-of-hippo", label = "25th Sunday in Ord. Time", locator = "46, On Pastors, 13", work = "sermon" },
    ["oor-8972a758744b70da"] = { author = "gregory-the-great", label = "Common of Saints, for religious", locator = "36, 11-13", work = "on-the-gospels" },
    ["oor-8a2e8f22c2d9fed5"] = { author = "second-vatican-council", label = "3rd Week in Ord. Time, Monday", locator = "48", work = "pastoral-constitution-on-the-church-in-the-modern-world" },
    ["oor-8a95fde2f71bc233"] = { author = "clement-of-rome", label = "30th Week in Ord. Time, Wednesday", locator = "30, 3-4; 34, 2—35, 5", work = "letter-to-the-corinthians" },
    ["oor-8ad4c818e1db171a"] = { author = "gregory-the-great", label = "4th Sunday of Easter", locator = "14, 3-6", work = "on-the-gospels" },
    ["oor-8b400af7b8e8dd46"] = { author = "hedwig-of-silesia", label = "Oct. 16: Hedwig, religious", work = "the-life-of-saint-hedwig" },
    ["oor-8ba75edf285990fb"] = { author = "peter-chrysologus", label = "4th Week of Easter, Tuesday", locator = "108 (On the body as a living sacrifice)", work = "sermon" },
    ["oor-8c7f1025e31ff904"] = { author = "john-de-brebeuf", label = "Oct. 19 [USA]: Isaac Jogues & John de Brebeuf, priests & martyrs, & Companions, martyrs", locator = "1503", us_only = true, work = "spiritual-diaries" },
    ["oor-8ce43dfb9c4a6a9f"] = { author = "braulio-of-saragossa", label = "Office of the Dead, alt.", locator = "19", work = "letter" },
    ["oor-8d3bc2b50d952384"] = { author = "imitation-of-christ", label = "16th Week in Ord. Time, Wednesday", locator = "2, 1-6", work = "book" },
    ["oor-8e840c15b7e424ef"] = { author = "alphonsus-liguori", label = "Aug. 1: Alphonsus Ligouri, bishop & doctor", work = "on-the-practice-of-loving-jesus-christ" },
    ["oor-8eb451e162a5686d"] = { author = "second-vatican-council", label = "4th Week of Lent, Saturday", locator = "37-38", work = "pastoral-constitution-on-the-church-in-the-modern-world" },
    ["oor-90afc0a632a5c825"] = { author = "anthony-of-padua", label = "June 13: Anthony of Padua, priest & doctor", locator = "1, 226", work = "sermon" },
    ["oor-90be2ca5f1df8c67"] = { author = "gregory-the-great", label = "9th Week in Ord. Time, Wednesday", locator = "23, 23-24", work = "moral-reflections-on-job" },
    ["oor-90f6a2a7bec121dc"] = { author = "anselm-of-canterbury", label = "1st Week of Advent, Friday", locator = "1", work = "proslogium" },
    ["oor-910c65a8ddb64f2b"] = { author = "zeno-of-verona", label = "8th Week in Ord. Time, Saturday", locator = "15, 2", work = "treatise" },
    ["oor-9210ee2de4d99ef7"] = { author = "ambrose-of-milan", label = "5th Week in Ord. Time, Wednesday", locator = "35, 4-6.13", work = "letter" },
    ["oor-921935ae59576db7"] = { author = "augustine-of-hippo", label = "2nd Week of Advent, Wednesday", locator = "110, 1-3", work = "on-psalm" },
    ["oor-927dfa12c93b7186"] = { author = "augustine-of-hippo", label = "Sept. 19: Januarius, bishop & martyr", locator = "340, 1", work = "sermon" },
    ["oor-93d8a737f0f36b43"] = { author = "origen", label = "34th Sunday in Ord. Time", locator = "25", work = "on-prayer" },
    ["oor-94ab0e9e97d55ae4"] = { author = "gregory-the-great", label = "8th Week in Ord. Time, Friday", locator = "10, 47-48", work = "moral-reflections-on-job" },
    ["oor-94cf62c833d6708e"] = { author = "polycarp-of-smyrna", label = "26th Week in Ord. Time, Monday", locator = "3, 1—5, 2", work = "to-the-philippians" },
    ["oor-953b39fd1c977605"] = { author = "pius-xi", label = "Nov. 12: Josaphat, bishop & martyr", work = "encyclical-letter-ecclesiam-dei" },
    ["oor-9551c174cb0772bd"] = { author = "jerome", label = "21st Week in Ord. Time, Friday", work = "on-joel" },
    ["oor-955a41d7381381ce"] = { author = "second-vatican-council", label = "3rd Week in Ord. Time, Saturday", locator = "18.22", work = "pastoral-constitution-on-the-church-in-the-modern-world" },
    ["oor-95f3f593358a6fa9"] = { author = "augustine-of-hippo", label = "Jan. 22: Vincent, Deacon & martyr", locator = "276, 1-2", work = "sermon" },
    ["oor-9619443f9ce21384"] = { author = "ambrose-of-milan", label = "15th Week in Ord. Time, Wednesday", locator = "19-21.24.26-28", work = "on-the-mysteries" },
    ["oor-978f5d02d4e94ecc"] = { author = "maximus-of-turin", label = "After Epiphany to the Baptism of the Lord, Friday", locator = "100, 1, 3", work = "sermon" },
    ["oor-98c424e8416977ad"] = { author = "hilary-of-poitiers", label = "Jan. 13: Hilary, bishop & doctor", locator = "1, 37-38", work = "on-the-trinity" },
    ["oor-997a7ea14e82a4ff"] = { author = "bede-the-venerable", label = "3rd Week of Easter, Monday", locator = "2", work = "on-the-first-letter-of-peter" },
    ["oor-99c7ab3914c8ed52"] = { author = "sulpicius-severus", label = "Nov. 11: Martin of Tours, bishop", locator = "3", work = "letter" },
    ["oor-9b110d5c10d9b4a2"] = { author = "anonymous-contemporary-of-casimir", label = "Mar. 4: Casimir", locator = "2-3", work = "the-life-of-saint-casimir" },
    ["oor-9b215c0b045ec459"] = { author = "john-eudes", label = "33rd Week in Ord. Time, Friday", work = "on-the-kingdom-of-jesus" },
    ["oor-9b5efcb9125dc518"] = { author = "peter-damian", label = "Apr. 23: George, martyr", locator = "3 on Saint George", work = "sermon" },
    ["oor-9b8d6169aec6bffe"] = { author = "cyprian-of-carthage", label = "11th Week in Ord. Time, Monday", locator = "8-9", work = "on-the-lords-prayer" },
    ["oor-9bcab68db674d97d"] = { author = "augustine-of-hippo", label = "July 29: Martha, Mary, and Lazarus", locator = "103, 1-2.6", work = "sermon" },
    ["oor-9bdcf85fb290b61b"] = { author = "bernard-of-clairvaux", label = "Oct. 7: Our Lady of the Rosary", work = "sermon-on-the-aqueduct" },
    ["oor-9bde840492855524"] = { author = "augustine-of-hippo", label = "Dec. 24", locator = "185, 1.2.3", work = "sermon" },
    ["oor-9c90fe4d06c4fc76"] = { author = "ambrose-of-milan", label = "15th Week in Ord. Time, Thursday", locator = "29-30.34-35.37.42", work = "on-the-mysteries" },
    ["oor-9d50571464503f64"] = { author = "augustine-of-hippo", label = "3rd Week of Advent , Friday", locator = "38, 13-14", work = "on-psalm" },
    ["oor-9dde514fe39474ee"] = { author = "ambrose-of-milan", label = "14th Week in Ord. Time, Thursday", locator = "119, 12, 13-14", work = "on-the-psalms" },
    ["oor-9de970b4e96efa32"] = { author = "ignatius-of-antioch", label = "2nd Sunday in Ord. Time", locator = "2, 2—5, 2", work = "to-the-ephesians" },
    ["oor-9e2fa7478fedce57"] = { author = "augustine-of-hippo", label = "Common of the Dedication of a Church, alt.", locator = "336, 1.6", work = "sermon" },
    ["oor-9ea830688d49f96d"] = { author = "bernardine-of-siena", label = "May 20: Bernardine of Siena, priest", locator = "49, 2", work = "sermon" },
    ["oor-9eaa7f0396e1a484"] = { author = "therese-of-lisieux", label = "Oct. 1: Theresa of the Child Jesus, virgin", work = "the-autobiography" },
    ["oor-9f9a2d500d018d5d"] = { author = "gaudentius-of-brescia", label = "5th Week of Easter, Thursday", locator = "2 (CSEL 68, 26.29-30)", work = "treatise" },
    ["oor-a05eb74b80c982e8"] = { author = "william-of-saint-thierry", label = "3rd Week of Advent, Monday", locator = "9-11", work = "on-contemplating-god" },
    ["oor-a0a091952c8f6485"] = { author = "columban", label = "21st Week in Ord. Time, Thursday", locator = "13, 2-3", work = "on-christ-the-font-of-life-instruction" },
    ["oor-a0dacc42ec474904"] = { author = "bernard-of-clairvaux", label = "20th Week in Ord. Time, Tuesday", locator = "2, 1-2.4", work = "in-praise-of-the-virgin-mother" },
    ["oor-a0daf3678dd617be"] = { author = "john-chrysostom", label = "2nd Week of Lent, Monday", locator = "3, 24-27", work = "catecheses" },
    ["oor-a18dfa43ac4e6636"] = { author = "caesarius-of-arles", label = "Nov. 9: Dedication of St. John Lateran", locator = "229, 1-3", work = "sermon" },
    ["oor-a1f0318b4e8f92a5"] = { author = "irenaeus-of-lyons", label = "June 28: Irenaeus, bishop & martyr", locator = "4, 20, 5-7", work = "against-heresies" },
    ["oor-a244f95d89895fc7"] = { author = "cyprian-of-carthage", label = "Jan. 20: Fabian, pope & martyr", locator = "9, 1; 8, 2-3", work = "letter" },
    ["oor-a2b169201f6c41a1"] = { author = "clement-of-rome", label = "14th Week in Ord. Time, Friday", locator = "50, 1—51, 3; 55, 1-4", work = "letter-to-the-corinthians" },
    ["oor-a31b8adde68a8957"] = { author = "columban", label = "28th Week in Ord. Time, Tuesday", locator = "12, 2-3", work = "instruction" },
    ["oor-a36de6c8dfc4e480"] = { author = "hilary-of-poitiers", label = "4th Week in Ord. Time, Monday", locator = "133", work = "on-psalm" },
    ["oor-a3d3847af3c561c3"] = { author = "cyril-of-jerusalem", label = "31st Week in Ord. Time, Thursday", locator = "5, 12-13", work = "catechetical-instruction" },
    ["oor-a4dab0f2a784529a"] = { author = "augustine-of-hippo", label = "13th Week in Ord. Time, Tuesday", locator = "47, 12-14", work = "sermon" },
    ["oor-a50ee2192a347f61"] = { author = "bernard-of-clairvaux", label = "Aug. 20: Bernard, abbot & doctor", locator = "83, 4-6", work = "on-the-song-of-songs" },
    ["oor-a51bfc20e8b06edd"] = { author = "augustine-of-hippo", label = "Aug. 28: Augustine, bishop & doctor", locator = "7, 10.18; 10, 27", work = "the-confessions" },
    ["oor-a52915bda8d8f858"] = { author = "augustine-of-hippo", label = "4th Week of Easter, Thursday", locator = "65, 1-3", work = "on-the-gospel-of-john" },
    ["oor-a591c2211809471d"] = { author = "dorotheus-of-gaza", label = "9th Week in Ord. Time, Tuesday", locator = "13, 2-3", work = "teaching" },
    ["oor-a5b3fea7d423e089"] = { author = "fulgentius-of-ruspe", label = "2nd Week in Ord. Time, Thursday", locator = "14, 36-37", work = "letter" },
    ["oor-a778f6acb3a2522e"] = { author = "letter-to-diognetus", label = "Dec. 18", locator = "8, 5—9, 6", work = "letter" },
    ["oor-a7b2a5ff193a7b02"] = { author = "augustine-of-hippo", label = "25th Week in Ord. Time, Wednesday", locator = "46, On Pastors, 20-21", work = "sermon" },
    ["oor-a7d97a42dcf05e77"] = { author = "augustine-of-hippo", label = "24th Week in Ord. Time, Wednesday", locator = "46, On Pastors, 6-7", work = "sermon" },
    ["oor-a8026222785e3a05"] = { author = "peter-chrysologus", label = "29th Week in Ord. Time, Saturday", locator = "117 (On the Incarnation of the Word)", work = "sermon" },
    ["oor-a830aba15b2fa9c8"] = { author = "gregory-the-great", label = "Feb. 10: Scholastica, virgin", locator = "2, 33", work = "book-of-dialogues" },
    ["oor-a86a046f3dd6c6e1"] = { author = "john-chrysostom", label = "Common of Holy Men", locator = "20, 4", work = "on-the-acts-of-the-apostles" },
    ["oor-a8e121ab35852e7a"] = { author = "thomas-aquinas", label = "9th Week in Ord. Time, Saturday", locator = "14, 2", work = "on-the-gospel-of-john" },
    ["oor-aa3743bd4e2bf4ba"] = { author = "ignatius-of-antioch", label = "27th Week in Ord. Time, Wednesday", locator = "8, 1—9, 2; 11, 1—13, 3", work = "to-the-trallians" },
    ["oor-aa661860cd143022"] = { author = "augustine-of-hippo", label = "1st Sunday of Lent", locator = "60, 2-3", work = "on-psalm" },
    ["oor-ab2e6f66b6228aa6"] = { author = "john-chrysostom", label = "Nov. 30: Andrew, apostle", locator = "19, 1", work = "on-the-gospel-of-john" },
    ["oor-abde2aab463fac0b"] = { author = "athanasius-of-alexandria", label = "30th Week in Ord. Time, Thursday", locator = "2, 78.79", work = "against-the-arians" },
    ["oor-ac8c43d650089be0"] = { author = "clement-of-rome", label = "Ash Wednesday", locator = "7:4—8:3; 8:5—9:1; 13:1-4; 19:2", work = "letter-to-the-corinthians" },
    ["oor-ac8e4654594659f8"] = { author = "bridget-of-sweden", label = "July 23: Bridget, religious", locator = "2, 2", work = "book-of-prayers" },
    ["oor-ad620e083faaeac1"] = { author = "cyril-of-jerusalem", label = "7th Week of Easter, Monday", locator = "16, 1, 11-12.16", work = "catechetical-instruction" },
    ["oor-addd6f71427bd7a8"] = { author = "peter-chrysologus", label = "After Epiphany to the Baptism of the Lord, Monday", locator = "160 (On the Incarnation & the Epiphany)", work = "sermon" },
    ["oor-aeddaed40c8dc9d7"] = { author = "gregory-the-great", label = "20th Week in Ord. Time, Monday", locator = "3, 39-40", work = "moral-reflections-on-job" },
    ["oor-aef184bbff6c64ec"] = { author = "cyprian-of-carthage", label = "11th Week in Ord. Time, Tuesday", locator = "11-12", work = "on-the-lords-prayer" },
    ["oor-af5ac4413db5c1f1"] = { author = "bruno-the-carthusian", label = "23rd Week in Ord. Time, Thursday", locator = "84", work = "on-psalm" },
    ["oor-afa9178e19f6a1df"] = { author = "leo-the-great", label = "July 16: Our Lady of Mount Carmel", locator = "1, 2.3", work = "sermon-on-the-birth-of-christ" },
    ["oor-b00ab5209cf73dc6"] = { author = "bernard-of-clairvaux", label = "6th Week in Ord. Time, Monday", locator = "15 of the occasional sermons", work = "sermon" },
    ["oor-b0c50931825a3ef1"] = { author = "bede-the-venerable", label = "Sept. 21: Matthew, apostle & evangelist", locator = "21", work = "homily" },
    ["oor-b0eb2e9e6a19a25b"] = { author = "cyril-of-jerusalem", label = "17th Week in Ord. Time, Thursday", locator = "18, 26-29", work = "catechetical-instruction" },
    ["oor-b10ca3002e33faac"] = { author = "caesarius-of-arles", label = "17th Week in Ord. Time, Monday", locator = "25, 1", work = "sermon" },
    ["oor-b12e1b4899349a61"] = { author = "pius-xii", label = "Nov. 13 [USA]: Frances Xavier Cabrini, virgin", us_only = true, work = "homily-at-the-canonization-of-frances-xavier-cabrini" },
    ["oor-b1884dc6c01fb187"] = { author = "thomas-aquinas", label = "33rd Week in Ord. Time, Saturday", locator = "6 on the Creed", work = "conference" },
    ["oor-b2490845a11b5ad6"] = { author = "augustine-of-hippo", label = "4th Sunday of Lent", locator = "34, 8-9", work = "on-the-gospel-of-john" },
    ["oor-b2921df2a14e0ee6"] = { author = "athanasius-of-alexandria", label = "May 2: Athnasius, bishop & doctor", locator = "8-9", work = "discourse-on-the-incarnation-of-the-word" },
    ["oor-b2bcfe6baa0b76c5"] = { author = "baldwin-of-canterbury", label = "20th Week in Ord. Time, Thursday", locator = "7: On the Hail Mary (PL 204, 477-78)", work = "treatise" },
    ["oor-b34dd6b4e33ae57c"] = { author = "john-chrysostom", label = "Common of Saints, for teachers", locator = "59, 5.7", work = "on-the-gospel-of-matthew" },
    ["oor-b4727bd576ced84c"] = { author = "bede-the-venerable", label = "Aug. 29: Beheading of John the Baptist, martyr", locator = "23", work = "homily" },
    ["oor-b4752cfd18385254"] = { author = "fulgentius-of-ruspe", label = "5th Week of Lent, Friday", locator = "22, 62", work = "to-peter-on-faith" },
    ["oor-b47e3072594be01a"] = { author = "thomas-aquinas", label = "Thursday (or Sunday) after Trinity Sunday: Corpus Christi", work = "a-work-on-the-feast-of-corpus-christi" },
    ["oor-b485aa5f76cdac53"] = { author = "cyril-of-jerusalem", label = "4th Week in Ord. Time, Thursday", locator = "13, 1.3.6.23", work = "catechetical-instruction" },
    ["oor-b4f6c43e57ea4b80"] = { author = "john-chrysostom", label = "21st Week in Ord. Time, Tuesday", locator = "2, 6", work = "on-the-devil-as-tempter" },
    ["oor-b5e3a2b7e9e755de"] = { author = "pseudo-ambrose", label = "26th Week in Ord. Time, Friday", work = "on-the-letter-to-the-philippians" },
    ["oor-b606c4ad2f4c089e"] = { author = "john-of-the-cross", label = "18th Week in Ord. Time, Friday", locator = "38", work = "spiritual-canticle-red-a-str" },
    ["oor-b6d3c6bad5165e3c"] = { author = "cyril-of-jerusalem", label = "1st Sunday of Advent", locator = "15, 1-3", work = "catechetical-instruction" },
    ["oor-b6f8e61360ba3f02"] = { author = "augustine-of-hippo", label = "25th Week in Ord. Time, Friday", locator = "46, On Pastors, 29-30", work = "sermon" },
    ["oor-b78d8ccda9c24783"] = { author = "hilary-of-poitiers", label = "4th Week of Easter, Wednesday", locator = "8, 13-16", work = "on-the-trinity" },
    ["oor-b8b0a57f7881bc9a"] = { author = "gregory-of-nyssa", label = "19th Week in Ord. Time, Thursday", locator = "PG 46, 259-262)", work = "on-christian-perfection" },
    ["oor-b8b31b1098f20c92"] = { author = "cyprian-of-carthage", label = "Common of Virgins", locator = "3-4, 22.23", work = "on-the-dress-of-virgins" },
    ["oor-b92ada8708b0e172"] = { author = "augustine-of-hippo", label = "34th Week in Ord. Time, Saturday", locator = "256, 1.2.3", work = "sermon" },
    ["oor-b92c9199efb7ea96"] = { author = "fulgentius-of-ruspe", label = "33rd Week in Ord. Time, Monday", locator = "2, 11, 2—12, 1.3-4", work = "on-forgiveness" },
    ["oor-b9d16416c6feefb4"] = { author = "hilary-of-poitiers", label = "2nd Week of Lent, Thursday", locator = "127, 1-3", work = "on-psalm" },
    ["oor-b9fb7338df28b457"] = { author = "gregory-of-nyssa", label = "12th Week in Ord. Time, Saturday", locator = "6 on the Beatitudes (PG 44, 1270-71)", work = "discourse" },
    ["oor-ba2fb53ebcc7ad71"] = { author = "maximus-the-confessor", label = "28th Week in Ord. Time, Wednesday", work = "an-inquiry-addressed-to-thalassius" },
    ["oor-ba30aa889d08de7e"] = { author = "augustine-of-hippo", label = "24th Week in Ord. Time, Saturday", locator = "46, On Pastors, 11-12", work = "sermon" },
    ["oor-bbdfc4dd7357cd4f"] = { author = "ambrose-of-milan", label = "15th Week in Ord. Time, Friday", locator = "43.47-49", work = "on-the-mysteries" },
    ["oor-bcba33bf5b3e2e52"] = { author = "augustine-of-hippo", label = "24th Week in Ord. Time, Thursday", locator = "46, On Pastors, 9", work = "sermon" },
    ["oor-bd0f0f7e394dde6f"] = { author = "leo-the-great", label = "5th Week in Ord. Time, Friday", locator = "7, 2.6", work = "sermon-on-the-birth-of-christ" },
    ["oor-bd9b5db30022b965"] = { author = "paul-vi", label = "13th Sunday in Ord. Time", locator = "1970", work = "homily-at-manila" },
    ["oor-bdce81425e66d61e"] = { author = "leo-the-great", label = "Dec. 17", locator = "31 to Flavianus 2-3", work = "letter" },
    ["oor-be0dd369d8789d60"] = { author = "ambrose-of-milan", label = "15th Sunday in Ord. Time", locator = "1-7", work = "on-the-mysteries" },
    ["oor-be11e2b46a6eb21b"] = { author = "theophilus-of-antioch", label = "3rd Week of Lent, Wednesday", locator = "1, 2-7", work = "book-addressed-to-autolycus" },
    ["oor-be924b9a231d9b97"] = { author = "anastasius-of-antioch", label = "Tuesday within the Octave of Easter", locator = "4, 1-2", work = "discourse" },
    ["oor-beb6f4a96d27b06e"] = { author = "augustine-of-hippo", label = "From Jan. 2 to Epiphany, Saturday", locator = "13, On the season", work = "sermon" },
    ["oor-bec8545306e1db76"] = { author = "origen", label = "4th Week of Lent, Monday", locator = "9, 5.10", work = "on-leviticus" },
    ["oor-bf1c181bcc80eed7"] = { author = "louis-of-france", label = "Aug. 25: Louis", work = "spiritual-testament-to-his-son" },
    ["oor-bff13b0eee1e9bb4"] = { author = "john-vianney", label = "Aug. 4: John Vianney, priest", locator = "87-89", work = "catechism" },
    ["oor-c085677d54d744df"] = { author = "polycarp-of-smyrna", label = "26th Week in Ord. Time, Wednesday", locator = "9, 1—11, 4", work = "to-the-philippians" },
    ["oor-c15d2535bac6ab5c"] = { author = "theodoret-of-cyr", label = "19th Week in Ord. Time, Monday", locator = "26-27", work = "on-the-incarnation" },
    ["oor-c2225a604c476307"] = { author = "cyprian-of-carthage", label = "Common of Several Martyrs", locator = "6, 1-2", work = "letter" },
    ["oor-c281321c12c9a436"] = { author = "gregory-the-great", label = "Oct. 18: Luke, evangelist", locator = "17, 1-3", work = "on-the-gospels" },
    ["oor-c2c0413bfeec9c74"] = { author = "gregory-nazianzen", label = "From Jan. 2 to Epiphany, Friday", locator = "634: Sunday of the Baptism of the Lord]", work = "cf-pg" },
    ["oor-c2d3634f9f4289df"] = { author = "augustine-of-hippo", label = "29th Week in Ord. Time, Wednesday", locator = "130 to Proba 12, 22—13, 24", work = "letter" },
    ["oor-c4609deb8ec6accb"] = { author = "augustine-of-hippo", label = "From Jan. 2 to Epiphany, Thursday", locator = "194, 3-4", work = "sermon" },
    ["oor-c511ea72a73742ae"] = { author = "second-vatican-council", label = "2nd Week of Easter, Saturday", locator = "5-6", work = "constitution-on-the-sacred-liturgy" },
    ["oor-c5666df5498d6cc8"] = { author = "cyprian-of-carthage", label = "Sept. 16: Cornelius, pope & martyr, & Cyprian, bishop & martyr, alt.", work = "proconsular-acts-of-the-martyrdom-of-saint-cyprian" },
    ["oor-c5e917bc278a8eef"] = { author = "bede-the-venerable", label = "Dec. 22", locator = "1, 46-55", work = "on-the-gospel-of-luke" },
    ["oor-c5f75ef26840cb18"] = { author = "cyprian-of-carthage", label = "Apr. 11: Stanislaus, bishop & martyr", locator = "58, 8-9.11", work = "letter" },
    ["oor-c68f8f21ea6a806e"] = { author = "clement-xii", label = "Dec. 23: John of Kanty, priest", work = "bull-on-the-canonization-of-saint-john-kanty" },
    ["oor-c6a5020313a073af"] = { author = "augustine-of-hippo", label = "24th Week in Ord. Time, Friday", locator = "46, On Pastors, 10-11", work = "sermon" },
    ["oor-c72688c10af9ebe3"] = { author = "cyprian-of-carthage", label = "11th Week in Ord. Time, Friday", locator = "23-24", work = "on-the-lords-prayer" },
    ["oor-c741c13080b166b1"] = { author = "raymond-of-penyafort", label = "Jan. 7: Raymond of Penyafort, priest", work = "letter" },
    ["oor-c7a5304e098ccd54"] = { author = "john-chrysostom", label = "Aug. 24: Bartholomew, apostle", locator = "4, 3.4", work = "on-the-first-letter-to-the-corinthians" },
    ["oor-c8f7209056750dd4"] = { author = "cyril-of-alexandria", label = "5th Week of Easter, Tuesday", locator = "10, 2", work = "on-the-gospel-of-john" },
    ["oor-c906ccb87f1bc6c7"] = { author = "augustine-of-hippo", label = "14th Week in Ord. Time, Saturday", locator = "127, 2", work = "on-psalm" },
    ["oor-c93b9f7477d0806c"] = { author = "hilary-of-poitiers", label = "7th Week of Easter, Friday", locator = "2, 1, 33.35", work = "on-the-trinity" },
    ["oor-c98a4734a7cf8939"] = { author = "john-chrysostom", label = "34th Week in Ord. Time, Thursday", locator = "33, 1.2", work = "on-the-gospel-of-matthew" },
    ["oor-ca583ee65a68b264"] = { author = "second-vatican-council", label = "Common of Pastors, for a priest", locator = "3, 12", work = "on-the-ministry-and-life-of-priests" },
    ["oor-ca7b6cb55648eb25"] = { author = "gregory-of-nyssa", label = "7th Week in Ord. Time, Monday", locator = "5", work = "on-ecclesiastes" },
    ["oor-ca89446cb35ed880"] = { author = "clement-of-rome", label = "1st Week in Ord. Time, Saturday", locator = "31-33", work = "letter-to-the-corinthians" },
    ["oor-cb06498d938bc42c"] = { author = "basil-the-great", label = "4th Week of Easter, Monday", locator = "15, 35-36", work = "on-the-holy-spirit" },
    ["oor-cb1d0df3ebcb06fd"] = { author = "peter-chrysologus", label = "July 4: Elizabeth of Portugal", work = "sermon-on-peace" },
    ["oor-cc04decbd82fe34d"] = { author = "gregory-the-great", label = "Sept. 29: Michael, Gabriel, & Raphael, Archangels", locator = "34, 8-9", work = "on-the-gospels" },
    ["oor-cc1a81f3b63ec625"] = { author = "theodoret-of-cyr", label = "19th Week in Ord. Time, Tuesday", locator = "28", work = "on-the-incarnation" },
    ["oor-cc4dbb1cf6bda8ef"] = { author = "sophronius-of-jerusalem", label = "Common of the Blessed Virgin Mary", locator = "2 on the Annunciation 21-22.26", work = "discourse" },
    ["oor-cd781820f7334ab7"] = { author = "cyril-of-alexandria", label = "4th Week of Easter, Saturday", locator = "15, 7", work = "on-the-letter-to-the-romans" },
    ["oor-ce13a71982702c77"] = { author = "anselm-of-canterbury", label = "Dec. 8: Immaculate Conception", locator = "52", work = "discourse" },
    ["oor-cf32cdf8ce603acd"] = { author = "second-vatican-council", label = "Feb. 3: Ansgar, bishop & martyr", locator = "23-24", work = "on-the-missionary-activity-of-the-church" },
    ["oor-cf81b59ae238f5b4"] = { author = "john-chrysostom", label = "16th Week in Ord. Time, Saturday", locator = "13, 1-2", work = "on-the-second-letter-to-the-corinthians" },
    ["oor-cf859eccefe8d189"] = { author = "augustine-of-hippo", label = "20th Week in Ord. Time, Wednesday", locator = "2, 92", work = "sermon-caillau-saint-yves" },
    ["oor-cff6a42a49162b94"] = { author = "cyprian-of-carthage", label = "1st Week of Advent, Saturday", locator = "13.15", work = "on-the-value-of-patience" },
    ["oor-d08c0d4b9ea2dae1"] = { author = "irenaeus-of-lyons", label = "Saturday after Ash Wednesday", locator = "4, 13, 4—14, 1", work = "against-heresies" },
    ["oor-d08c560134ae8594"] = { author = "basil-the-great", label = "1st Week in Ord. Time, Tuesday", work = "detailed-rules-for-monks" },
    ["oor-d0aa98d857466ffb"] = { author = "vincent-of-lerins", label = "27th Week in Ord. Time, Friday", locator = "23", work = "first-instruction" },
    ["oor-d16f43cb9004069d"] = { author = "cyril-of-jerusalem", label = "17th Week in Ord. Time, Wednesday", locator = "18, 23-25", work = "catechetical-instruction" },
    ["oor-d1da2e3f03c6378d"] = { author = "teresa-of-avila", label = "13th Week in Ord. Time, Wednesday", locator = "30, 1-4", work = "the-way-of-perfection" },
    ["oor-d21450a629bd2876"] = { author = "ignatius-of-antioch", label = "16th Sunday in Ord. Time", locator = "1, 1—5, 2", work = "to-the-magnesians" },
    ["oor-d298984042552593"] = { author = "augustine-of-hippo", label = "9th Sunday in Ord. Time", locator = "1, 1—2, 2.5, 5", work = "the-confessions" },
    ["oor-d2e022462f50fce9"] = { author = "augustine-of-hippo", label = "Aug. 27: Monica", locator = "9, 10-11", work = "the-confessions" },
    ["oor-d2fe09baae3763d7"] = { author = "conrad-of-marburg", label = "Nov. 17: Elizabeth of Hungary, religious", locator = "1232", work = "letter-in-the-year" },
    ["oor-d35def947b0df689"] = { author = "vincent-ferrer", label = "Apr. 5: Vincent Ferrer, priest", locator = "13", work = "on-the-spiritual-life" },
    ["oor-d3c7967c1bf5b18c"] = { author = "leo-the-great", label = "Common of Pastors, for a pope", locator = "3, 2-3", work = "sermon-on-his-own-birthday" },
    ["oor-d3eef7bd5e2e3ff1"] = { author = "ignatius-of-antioch", label = "9th Sunday in Ord. Time", locator = "1, 1—2, 2", work = "to-the-romans" },
    ["oor-d432024ca8150254"] = { author = "irenaeus-of-lyons", label = "Dec. 19", locator = "3, 20, 2-3", work = "against-heresies" },
    ["oor-d48a52e40ddd07a2"] = { author = "john-chrysostom", label = "Memorial of the Blessed Virgin Mary on Saturday, alt.", locator = "2", work = "on-the-grave-and-the-cross" },
    ["oor-d4d852ea5a094043"] = { author = "letter-of-barnabas", label = "18th Week in Ord. Time, Tuesday", locator = "5, 1-8; 6, 11-16", work = "letter" },
    ["oor-d527b469f0b21a40"] = { author = "anonymous", label = "7th Week of Easter, Saturday", locator = "8.1-3", work = "sermon-of-a-sixth-century-african-author" },
    ["oor-d5322af2131c3302"] = { author = "ambrose-of-milan", label = "Dec. 13: Lucy, virgin and martyr", locator = "12, 68, 74-75; 13, 77-78", work = "on-virginity" },
    ["oor-d57150b15549ffb7"] = { author = "augustine-of-hippo", label = "13th Week in Ord. Time, Friday", work = "on-the-predestination-of-the-saints" },
    ["oor-d5bd4b97e5a1747a"] = { author = "gregory-nazianzen", label = "Sunday after January 6: Baptism of the Lord", locator = "39, 14-16.20", work = "discourse" },
    ["oor-d5d8eda366339b4e"] = { author = "augustine-of-hippo", label = "Feb. 3: Blase, bishop & martyr", locator = "32", work = "sermon-guelferbytanus" },
    ["oor-d5dc4c94f90e01c6"] = { author = "bernard-of-clairvaux", label = "1st Week of Advent, Wednesday", locator = "5 on Advent 1-3", work = "sermon" },
    ["oor-d5eb1f5237870c0e"] = { author = "gregory-nazianzen", label = "1st Week of Lent, Monday", locator = "14, 23-25", work = "discourse" },
    ["oor-d606af02dc4840d9"] = { author = "leo-the-great", label = "Dec. 31: Octave of Christmas, Seventh Day", locator = "6, 2-3.5", work = "sermon" },
    ["oor-d66b65bbe1f0c6d5"] = { author = "second-vatican-council", label = "31st Sunday in Ord. Time", locator = "78", work = "pastoral-constitution-on-the-church-in-the-modern-world" },
    ["oor-d66b8d535f7fb0ac"] = { author = "bonaventure", label = "July 15: Bonaventure, bishop & doctor", locator = "7, 1.2.4.6", work = "on-the-journey-of-the-mind-to-god" },
    ["oor-d6f3cf5658659468"] = { author = "second-vatican-council", label = "Memorial of the Blessed Virgin Mary on Saturday, alt.", locator = "63-65", work = "dogmatic-constitution-on-the-church" },
    ["oor-d7c3de23a4f14080"] = { author = "ignatius-of-antioch", label = "17th Week in Ord. Time, Saturday", locator = "5, 1—8, 1.3", work = "to-polycarp" },
    ["oor-d7e902c1cba6744c"] = { author = "maximus-the-confessor", label = "4th Week of Lent, Wednesday", locator = "11", work = "letter" },
    ["oor-d847956a8f0ef83c"] = { author = "faustus-of-riez", label = "After Epiphany to the Baptism of the Lord, Saturday", locator = "5, 2", work = "sermon" },
    ["oor-d88745de9bd5690e"] = { author = "augustine-of-hippo", label = "Sept. 26: Cosmas & Damian, martyrs", locator = "329, 1-2", work = "sermon" },
    ["oor-d8f024dcf4a1962c"] = { author = "augustine-of-hippo", label = "34th Week in Ord. Time, Tuesday", locator = "35, 8-9", work = "on-the-gospel-of-john" },
    ["oor-da4b05cf224d2ae6"] = { author = "gregory-the-great", label = "July 22: Mary Magdalene", locator = "25, 1-2.4-5", work = "on-the-gospels" },
    ["oor-db4ff34b74c4db18"] = { author = "leo-the-great", label = "Mar. 25: Annunciation", locator = "28 to Flavianus 3-4", work = "letter" },
    ["oor-db5fba2fdec44548"] = { author = "augustine-of-hippo", label = "Ascension Thursday (or Sunday)", locator = "98, 1-2", work = "sermon-on-the-ascension-mai" },
    ["oor-dc0b64c10d58975e"] = { author = "jerome", label = "13th Week in Ord. Time, Thursday", locator = "42", work = "on-psalm" },
    ["oor-dc1123f2fd145781"] = { author = "clement-of-rome", label = "4th Week of Easter, Friday", locator = "36:1-2; 37—38", work = "letter-to-the-corinthians" },
    ["oor-dd6a90a8de3b0977"] = { author = "clement-of-rome", label = "June 30: First martyrs of the Church of Rome", locator = "5, 1—7, 4", work = "letter-to-the-corinthians" },
    ["oor-ddbbfd9a3f6aeb47"] = { author = "columban", label = "Nov. 23: Columban, abbot", locator = "11, 1-2", work = "instruction" },
    ["oor-ddd86979c78920dc"] = { author = "cyprian-of-carthage", label = "Aug. 13: Pontian, pope & martyr, & Hippolytus, priest & martyr", locator = "10, 2-3.5", work = "letter" },
    ["oor-de1aecf32e64c731"] = { author = "catherine-of-siena", label = "19th Sunday in Ord. Time", locator = "4, 13", work = "dialogue-on-divine-providence" },
    ["oor-df4e156d0ec90df9"] = { author = "irenaeus-of-lyons", label = "1st Week in Ord. Time, Wednesday", locator = "4, 6, 3.5.6.7", work = "against-heresies" },
    ["oor-e005bae1ff79ef69"] = { author = "origen", label = "22nd Week in Ord. Time, Wednesday", locator = "10, 20", work = "on-the-gospel-of-john" },
    ["oor-e0a50bac81c90dc1"] = { author = "second-vatican-council", label = "Common of Pastors, for a missionary", locator = "4-5", work = "on-the-missionary-activity-of-the-church" },
    ["oor-e1932e642530f743"] = { author = "hilary-of-poitiers", label = "25th Week in Ord. Time, Saturday", locator = "65, 14-15", work = "on-psalm" },
    ["oor-e1d5cf5ab3391053"] = { author = "patrick", label = "Mar. 17: Patrick, bishop", locator = "14-16", work = "the-confession" },
    ["oor-e1ec165bc0e965a4"] = { author = "andrew-of-crete", label = "Sept. 8: Birth of Mary", locator = "1", work = "discourse" },
    ["oor-e24aa01b62948dc8"] = { author = "maximus-of-turin", label = "5th Sunday of Easter", locator = "53, 1-2.4", work = "sermon" },
    ["oor-e3b723f54d36c32a"] = { author = "acts-of-perpetua-and-felicity", label = "Mar. 7: Perpetua & Felicity, martyrs", locator = "18,20-21", work = "the-story-of-the-death-of-martyrs-perpetua-and-felicity" },
    ["oor-e3deceb1552bc269"] = { author = "gregory-of-nyssa", label = "5th Week of Easter, Monday", locator = "1 on the resurrection of Christ", work = "discourse" },
    ["oor-e43039fd288e9fd9"] = { author = "maximus-the-confessor", label = "7th Sunday in Ord. Time", locator = "1, 4-5.16-17.23-24.26-28.30-40", work = "chapters-on-charity" },
    ["oor-e4501ef7ad2b6bfb"] = { author = "bernard-of-clairvaux", label = "3rd Week in Ord. Time, Wednesday", locator = "61, 3-5", work = "on-the-song-of-songs" },
    ["oor-e514fa744f51739c"] = { author = "john-of-god", label = "Mar. 8: John of God, religious", locator = "23-24.27", work = "letters-passim" },
    ["oor-e5591bb4c2952e23"] = { author = "peter-chrysologus", label = "July 30: Peter Chrysologus, bishop & doctor", locator = "148 (On Christ’s Incarnation)", work = "sermon" },
    ["oor-e65d228ee38259ee"] = { author = "aelred-of-rievaulx", label = "12th Week in Ord. Time, Wednesday", work = "on-spiritual-friendship" },
    ["oor-e6781d0b348a7e36"] = { author = "augustine-of-hippo", label = "13th Week in Ord. Time, Monday", locator = "47 On God’s flock 1.2.3.6", work = "sermon" },
    ["oor-e71ce3478a22259f"] = { author = "melito-of-sardis", label = "Monday within the Octave of Easter", locator = "2-7, 100-103", work = "easter-homily" },
    ["oor-e74b6dd3102bbddd"] = { author = "thomas-becket", label = "Dec. 29: Thomas Becket, bishop and martyr", locator = "74", work = "letter" },
    ["oor-e826e69eb408914a"] = { author = "aloysius-gonzaga", label = "June 21: Aloysius Gonzaga, religious", work = "from-a-letter-to-his-mother" },
    ["oor-e8270e15271f7e55"] = { author = "charles-borromeo", label = "1st Week of Advent, Monday", work = "pastoral-letter" },
    ["oor-e8503ea3ba501d6a"] = { author = "gregory-the-great", label = "Sept. 3: Gregory the Great, pope & doctor", locator = "1, 11, 4-6", work = "on-ezekiel" },
    ["oor-e94f994bf05ac50f"] = { author = "melito-of-sardis", label = "Holy Thursday", locator = "65-71", work = "easter-homily" },
    ["oor-e9723412ab8847a5"] = { author = "catherine-of-siena", label = "Apr. 29: Catherine of Siena, virgin & doctor", locator = "167", work = "dialogue-on-divine-providence" },
    ["oor-ea085eb29b1b08a9"] = { author = "leo-the-great", label = "2nd Week of Easter, Wednesday", locator = "12, 3.6-7", work = "sermon-on-the-passion" },
    ["oor-ea47dcaf74af954d"] = { author = "bernard-of-clairvaux", label = "23rd Week in Ord. Time, Tuesday", locator = "5 of the Occasional Sermons 1-4", work = "sermon" },
    ["oor-ebca829d5527f076"] = { author = "ignatius-of-antioch", label = "17th Week in Ord. Time, Friday", locator = "1, 1—4, 3", work = "to-polycarp" },
    ["oor-ebcaac25f1d8eed6"] = { author = "ambrose-of-milan", label = "27th Week in Ord. Time, Monday", locator = "1, 9, 34.38-39", work = "on-cain-and-abel" },
    ["oor-ebcf4b75eb67208e"] = { author = "cyril-of-alexandria", label = "Oct. 28: Simon & Jude, apostles", locator = "12, 1", work = "on-the-gospel-of-john" },
    ["oor-ec6dd85033a7de43"] = { author = "ambrose-of-milan", label = "10th Week in Ord. Time, Friday", locator = "1, 4.7-8", work = "on-the-psalms" },
    ["oor-ec70f0f380cf4b38"] = { author = "augustine-of-hippo", label = "Sunday within the Octave of Easter", locator = "8 for the Easter Octave 1, 4", work = "sermon" },
    ["oor-ed728724bb8ea67c"] = { author = "anonymous", label = "32nd Week in Ord. Time, Saturday", locator = "18, 1—20, 5", work = "of-a-second-century-author" },
    ["oor-edcf53ee3b099f7c"] = { author = "francis-of-paola", label = "Apr. 2: Francis of Paola Hermit", locator = "1486", work = "letter" },
    ["oor-ee0b45ebbfdc4b3c"] = { author = "leo-the-great", label = "Thursday after Ash Wednesday", locator = "6, 1-2", work = "sermon-on-lent" },
    ["oor-ee391bff19b66a06"] = { author = "lawrence-of-brindisi", label = "July 21: Lawrence of Brindisi, priest & doctor", locator = "2, 48.50.52", work = "sermon-on-lent" },
    ["oor-ee3efafef57a62be"] = { author = "cyprian-of-carthage", label = "34th Week in Ord. Time, Friday", locator = "18.24.26", work = "on-man-s-mortality" },
    ["oor-ee4a0eaadf1e3926"] = { author = "polycarp-of-smyrna", label = "26th Week in Ord. Time, Tuesday", locator = "6, 1—8, 2", work = "to-the-philippians" },
    ["oor-ee4d022d7377b33a"] = { author = "irenaeus-of-lyons", label = "2nd Week in Ord. Time, Saturday", locator = "4, 18, 1-2.4.5", work = "against-heresies" },
    ["oor-eedb5b143d3c7efb"] = { author = "aelred-of-rievaulx", label = "Common of the Blessed Virgin Mary, alt.", locator = "20 on the birthday of Mary", work = "sermon" },
    ["oor-eedba59a34252018"] = { author = "benedict-of-nursia", label = "July 11: Benedict, abbot", locator = "72", work = "the-rule-of-benedict-prologue" },
    ["oor-ef67e7575cbd3ac0"] = { author = "second-vatican-council", label = "6th Week in Ord. Time, Saturday", locator = "48", work = "pastoral-constitution-on-the-church-in-the-modern-world" },
    ["oor-efcd1166aa3e6389"] = { author = "pius-xii", label = "Aug. 15: Assumption", work = "apostolic-constitution-munificentissimus-deus" },
    ["oor-f145f6cddb393da6"] = { author = "origen", label = "10th Week in Ord. Time, Wednesday", locator = "4, 1", work = "on-the-book-of-joshua" },
    ["oor-f15f46e6cec6e1b9"] = { author = "gregory-of-nyssa", label = "33rd Week in Ord. Time, Thursday", locator = "2", work = "on-the-song-of-songs" },
    ["oor-f1afd9de6532c36b"] = { author = "anthony-claret", label = "Oct. 24: Anthony Claret, bishop", work = "l-egoismo-vinto" },
    ["oor-f246a1ccbb74f876"] = { author = "ignatius-of-antioch", label = "16th Week in Ord. Time, Tuesday", locator = "10, 1-15", work = "to-the-magnesians" },
    ["oor-f269d853a82f411d"] = { author = "fulgentius-of-ruspe", label = "2nd Week of Easter, Tuesday", locator = "2, 11-12", work = "to-monimus" },
    ["oor-f4a3fe57022b0b11"] = { author = "clement-of-rome", label = "30th Sunday in Ord. Time", locator = "19, 2—20, 12", work = "letter-to-the-corinthians" },
    ["oor-f4e7de968e7999e7"] = { author = "leo-the-great", label = "Dec. 25: Christmas", locator = "1, 1-3", work = "sermon-on-the-birth-of-christ" },
    ["oor-f5994e043356a4fe"] = { author = "isidore-of-seville", label = "Apr. 4: Isidore, bishop & doctor", locator = "3, 8-10", work = "book-of-maxims" },
    ["oor-f680ae02bc115f0a"] = { author = "amadeus-of-lausanne", label = "Aug. 22: Queenship of Mary", locator = "7", work = "homily-on-mary" },
    ["oor-f6d73cf0b9c39dde"] = { author = "gregory-the-great", label = "July 3: Thomas, apostle", locator = "26, 7-9", work = "on-the-gospels" },
    ["oor-f84ec735896a2aaa"] = { author = "ignatius-of-antioch", label = "27th Week in Ord. Time, Thursday", locator = "1, 1—2, 1; 3, 2-5", work = "to-the-philadelphians" },
    ["oor-f856146506e266c3"] = { author = "cyril-of-jerusalem", label = "13th Week in Ord. Time, Saturday", locator = "1, 2-3.5-6", work = "catechetical-instruction" },
    ["oor-f86e3c09536f8229"] = { author = "bernard-of-clairvaux", label = "Dec. 29: Octave of Christmas, Fifth Day", locator = "1 on the Epiphany 1-2", work = "sermon" },
    ["oor-f8d4f9164b130635"] = { author = "gregory-of-nyssa", label = "12th Week in Ord. Time, Tuesday", locator = "PG 46, 283-286)", work = "on-christian-perfection" },
    ["oor-f8db5548815f7313"] = { author = "anonymous-on-norbert", label = "June 6: Norbert, bishop", work = "the-life-of-saint-norbert" },
    ["oor-f9b08203946e3951"] = { author = "john-bosco", label = "Jan. 31: John Bosco, priest", locator = "4, 201-203", work = "letter" },
    ["oor-fa6d57b2e4c40b59"] = { author = "cyril-of-alexandria", label = "28th Sunday in Ord. Time", locator = "14", work = "on-haggai" },
    ["oor-fa832758c74644c4"] = { author = "pseudo-chrysostom", label = "2nd Week of Easter, Monday", work = "easter-homily-by-pseudo-chrysostom" },
    ["oor-fb063e6b9403cc90"] = { author = "ambrose-of-milan", label = "6th Week in Ord. Time, Thursday", locator = "37, 65-66", work = "on-the-psalms" },
    ["oor-fba8d768b5e3da7e"] = { author = "imitation-of-christ", label = "22nd Week in Ord. Time, Tuesday", locator = "3, 14-15", work = "book" },
    ["oor-fbaff64786ed6f48"] = { author = "ephrem-the-syrian", label = "June 9: Ephrem, Deacon & doctor", locator = "3, 2.4-5", work = "sermon" },
    ["oor-fc1886860db908cc"] = { author = "peter-chrysologus", label = "3rd Week of Lent, Tuesday", locator = "43 (On prayer, fasting, mercy)", work = "sermon" },
    ["oor-fc560d794214117b"] = { author = "origen", label = "Common of the Dedication of a Church", locator = "9, 1-2", work = "on-the-book-of-joshua" },
    ["oor-fcca0ae8ea8e5704"] = { author = "gertrude-the-great", label = "Nov. 16: Gertrude, virgin", locator = "2, 23, 1.3-5.8.10", work = "revelations" },
    ["oor-fd1c988a152dddc2"] = { author = "anonymous-on-peter-chanel", label = "Apr. 28: Peter Chanel, priest & martyr", work = "eulogy-for-peter-chanel" },
    ["oor-fd33679097e6cb57"] = { author = "eusebius-of-vercelli", label = "Aug. 2: Eusebius of Vercelli, bishop", locator = "2, 1.3—2, 3; 10, 1—11, 1", work = "letter" },
    ["oor-fe30033eb74f2dfe"] = { author = "anonymous", label = "32nd Week in Ord. Time, Thursday", locator = "13, 2—14, 5", work = "of-a-second-century-author" },
    ["oor-fe4cb3d6647b1b4a"] = { author = "john-baptist-de-la-salle", label = "Apr. 7: John Baptist de La Salle, priest", locator = "201", work = "meditation" },
    ["oor-fe5560beed53cba0"] = { author = "bernard-of-clairvaux", label = "23rd Week in Ord. Time, Wednesday", locator = "5 of the Occasional Sermons 4-5", work = "sermon" },
    ["oor-ff196b8165a8467c"] = { author = "thomas-aquinas", label = "Jan. 28: Thomas Aquinas, priest & doctor", locator = "6 on the Creed", work = "conference" },
    ["oor-ff6498221d6943ff"] = { author = "jerome", label = "7th Week in Ord. Time, Wednesday", work = "on-ecclesiastes" },
}
