-- Calendar of AR: changes to the General Roman Calendar.
-- Origin: romcal @ 30344b3 (MIT), normalized in parked/epub/data/calendars/ar-overlay.json;
-- transfers also from parked/epub/data/calendars/transfer-decisions.json.
-- transfers: solemnities moved to Sunday (epiphany, ascension, corpus_christi).
-- celebrations: added, or replacing the general celebration with the same id; title: the
-- calendar's own title for it (tag celebration.<title>), e.g. "..., Patron of Europe".
return {
    celebrations = {
        {
            id = "laura-vicuna-virgin",
            date = "01-22",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "our-lady-queen-of-peace",
            date = "01-24",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "blessed_virgin_mary" },
        },
        {
            id = "turibius-of-mogrovejo-bishop",
            date = "04-27",
            rank = "feast",
            precedence = 8,
            colors = { "white" },
            commons = { "bishops" },
            saints = { "turibius-of-mogrovejo-bishop" },
        },
        {
            id = "our-lady-of-lujan",
            date = "05-08",
            rank = "solemnity",
            precedence = 4,
            colors = { "white" },
            commons = { "blessed_virgin_mary" },
        },
        {
            id = "isidore-the-farmer",
            date = "05-15",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "saints" },
        },
        {
            id = "luigi-orione-priest",
            date = "05-16",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "our-lady-of-itati",
            date = "07-09",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "blessed_virgin_mary" },
        },
        {
            id = "augustine-zhao-rong-priest-and-companions-martyrs",
            date = "07-10",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "red" },
            commons = { "martyrs" },
            plural = true,
            saints = { "augustine-zhao-rong-priest", "companions-martyrs" },
        },
        {
            id = "our-lady-of-mount-carmel",
            date = "07-16",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "blessed_virgin_mary" },
        },
        {
            id = "sharbel-makhluf-priest",
            date = "07-23",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "pastors", "monks" },
            saints = { "sharbel-makhluf-priest" },
        },
        {
            id = "francis-solanus-priest",
            date = "07-24",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "missionaries" },
        },
        {
            id = "roch-of-montpellier",
            date = "08-16",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "saints" },
        },
        {
            id = "zepherin-namuncura",
            date = "08-26",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "rose-of-lima-virgin",
            date = "08-30",
            rank = "feast",
            precedence = 8,
            colors = { "white" },
            commons = { "virgins" },
            saints = { "rose-of-lima-virgin" },
        },
        {
            id = "our-lady-of-mercy",
            date = "09-24",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "blessed_virgin_mary" },
        },
        {
            id = "benedict-of-jesus-valdivielso-saez-religious",
            date = "10-09",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "our-lady-of-the-pillar",
            date = "10-12",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "blessed_virgin_mary" },
        },
        {
            id = "roch-gonzalez-alphonsus-rodriguez-and-john-del-castillo-priests",
            date = "11-17",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "martyrs" },
            plural = true,
            saints = {
                "roch-gonzalez-priest",
                "alphonsus-rodriguez-priest",
                "john-del-castillo-priest",
            },
        },
        {
            id = "elizabeth-of-hungary-religious",
            date = "11-18",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "mercy_workers" },
            saints = { "elizabeth-of-hungary-religious" },
        },
        {
            id = "our-lady-of-guadalupe",
            date = "12-12",
            title = "our-lady-of-guadalupe-patroness-of-the-americas",
            rank = "feast",
            precedence = 8,
            colors = { "white" },
            commons = { "blessed_virgin_mary" },
        },
        {
            id = "our-lady-of-the-valley",
            date = { fn = "divine_mercy_sunday", offset = 6 },
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "blessed_virgin_mary" },
        },
    },
    transfers = {},
}
