-- Calendar of BO: changes to the General Roman Calendar.
-- Origin: romcal @ 30344b3 (MIT), normalized in parked/epub/data/calendars/bo-overlay.json;
-- transfers also from parked/epub/data/calendars/transfer-decisions.json.
-- transfers: solemnities moved to Sunday (epiphany, ascension, corpus_christi).
-- celebrations: added, or replacing the general celebration with the same id; title: the
-- calendar's own title for it (tag celebration.<title>), e.g. "..., Patron of Europe".
return {
    celebrations = {
        {
            id = "philip-of-jesus-de-las-casas-paul-miki-and-companions-martyrs",
            date = "02-06",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            saints = {
                "philip-of-jesus-de-las-casas-martyr",
                "paul-miki-martyr",
                "companions-martyrs",
            },
        },
        {
            id = "nazaria-ignacia-of-saint-teresa-of-jesus-march-mesa-virgin",
            date = "03-23",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
        },
        {
            id = "turibius-of-mogrovejo-bishop",
            date = "03-23",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "bishops" },
            saints = { "turibius-of-mogrovejo-bishop" },
        },
        {
            id = "mariana-of-jesus-de-paredes-virgin",
            date = "05-25",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "virgins" },
        },
        {
            id = "camillus-de-lellis-priest",
            date = "07-12",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "mercy_workers" },
            saints = { "camillus-de-lellis-priest" },
        },
        {
            id = "francis-solanus-priest",
            date = "07-14",
            rank = "feast",
            precedence = 8,
            colors = { "white" },
            commons = { "missionaries" },
        },
        {
            id = "our-lady-of-mount-carmel",
            date = "07-16",
            rank = "solemnity",
            precedence = 4,
            colors = { "white" },
            commons = { "blessed_virgin_mary" },
        },
        {
            id = "rose-of-lima-virgin",
            date = "08-23",
            rank = "feast",
            precedence = 8,
            colors = { "white" },
            commons = { "virgins" },
            saints = { "rose-of-lima-virgin" },
        },
        {
            id = "john-macias-religious",
            date = "09-18",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "religious" },
        },
        {
            id = "louis-bertrand-priest",
            date = "10-09",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "miguel-febres-cordero-religious",
            date = "10-21",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "anthony-mary-claret-bishop",
            date = "10-24",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "missionaries", "bishops" },
            saints = { "anthony-mary-claret-bishop" },
        },
        {
            id = "martin-de-porres-religious",
            date = "11-03",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "religious" },
            saints = { "martin-de-porres-religious" },
        },
        {
            id = "roch-gonzalez-alphonsus-rodriguez-and-john-del-castillo-priests",
            date = "11-19",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "martyrs" },
            plural = true,
            saints = {
                "roch-gonzalez-priest",
                "alphonsus-rodriguez-priest",
                "john-del-castillo-priest",
            },
        },
        {
            id = "our-lady-of-guadalupe",
            date = "12-12",
            title = "our-lady-of-guadalupe-patroness-of-the-americas",
            rank = "feast",
            precedence = 8,
            colors = { "white" },
            commons = { "blessed_virgin_mary" },
        },
        {
            id = "our-lord-jesus-christ-the-eternal-high-priest",
            date = { fn = "pentecost_sunday", offset = 4 },
            rank = "feast",
            precedence = 8,
            colors = { "white" },
            office = "weekday",
        },
    },
    transfers = {},
}
