-- Calendar of CA: changes to the General Roman Calendar.
-- Origin: romcal @ 30344b3 (MIT), normalized in parked/epub/data/calendars/ca-overlay.json;
-- transfers also from parked/epub/data/calendars/transfer-decisions.json.
-- transfers: solemnities moved to Sunday (epiphany, ascension, corpus_christi).
-- celebrations: added, or replacing the general celebration with the same id; title: the
-- calendar's own title for it (tag celebration.<title>), e.g. "..., Patron of Europe".
return {
    celebrations = {
        {
            id = "andre-bessette-religious",
            date = "01-07",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "religious" },
        },
        {
            id = "raymond-of-penyafort-priest",
            date = "01-08",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "pastors" },
            saints = { "raymond-of-penyafort-priest" },
        },
        {
            id = "marguerite-bourgeoys-virgin",
            date = "01-12",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "virgins" },
        },
        {
            id = "joseph-spouse-of-mary",
            date = "03-19",
            title = "joseph-spouse-of-mary-patron-of-canada",
            rank = "solemnity",
            precedence = 4,
            colors = { "white" },
            exceptions = {
                { move = { offset = 1 }, when = { weekday = "sunday" } },
                {
                    move = { fn = "palm_sunday", offset = -1 },
                    when = { between = { "palm_sunday", "divine_mercy_sunday" }, inclusive = true },
                },
            },
            obligation = true,
            saints = { "joseph-spouse-of-mary" },
        },
        {
            id = "kateri-tekakwitha-virgin",
            date = "04-17",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "virgins" },
        },
        {
            id = "marie-anne-blondin-virgin",
            date = "04-18",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "virgins" },
        },
        {
            id = "our-lady-of-good-counsel",
            date = "04-26",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "mary-of-the-incarnation-marie-guyart-religious",
            date = "04-30",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "religious" },
        },
        {
            id = "pius-v-pope",
            date = "05-01",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "pope_or_bishop" },
            saints = { "pius-v-pope" },
        },
        {
            id = "marie-leonie-paradis-virgin",
            date = "05-04",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "virgins" },
        },
        {
            id = "francois-de-montmorency-laval-bishop",
            date = "05-06",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "bishops" },
        },
        {
            id = "mary-catherine-of-saint-augustine-catherine-de-simon-de-longpre-virgin",
            date = "05-08",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "virgins", "mercy_workers" },
        },
        {
            id = "eugene-de-mazenod-bishop",
            date = "05-21",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "bishops", "missionaries" },
        },
        {
            id = "louis-zephirin-moreau-bishop",
            date = "05-24",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "bishops" },
        },
        {
            id = "nykyta-budka-and-vasyl-velychkovsky-bishops",
            date = "06-27",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "martyrs", "pastors" },
            plural = true,
            saints = { "nykyta-budka-bishop", "vasyl-velychkovsky-bishop" },
        },
        {
            id = "canada-day",
            date = "07-01",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "joachim-and-anne-parents-of-mary",
            date = "07-26",
            title = "joachim-and-anne-patroness-of-the-province-of-quebec-parents-of-mary",
            rank = "feast",
            precedence = 8,
            colors = { "white" },
            saints = { "anne-mother-of-mary", "joachim-father-of-mary" },
        },
        {
            id = "frederic-janssoone-priest",
            date = "08-05",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "pastors" },
        },
        {
            id = "andre-grasset-priest",
            date = "09-02",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "martyrs", "pastors" },
        },
        {
            id = "dina-belanger-virgin",
            date = "09-04",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "virgins" },
        },
        {
            id = "emilie-tavernier-gamelin-religious",
            date = "09-24",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "religious" },
        },
        {
            id = "cosmas-of-cilicia-and-damian-of-cilicia-martyrs",
            date = "09-25",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "red" },
            commons = { "martyrs" },
            plural = true,
            saints = { "cosmas-of-cilicia-martyr", "damian-of-cilicia-martyr" },
        },
        {
            id = "john-de-brebeuf-isaac-jogues-priests-and-companions-martyrs",
            date = "09-26",
            title = "john-de-brebeuf-isaac-jogues-priests-and-companions-martyrs-copatrons-of-canada",
            rank = "feast",
            precedence = 8,
            colors = { "red" },
            commons = { "missionary_martyrs" },
            plural = true,
            saints = { "john-de-brebeuf-priest", "isaac-jogues-priest", "companions-martyrs" },
        },
        {
            id = "marie-rose-durocher-virgin",
            date = "10-06",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "virgins" },
        },
        {
            id = "marguerite-dyouville-religious",
            date = "10-16",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "religious" },
        },
        {
            id = "hedwig-of-silesia-religious",
            date = "10-20",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "religious", "holy_women" },
            saints = { "hedwig-of-silesia-religious" },
        },
        {
            id = "margaret-mary-alacoque-virgin",
            date = "10-20",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "virgins" },
            saints = { "margaret-mary-alacoque-virgin" },
        },
        {
            id = "dedication-of-consecrated-churches",
            date = "10-25",
            rank = "solemnity",
            precedence = 4,
            colors = { "white" },
            commons = { "dedication_anniversary__inside" },
            omissible = true,
        },
        {
            id = "remembrance-day",
            date = "11-11",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            omissible = true,
        },
        {
            id = "our-lady-of-guadalupe",
            date = "12-12",
            title = "our-lady-of-guadalupe-patroness-of-the-americas",
            rank = "feast",
            precedence = 8,
            colors = { "white" },
            commons = { "blessed_virgin_mary" },
        },
        {
            id = "thanksgiving-day",
            date = { month = 10, nth = 2, weekday = "monday" },
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "labor-day",
            date = { month = 9, nth = 1, weekday = "monday" },
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
    },
    transfers = { ascension = true, corpus_christi = true, epiphany = true },
}
