-- Calendar of CN: changes to the General Roman Calendar.
-- Origin: romcal @ 30344b3 (MIT), normalized in parked/epub/data/calendars/cn-overlay.json;
-- transfers also from parked/epub/data/calendars/transfer-decisions.json.
-- transfers: solemnities moved to Sunday (epiphany, ascension, corpus_christi).
-- celebrations: added, or replacing the general celebration with the same id; title: the
-- calendar's own title for it (tag celebration.<title>), e.g. "..., Patron of Europe".
return {
    celebrations = {
        {
            id = "odoric-of-pordenone-priest",
            date = "01-14",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "francis-ferdinand-de-capillas-priest",
            date = "01-15",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "lawrence-bai-xiaoman-martyr",
            date = "01-23",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "augustine-zhao-rong-priest",
            date = "01-27",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "joseph-freinademetz-priest",
            date = "01-29",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "laurence-wang-bing-and-companions-martyrs",
            date = "01-29",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            saints = { "laurence-wang-bing-martyr", "companions-martyrs" },
        },
        {
            id = "john-of-triora-priest",
            date = "02-13",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "martin-wu-xuesheng-and-companions-martyrs",
            date = "02-17",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            saints = { "martin-wu-xuesheng-martyr", "companions-martyrs" },
        },
        {
            id = "lucy-yi-zhenmei-virgin",
            date = "02-19",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "paul-liu-hanzuo-priest",
            date = "02-21",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "aloysius-versiglia-bishop-and-callistus-caravario-priest-martyrs",
            date = "02-25",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            saints = { "aloysius-versiglia-bishop", "callistus-caravario-priest" },
        },
        {
            id = "agnes-cao-guiying-martyr",
            date = "03-01",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "joseph-zhang-dapeng-martyr",
            date = "03-12",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "mary-assunta-pallotta-virgin",
            date = "04-08",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "john-martin-moye-priest",
            date = "05-04",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "peter-liu-wenyuan-martyr",
            date = "05-14",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "peter-sanz-bishop",
            date = "05-27",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "joachim-he-kaizhi-martyr",
            date = "05-29",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "gregory-grassi-francis-fogolla-and-anthony-fantosati-bishops-and-companions-martyrs",
            date = "06-20",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            saints = {
                "gregory-grassi-bishop",
                "francis-fogolla-bishop",
                "anthony-fantosati-bishop",
                "companions-martyrs",
            },
        },
        {
            id = "joseph-yuan-gengyin-priest",
            date = "06-23",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "seven-martyred-nuns-from-the-franciscan-missionaries-of-mary",
            date = "07-08",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "augustine-zhao-rong-priest-and-companions-martyrs",
            date = "07-09",
            rank = "solemnity",
            precedence = 4,
            colors = { "red" },
            commons = { "martyrs" },
            plural = true,
            saints = { "augustine-zhao-rong-priest", "companions-martyrs" },
        },
        {
            id = "leo-ignatius-mangin-priest-and-companions-martyrs",
            date = "07-20",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            saints = { "leo-ignatius-mangin-priest", "companions-martyrs" },
        },
        {
            id = "alberic-crescitelli-priest",
            date = "07-21",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "paul-chen-changpin-and-companions-martyrs",
            date = "07-28",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            saints = { "paul-chen-changpin-martyr", "companions-martyrs" },
        },
        {
            id = "maurice-tornay-priest",
            date = "08-11",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "john-gabriel-perboyre-priest",
            date = "09-11",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "francis-diaz-del-rincon-priest-and-companions-martyrs",
            date = "10-27",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "martyrs" },
            plural = true,
            saints = { "francis-diaz-del-rincon-priest", "companions-martyrs" },
        },
        {
            id = "peter-wu-guosheng-martyr",
            date = "11-07",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "gabriel-taurin-dufresse-bishop",
            date = "11-27",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "our-lord-jesus-christ-the-eternal-high-priest",
            date = { fn = "pentecost_sunday", offset = 4 },
            rank = "feast",
            precedence = 8,
            colors = { "white" },
            office = "weekday",
        },
        {
            id = "our-lady-of-china",
            date = { month = 5, nth = 2, weekday = "saturday" },
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "blessed_virgin_mary" },
        },
    },
    transfers = {},
}
