-- Calendar of DE: changes to the General Roman Calendar.
-- Origin: romcal @ 30344b3 (MIT), normalized in parked/epub/data/calendars/de-overlay.json;
-- transfers also from parked/epub/data/calendars/transfer-decisions.json.
-- transfers: solemnities moved to Sunday (epiphany, ascension, corpus_christi).
-- celebrations: added, or replacing the general celebration with the same id; title: the
-- calendar's own title for it (tag celebration.<title>), e.g. "..., Patron of Europe".
return {
    celebrations = {
        {
            id = "john-nepomucene-neumann-bishop",
            date = "01-05",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "valentine-of-raetia-bishop",
            date = "01-07",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "severinus-of-noricum-monk",
            date = "01-08",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "meinrad-of-einsiedeln-martyr",
            date = "01-21",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "henry-suso-priest",
            date = "01-23",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "rabanus-maurus-bishop",
            date = "02-04",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "cyril-constantine-the-philosopher-monk-and-methodius-michael-of-thessaloniki-bishop",
            date = "02-14",
            title = "cyril-constantine-the-philosopher-monk-and-methodius-michael-of-thessaloniki-bishop-copatrons-of-europe",
            rank = "feast",
            precedence = 8,
            colors = { "white" },
            saints = {
                "cyril-constantine-the-philosopher-monk",
                "methodius-michael-of-thessaloniki-bishop",
            },
        },
        {
            id = "matthias-apostle",
            date = "02-24",
            rank = "memorial",
            precedence = 11,
            colors = { "red" },
            saints = { "matthias-apostle" },
        },
        {
            id = "walpurga-of-heidenheim-abbess",
            date = "02-25",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "fridolin-of-sackingen-monk",
            date = "03-06",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "bruno-of-querfurt-bishop",
            date = "03-09",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "martyrs" },
        },
        {
            id = "matilda-of-ringelheim",
            date = "03-14",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "clement-mary-hofbauer-priest",
            date = "03-15",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "gertrude-of-nivelles-abbess",
            date = "03-17",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "ludger-of-munster-bishop",
            date = "03-26",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "leo-ix-pope",
            date = "04-19",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "marcel-callo-martyr",
            date = "04-19",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "conrad-of-parzham-religious",
            date = "04-21",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "peter-canisius-priest",
            date = "04-27",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "pastors", "doctors_of_the_church" },
            saints = { "peter-canisius-priest" },
        },
        {
            id = "catherine-of-siena-virgin",
            date = "04-29",
            title = "catherine-of-siena-virgin-copatroness-of-europe",
            rank = "feast",
            precedence = 8,
            colors = { "white" },
            saints = { "catherine-of-siena-virgin" },
        },
        {
            id = "florian-of-lorch-and-companions-martyrs",
            date = "05-04",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            saints = { "florian-of-lorch-martyr", "companions-martyrs" },
        },
        {
            id = "gotthard-of-hildesheim-bishop",
            date = "05-05",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "john-nepomucene-priest",
            date = "05-16",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "martyrs" },
        },
        {
            id = "hermann-joseph-of-steinfeld-priest",
            date = "05-21",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "vitus-of-lucania-martyr",
            date = "06-15",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "benno-of-meissen-bishop",
            date = "06-16",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "hemma-of-gurk",
            date = "06-27",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "otto-of-bamberg-bishop",
            date = "06-30",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "visitation-of-mary",
            date = "07-02",
            rank = "feast",
            precedence = 8,
            colors = { "white" },
        },
        {
            id = "ulrich-of-augsburg-bishop",
            date = "07-04",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "willibald-of-eichstatt-bishop",
            date = "07-07",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "kilian-of-wurzburg-bishop-and-companions-martyrs",
            date = "07-08",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            saints = { "kilian-of-wurzburg-bishop", "companions-martyrs" },
        },
        {
            id = "canute-iv-of-denmark-eric-ix-of-sweden-and-olaf-ii-of-norway-martyrs",
            date = "07-10",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            saints = {
                "canute-iv-of-denmark-martyr",
                "eric-ix-of-sweden-martyr",
                "olaf-ii-of-norway-martyr",
            },
        },
        {
            id = "benedict-of-nursia-abbot",
            date = "07-11",
            title = "benedict-of-nursia-abbot-patron-of-europe",
            rank = "feast",
            precedence = 8,
            colors = { "white" },
            saints = { "benedict-of-nursia-abbot" },
        },
        {
            id = "henry-ii-emperor-and-cunigunde-of-luxembourg",
            date = "07-13",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            saints = { "henry-ii-emperor", "cunigunde-of-luxembourg" },
        },
        {
            id = "margaret-of-antioch-virgin",
            date = "07-20",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "bridget-of-sweden-religious",
            date = "07-23",
            title = "bridget-of-sweden-religious-copatroness-of-europe",
            rank = "feast",
            precedence = 8,
            colors = { "white" },
            commons = { "holy_women", "religious" },
            saints = { "bridget-of-sweden-religious" },
        },
        {
            id = "christopher-of-palestine-martyr",
            date = "07-24",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "teresa-benedicta-of-the-cross-stein-virgin",
            date = "08-09",
            title = "teresa-benedicta-of-the-cross-stein-virgin-copatroness-of-europe",
            rank = "feast",
            precedence = 8,
            colors = { "red" },
            commons = { "martyrs", "virgins" },
            saints = { "teresa-benedicta-of-the-cross-stein-virgin" },
        },
        {
            id = "paulinus-of-trier-bishop",
            date = "08-31",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "lambert-of-maastricht-bishop",
            date = "09-18",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "maurice-of-agaunum-and-companions-martyrs",
            date = "09-22",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            saints = { "maurice-of-agaunum-martyr", "companions-martyrs" },
        },
        {
            id = "rupert-of-salzburg-and-virgilius-of-salzburg-bishops",
            date = "09-24",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            saints = { "rupert-of-salzburg-bishop", "virgilius-of-salzburg-bishop" },
        },
        {
            id = "nicholas-of-flue-hermit",
            date = "09-25",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "leoba-of-tauberbischofsheim-abbess",
            date = "09-28",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "gall-of-switzerland-abbot",
            date = "10-16",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "wendelin-of-trier-hermit",
            date = "10-20",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "ursula-of-cologne-and-companions-virgins",
            date = "10-21",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            saints = { "ursula-of-cologne-virgin", "companions-martyrs" },
        },
        {
            id = "wolfgang-of-regensburg-bishop",
            date = "10-31",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "hubert-of-liege-bishop",
            date = "11-03",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "pirmin-of-hornbach-abbot",
            date = "11-03",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "leonard-of-noblac-hermit",
            date = "11-06",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "willibrord-of-utrecht-bishop",
            date = "11-07",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "leopold-iii-of-babenberg",
            date = "11-15",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "gertrude-the-great-virgin",
            date = "11-17",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "virgins", "nuns" },
            saints = { "gertrude-the-great-virgin" },
        },
        {
            id = "elizabeth-of-hungary-religious",
            date = "11-19",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "mercy_workers" },
            saints = { "elizabeth-of-hungary-religious" },
        },
        {
            id = "corbinian-of-freising-bishop",
            date = "11-20",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "conrad-of-constance-and-gebhard-of-constance-bishops",
            date = "11-26",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            saints = { "conrad-of-constance-bishop", "gebhard-of-constance-bishop" },
        },
        {
            id = "lucius-of-chur-bishop",
            date = "12-02",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "adolph-kolping-priest",
            date = "12-04",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "barbara-of-heliopolis-virgin",
            date = "12-04",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "anno-of-cologne-bishop",
            date = "12-05",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "odile-of-alsace-abbess",
            date = "12-13",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "stephen-the-first-martyr",
            date = "12-26",
            rank = "feast",
            precedence = 7,
            colors = { "red" },
            obligation = true,
            saints = { "stephen-the-first-martyr" },
        },
        {
            id = "mary-mother-of-the-church",
            date = { fn = "mary_mother_of_the_church" },
            rank = "memorial",
            precedence = 10,
            colors = { "white" },
            commons = { "blessed_virgin_mary" },
            obligation = true,
        },
    },
    obligations = { "easter-1-monday" },
    transfers = {},
}
