-- Calendar of ES: changes to the General Roman Calendar.
-- Origin: romcal @ 30344b3 (MIT), normalized in parked/epub/data/calendars/es-overlay.json;
-- transfers also from parked/epub/data/calendars/transfer-decisions.json.
-- transfers: solemnities moved to Sunday (epiphany, ascension, corpus_christi).
-- celebrations: added, or replacing the general celebration with the same id; title: the
-- calendar's own title for it (tag celebration.<title>), e.g. "..., Patron of Europe".
return {
    celebrations = {
        {
            id = "eulogius-of-cordoba-bishop",
            date = "01-09",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "fructuosus-of-tarragona-bishop-and-augurius-of-tarragona-and-eulogius-of-tarragona-deacons-martyrs",
            date = "01-20",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            saints = {
                "fructuosus-of-tarragona-bishop",
                "augurius-of-tarragona-deacon",
                "eulogius-of-tarragona-deacon",
            },
        },
        {
            id = "vincent-of-saragossa-deacon",
            date = "01-22",
            rank = "memorial",
            precedence = 11,
            colors = { "red" },
            commons = { "martyrs" },
            saints = { "vincent-of-saragossa-deacon" },
        },
        {
            id = "ildephonsus-of-toledo-bishop",
            date = "01-23",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "cyril-constantine-the-philosopher-monk-and-methodius-michael-of-thessaloniki-bishop",
            date = "02-14",
            title = "cyril-constantine-the-philosopher-monk-and-methodius-michael-of-thessaloniki-bishop-copatrons-of-europe",
            rank = "feast",
            precedence = 8,
            colors = { "white" },
            saints = {
                "cyril-constantine-the-philosopher-monk",
                "methodius-michael-of-thessaloniki-bishop",
            },
        },
        {
            id = "hermenegild-the-visigoths-martyr",
            date = "04-13",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "isidore-of-seville-bishop",
            date = "04-26",
            rank = "feast",
            precedence = 8,
            colors = { "white" },
            commons = { "bishops", "doctors_of_the_church" },
            saints = { "isidore-of-seville-bishop" },
        },
        {
            id = "catherine-of-siena-virgin",
            date = "04-29",
            title = "catherine-of-siena-virgin-copatroness-of-europe",
            rank = "feast",
            precedence = 8,
            colors = { "white" },
            saints = { "catherine-of-siena-virgin" },
        },
        {
            id = "john-of-avila-priest",
            date = "05-10",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "pastors", "doctors_of_the_church" },
            saints = { "john-of-avila-priest" },
        },
        {
            id = "isidore-the-farmer",
            date = "05-15",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "saints" },
        },
        {
            id = "paschal-baylon-religious",
            date = "05-17",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "joaquina-of-saint-francis-of-assisi-de-vedruna-religious",
            date = "05-22",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "ferdinand-iii-of-castile",
            date = "05-30",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "maria-micaela-of-the-blessed-sacrament-desmaisieres-virgin",
            date = "06-15",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "pelagius-of-cordoba-martyr",
            date = "06-26",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "benedict-of-nursia-abbot",
            date = "07-11",
            title = "benedict-of-nursia-abbot-patron-of-europe",
            rank = "feast",
            precedence = 8,
            colors = { "white" },
            saints = { "benedict-of-nursia-abbot" },
        },
        {
            id = "our-lady-of-mount-carmel",
            date = "07-16",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "blessed_virgin_mary" },
        },
        {
            id = "bridget-of-sweden-religious",
            date = "07-23",
            title = "bridget-of-sweden-religious-copatroness-of-europe",
            rank = "feast",
            precedence = 8,
            colors = { "white" },
            commons = { "holy_women", "religious" },
            saints = { "bridget-of-sweden-religious" },
        },
        {
            id = "james-apostle",
            date = "07-25",
            title = "james-apostle-patron-of-spain",
            rank = "solemnity",
            precedence = 4,
            colors = { "red" },
            saints = { "james-apostle" },
        },
        {
            id = "teresa-benedicta-of-the-cross-stein-virgin",
            date = "08-09",
            title = "teresa-benedicta-of-the-cross-stein-virgin-copatroness-of-europe",
            rank = "feast",
            precedence = 8,
            colors = { "red" },
            commons = { "martyrs", "virgins" },
            saints = { "teresa-benedicta-of-the-cross-stein-virgin" },
        },
        {
            id = "ezequiel-moreno-bishop",
            date = "08-19",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "bishops" },
        },
        {
            id = "teresa-of-jesus-jornet-ibars-virgin",
            date = "08-26",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "virgins" },
        },
        {
            id = "francis-borgia-priest",
            date = "10-03",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "thomas-of-villanova-bishop",
            date = "10-10",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "mary-soledad-torres-acosta-virgin",
            date = "10-11",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "our-lady-of-the-pillar",
            date = "10-12",
            rank = "feast",
            precedence = 8,
            colors = { "white" },
            commons = { "blessed_virgin_mary" },
        },
        {
            id = "teresa-of-jesus-of-avila-virgin",
            date = "10-15",
            rank = "feast",
            precedence = 8,
            colors = { "white" },
            commons = { "virgins", "doctors_of_the_church" },
            saints = { "teresa-of-jesus-of-avila-virgin" },
        },
        {
            id = "peter-of-alcantara-priest",
            date = "10-19",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "peter-poveda-and-innocent-of-mary-immaculate-canoura-priests-and-companions-martyrs",
            date = "11-06",
            rank = "memorial",
            precedence = 10,
            colors = { "white" },
            commons = { "martyrs" },
            plural = true,
        },
        {
            id = "leander-of-seville-bishop",
            date = "11-13",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "eulalia-of-merida-virgin",
            date = "12-10",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "john-of-the-cross-priest",
            date = "12-14",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            saints = { "john-of-the-cross-priest" },
        },
        {
            id = "our-lord-jesus-christ-the-eternal-high-priest",
            date = { fn = "pentecost_sunday", offset = 4 },
            rank = "feast",
            precedence = 8,
            colors = { "white" },
            office = "weekday",
        },
    },
    transfers = {},
}
