-- Calendar of FR: changes to the General Roman Calendar.
-- Origin: romcal @ 30344b3 (MIT), normalized in parked/epub/data/calendars/fr-overlay.json;
-- transfers also from parked/epub/data/calendars/transfer-decisions.json.
-- transfers: solemnities moved to Sunday (epiphany, ascension, corpus_christi).
-- celebrations: added, or replacing the general celebration with the same id; title: the
-- calendar's own title for it (tag celebration.<title>), e.g. "..., Patron of Europe".
return {
    celebrations = {
        {
            id = "genevieve-of-paris-virgin",
            date = "01-03",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "virgins", "mercy_workers" },
        },
        {
            id = "remigius-of-reims-bishop",
            date = "01-15",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "bishops" },
        },
        {
            id = "our-lady-of-lourdes",
            date = "02-11",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "blessed_virgin_mary" },
        },
        {
            id = "cyril-constantine-the-philosopher-monk-and-methodius-michael-of-thessaloniki-bishop",
            date = "02-14",
            title = "cyril-constantine-the-philosopher-monk-and-methodius-michael-of-thessaloniki-bishop-copatrons-of-europe",
            rank = "feast",
            precedence = 8,
            colors = { "white" },
            saints = {
                "cyril-constantine-the-philosopher-monk",
                "methodius-michael-of-thessaloniki-bishop",
            },
        },
        {
            id = "bernadette-soubirous-virgin",
            date = "02-18",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "virgins", "religious" },
        },
        {
            id = "catherine-of-siena-virgin",
            date = "04-29",
            title = "catherine-of-siena-virgin-copatroness-of-europe",
            rank = "feast",
            precedence = 8,
            colors = { "white" },
            saints = { "catherine-of-siena-virgin" },
        },
        {
            id = "louise-de-marillac-religious",
            date = "05-09",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "holy_women" },
        },
        {
            id = "ivo-of-kermartin-priest",
            date = "05-19",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "mercy_workers", "pastors" },
        },
        {
            id = "joan-of-arc-virgin",
            date = "05-30",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "virgins" },
        },
        {
            id = "pothinus-of-lyon-bishop-blandina-of-lyon-virgin-and-companions-martyrs",
            date = "06-02",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "martyrs" },
            plural = true,
            saints = { "pothinus-of-lyon-bishop", "blandina-of-lyon-virgin", "companions-martyrs" },
        },
        {
            id = "clotilde-of-burgundy",
            date = "06-04",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "holy_women" },
        },
        {
            id = "benedict-of-nursia-abbot",
            date = "07-11",
            title = "benedict-of-nursia-abbot-patron-of-europe",
            rank = "feast",
            precedence = 8,
            colors = { "white" },
            saints = { "benedict-of-nursia-abbot" },
        },
        {
            id = "bridget-of-sweden-religious",
            date = "07-23",
            title = "bridget-of-sweden-religious-copatroness-of-europe",
            rank = "feast",
            precedence = 8,
            colors = { "white" },
            commons = { "holy_women", "religious" },
            saints = { "bridget-of-sweden-religious" },
        },
        {
            id = "john-mary-vianney-priest",
            date = "08-04",
            rank = "memorial",
            precedence = 10,
            colors = { "white" },
            commons = { "pastors" },
            saints = { "john-mary-vianney-priest" },
        },
        {
            id = "teresa-benedicta-of-the-cross-stein-virgin",
            date = "08-09",
            title = "teresa-benedicta-of-the-cross-stein-virgin-copatroness-of-europe",
            rank = "feast",
            precedence = 8,
            colors = { "red" },
            commons = { "martyrs", "virgins" },
            saints = { "teresa-benedicta-of-the-cross-stein-virgin" },
        },
        {
            id = "louis-ix-of-france",
            date = "08-25",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "saints" },
            saints = { "louis-ix-of-france" },
        },
        {
            id = "caesarius-of-arles-bishop",
            date = "08-26",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "bishops" },
        },
        {
            id = "joseph-of-calasanz-priest",
            date = "08-26",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "educators", "pastors" },
            saints = { "joseph-of-calasanz-priest" },
        },
        {
            id = "our-lady-of-la-salette",
            date = "09-19",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "blessed_virgin_mary" },
        },
        {
            id = "therese-of-the-child-jesus-and-the-holy-face-of-lisieux-virgin",
            date = "10-01",
            title = "therese-of-the-child-jesus-and-the-holy-face-of-lisieux-virgin-copatroness-of-france",
            rank = "memorial",
            precedence = 10,
            colors = { "white" },
            saints = { "therese-of-the-child-jesus-and-the-holy-face-of-lisieux-virgin" },
        },
        {
            id = "dedication-of-consecrated-churches",
            date = "10-25",
            rank = "solemnity",
            precedence = 4,
            colors = { "white" },
            commons = { "dedication_anniversary__inside" },
            omissible = true,
        },
        {
            id = "assumption-of-the-blessed-virgin-mary",
            date = { fn = "assumption" },
            title = "assumption-of-the-blessed-virgin-mary-patroness-of-france",
            rank = "solemnity",
            precedence = 2,
            colors = { "white" },
            obligation = true,
        },
    },
    transfers = { corpus_christi = true, epiphany = true },
}
