-- Calendar of GB-SC: changes to the General Roman Calendar.
-- Origin: romcal @ 30344b3 (MIT), normalized in parked/epub/data/calendars/gb-sc-overlay.json;
-- transfers also from parked/epub/data/calendars/transfer-decisions.json.
-- transfers: solemnities moved to Sunday (epiphany, ascension, corpus_christi).
-- celebrations: added, or replacing the general celebration with the same id; title: the
-- calendar's own title for it (tag celebration.<title>), e.g. "..., Patron of Europe".
return {
    celebrations = {
        {
            id = "kentigern-of-scotland-bishop",
            date = "01-13",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "bishops" },
        },
        {
            id = "cyril-constantine-the-philosopher-monk-and-methodius-michael-of-thessaloniki-bishop",
            date = "02-14",
            title = "cyril-constantine-the-philosopher-monk-and-methodius-michael-of-thessaloniki-bishop-copatrons-of-europe",
            rank = "feast",
            precedence = 8,
            colors = { "white" },
            saints = {
                "cyril-constantine-the-philosopher-monk",
                "methodius-michael-of-thessaloniki-bishop",
            },
        },
        {
            id = "john-ogilvie-priest",
            date = "03-10",
            rank = "feast",
            precedence = 8,
            colors = { "white" },
            commons = { "martyrs" },
        },
        {
            id = "patrick-of-ireland-bishop",
            date = "03-17",
            rank = "feast",
            precedence = 8,
            colors = { "white" },
            commons = { "missionaries", "bishops" },
            saints = { "patrick-of-ireland-bishop" },
        },
        {
            id = "catherine-of-siena-virgin",
            date = "04-29",
            title = "catherine-of-siena-virgin-copatroness-of-europe",
            rank = "feast",
            precedence = 8,
            colors = { "white" },
            saints = { "catherine-of-siena-virgin" },
        },
        {
            id = "columba-of-iona-abbot",
            date = "06-09",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "abbots" },
        },
        {
            id = "benedict-of-nursia-abbot",
            date = "07-11",
            title = "benedict-of-nursia-abbot-patron-of-europe",
            rank = "feast",
            precedence = 8,
            colors = { "white" },
            saints = { "benedict-of-nursia-abbot" },
        },
        {
            id = "bridget-of-sweden-religious",
            date = "07-23",
            title = "bridget-of-sweden-religious-copatroness-of-europe",
            rank = "feast",
            precedence = 8,
            colors = { "white" },
            commons = { "holy_women", "religious" },
            saints = { "bridget-of-sweden-religious" },
        },
        {
            id = "teresa-benedicta-of-the-cross-stein-virgin",
            date = "08-09",
            title = "teresa-benedicta-of-the-cross-stein-virgin-copatroness-of-europe",
            rank = "feast",
            precedence = 8,
            colors = { "red" },
            commons = { "martyrs", "virgins" },
            saints = { "teresa-benedicta-of-the-cross-stein-virgin" },
        },
        {
            id = "ninian-of-whithorn-bishop",
            date = "09-16",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
        },
        {
            id = "margaret-of-scotland",
            date = "11-16",
            rank = "feast",
            precedence = 8,
            colors = { "white" },
            commons = { "mercy_workers" },
            saints = { "margaret-of-scotland" },
        },
        {
            id = "andrew-apostle",
            date = "11-30",
            title = "andrew-apostle-patron-of-scotland",
            rank = "solemnity",
            precedence = 4,
            colors = { "red" },
            saints = { "andrew-apostle" },
        },
    },
    transfers = {},
}
