-- General Roman Calendar (Missal of Paul VI): the sanctoral cycle.
-- Origin: romcal @ 30344b3 (MIT), normalized in parked/epub/data/calendars/general-roman-sanctoral.json.
-- Each celebration: id (its title is the tag celebration.<id>), date ("MM-DD" or a rule),
-- rank, precedence (Table of Liturgical Days, 1-13), colours, commons, saints,
-- obligation, similar (may share its day with others of equal rank), plural (several
-- martyrs), omissible (romcal: may be left out locally), office ("weekday": the
-- Office of Readings keeps the weekday's reading; an id: that celebration's), readings
-- (the same for the Mass readings), exceptions.
-- See litcomp/roman1970/sanctoral.lua for the date rules.
return {
    celebrations = {
        {
            id = "basil-the-great-and-gregory-nazianzen-bishops",
            date = "01-02",
            rank = "memorial",
            precedence = 10,
            colors = { "white" },
            saints = { "basil-the-great-bishop", "gregory-nazianzen-bishop" },
        },
        {
            id = "most-holy-name-of-jesus",
            date = "01-03",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "raymond-of-penyafort-priest",
            date = "01-07",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "pastors" },
            saints = { "raymond-of-penyafort-priest" },
        },
        {
            id = "hilary-of-poitiers-bishop",
            date = "01-13",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "bishops", "doctors_of_the_church" },
            saints = { "hilary-of-poitiers-bishop" },
        },
        {
            id = "anthony-of-egypt-abbot",
            date = "01-17",
            rank = "memorial",
            precedence = 10,
            colors = { "white" },
            saints = { "anthony-of-egypt-abbot" },
        },
        {
            id = "fabian-i-pope",
            date = "01-20",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "red" },
            commons = { "martyrs", "pope_or_bishop" },
            saints = { "fabian-i-pope" },
        },
        {
            id = "sebastian-of-milan-martyr",
            date = "01-20",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "red" },
            commons = { "martyrs" },
            saints = { "sebastian-of-milan-martyr" },
        },
        {
            id = "agnes-of-rome-virgin",
            date = "01-21",
            rank = "memorial",
            precedence = 10,
            colors = { "red" },
            commons = { "virgin_martyrs", "virgins" },
            saints = { "agnes-of-rome-virgin" },
        },
        {
            id = "vincent-of-saragossa-deacon",
            date = "01-22",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "red" },
            commons = { "martyrs" },
            saints = { "vincent-of-saragossa-deacon" },
        },
        {
            id = "francis-de-sales-bishop",
            date = "01-24",
            rank = "memorial",
            precedence = 10,
            colors = { "white" },
            commons = { "bishops", "doctors_of_the_church" },
            saints = { "francis-de-sales-bishop" },
        },
        {
            id = "conversion-of-saint-paul-the-apostle",
            date = "01-25",
            rank = "feast",
            precedence = 7,
            colors = { "white" },
        },
        {
            id = "timothy-of-ephesus-and-titus-of-crete-bishops",
            date = "01-26",
            rank = "memorial",
            precedence = 10,
            colors = { "white" },
            saints = { "timothy-of-ephesus-bishop", "titus-of-crete-bishop" },
        },
        {
            id = "angela-merici-virgin",
            date = "01-27",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "virgins", "educators" },
            saints = { "angela-merici-virgin" },
        },
        {
            id = "thomas-aquinas-priest",
            date = "01-28",
            rank = "memorial",
            precedence = 10,
            colors = { "white" },
            commons = { "doctors_of_the_church", "pastors" },
            saints = { "thomas-aquinas-priest" },
        },
        {
            id = "john-bosco-priest",
            date = "01-31",
            rank = "memorial",
            precedence = 10,
            colors = { "white" },
            commons = { "pastors", "educators" },
            saints = { "john-bosco-priest" },
        },
        {
            id = "ansgar-of-hamburg-bishop",
            date = "02-03",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "missionaries", "bishops" },
            saints = { "ansgar-of-hamburg-bishop" },
        },
        {
            id = "blaise-of-sebaste-bishop",
            date = "02-03",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "red" },
            commons = { "martyrs", "bishops" },
            saints = { "blaise-of-sebaste-bishop" },
        },
        {
            id = "agatha-of-sicily-virgin",
            date = "02-05",
            rank = "memorial",
            precedence = 10,
            colors = { "red" },
            commons = { "virgin_martyrs", "virgins" },
            saints = { "agatha-of-sicily-virgin" },
        },
        {
            id = "paul-miki-and-companions-martyrs",
            date = "02-06",
            rank = "memorial",
            precedence = 10,
            colors = { "red" },
            commons = { "martyrs" },
            plural = true,
            saints = { "paul-miki-martyr", "companions-of-paul-miki-martyr" },
        },
        {
            id = "jerome-emiliani",
            date = "02-08",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "educators" },
            saints = { "jerome-emiliani" },
        },
        {
            id = "josephine-bakhita-virgin",
            date = "02-08",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "virgins" },
            saints = { "josephine-bakhita-virgin" },
        },
        {
            id = "scholastica-of-nursia-virgin",
            date = "02-10",
            rank = "memorial",
            precedence = 10,
            colors = { "white" },
            commons = { "virgins", "nuns" },
            saints = { "scholastica-of-nursia-virgin" },
        },
        {
            id = "our-lady-of-lourdes",
            date = "02-11",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "blessed_virgin_mary" },
        },
        {
            id = "cyril-constantine-the-philosopher-monk-and-methodius-michael-of-thessaloniki-bishop",
            date = "02-14",
            rank = "memorial",
            precedence = 10,
            colors = { "white" },
            saints = {
                "cyril-constantine-the-philosopher-monk",
                "methodius-michael-of-thessaloniki-bishop",
            },
        },
        {
            id = "seven-holy-founders-of-the-servite-order",
            date = "02-17",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "religious" },
        },
        {
            id = "peter-damian-bishop",
            date = "02-21",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "doctors_of_the_church", "bishops" },
            saints = { "peter-damian-bishop" },
        },
        {
            id = "chair-of-saint-peter-the-apostle",
            date = "02-22",
            rank = "feast",
            precedence = 7,
            colors = { "white" },
        },
        {
            id = "polycarp-of-smyrna-bishop",
            date = "02-23",
            rank = "memorial",
            precedence = 10,
            colors = { "red" },
            commons = { "martyrs", "bishops" },
            saints = { "polycarp-of-smyrna-bishop" },
        },
        {
            id = "gregory-of-narek-abbot",
            date = "02-27",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "doctors_of_the_church", "abbots" },
            saints = { "gregory-of-narek-abbot" },
        },
        {
            id = "casimir-of-poland",
            date = "03-04",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "saints" },
            saints = { "casimir-of-poland" },
        },
        {
            id = "perpetua-of-carthage-and-felicity-of-carthage-martyrs",
            date = "03-07",
            rank = "memorial",
            precedence = 10,
            colors = { "red" },
            saints = { "perpetua-of-carthage-martyr", "felicity-of-carthage-martyr" },
        },
        {
            id = "john-of-god-duarte-cidade-religious",
            date = "03-08",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "religious", "mercy_workers" },
            saints = { "john-of-god-duarte-cidade-religious" },
        },
        {
            id = "frances-of-rome-religious",
            date = "03-09",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "holy_women", "religious" },
            saints = { "frances-of-rome-religious" },
        },
        {
            id = "patrick-of-ireland-bishop",
            date = "03-17",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "missionaries", "bishops" },
            saints = { "patrick-of-ireland-bishop" },
        },
        {
            id = "cyril-of-jerusalem-bishop",
            date = "03-18",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "bishops", "doctors_of_the_church" },
            saints = { "cyril-of-jerusalem-bishop" },
        },
        {
            id = "joseph-spouse-of-mary",
            date = "03-19",
            rank = "solemnity",
            precedence = 3,
            colors = { "white" },
            exceptions = {
                { move = { offset = 1 }, when = { weekday = "sunday" } },
                {
                    move = { fn = "palm_sunday", offset = -1 },
                    when = { between = { "palm_sunday", "divine_mercy_sunday" }, inclusive = true },
                },
            },
            obligation = true,
            saints = { "joseph-spouse-of-mary" },
        },
        {
            id = "turibius-of-mogrovejo-bishop",
            date = "03-23",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "bishops" },
            saints = { "turibius-of-mogrovejo-bishop" },
        },
        {
            id = "francis-of-paola-hermit",
            date = "04-02",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "religious" },
            saints = { "francis-of-paola-hermit" },
        },
        {
            id = "isidore-of-seville-bishop",
            date = "04-04",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "bishops", "doctors_of_the_church" },
            saints = { "isidore-of-seville-bishop" },
        },
        {
            id = "vincent-ferrer-priest",
            date = "04-05",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "missionaries" },
            saints = { "vincent-ferrer-priest" },
        },
        {
            id = "john-baptist-de-la-salle-priest",
            date = "04-07",
            rank = "memorial",
            precedence = 10,
            colors = { "white" },
            commons = { "pastors", "educators" },
            saints = { "john-baptist-de-la-salle-priest" },
        },
        {
            id = "stanislaus-of-szczepanow-bishop",
            date = "04-11",
            rank = "memorial",
            precedence = 10,
            colors = { "red" },
            commons = { "martyrs", "bishops" },
            saints = { "stanislaus-of-szczepanow-bishop" },
        },
        {
            id = "martin-i-pope",
            date = "04-13",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "red" },
            commons = { "martyrs", "pope_or_bishop" },
            saints = { "martin-i-pope" },
        },
        {
            id = "anselm-of-canterbury-bishop",
            date = "04-21",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "bishops", "doctors_of_the_church" },
            saints = { "anselm-of-canterbury-bishop" },
        },
        {
            id = "adalbert-of-prague-bishop",
            date = "04-23",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "red" },
            commons = { "martyrs", "bishops" },
            saints = { "adalbert-of-prague-bishop" },
        },
        {
            id = "george-of-lydda-martyr",
            date = "04-23",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "red" },
            commons = { "martyrs" },
            saints = { "george-of-lydda-martyr" },
        },
        {
            id = "fidelis-of-sigmaringen-priest",
            date = "04-24",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "red" },
            commons = { "martyrs", "pastors" },
            saints = { "fidelis-of-sigmaringen-priest" },
        },
        {
            id = "mark-evangelist",
            date = "04-25",
            rank = "feast",
            precedence = 7,
            colors = { "red" },
            saints = { "mark-evangelist" },
        },
        {
            id = "louis-grignion-de-montfort-priest",
            date = "04-28",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "pastors" },
            saints = { "louis-grignion-de-montfort-priest" },
        },
        {
            id = "peter-chanel-priest",
            date = "04-28",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "red" },
            commons = { "martyrs", "missionaries" },
            saints = { "peter-chanel-priest" },
        },
        {
            id = "catherine-of-siena-virgin",
            date = "04-29",
            rank = "memorial",
            precedence = 10,
            colors = { "white" },
            saints = { "catherine-of-siena-virgin" },
        },
        {
            id = "pius-v-pope",
            date = "04-30",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "pope_or_bishop" },
            saints = { "pius-v-pope" },
        },
        {
            id = "joseph-the-worker",
            date = "05-01",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            saints = { "joseph-spouse-of-mary" },
        },
        {
            id = "athanasius-of-alexandria-bishop",
            date = "05-02",
            rank = "memorial",
            precedence = 10,
            colors = { "white" },
            saints = { "athanasius-of-alexandria-bishop" },
        },
        {
            id = "philip-and-james-apostles",
            date = "05-03",
            rank = "feast",
            precedence = 7,
            colors = { "red" },
            saints = { "philip-apostle", "james-apostle" },
        },
        {
            id = "john-of-avila-priest",
            date = "05-10",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "pastors", "doctors_of_the_church" },
            saints = { "john-of-avila-priest" },
        },
        {
            id = "nereus-of-terracina-and-achilleus-of-terracina-martyrs",
            date = "05-12",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "red" },
            commons = { "martyrs" },
            plural = true,
            saints = { "nereus-of-terracina-martyr", "achilleus-of-terracina-martyr" },
        },
        {
            id = "pancras-of-rome-martyr",
            date = "05-12",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "red" },
            commons = { "martyrs" },
            saints = { "pancras-of-rome-martyr" },
        },
        {
            id = "our-lady-of-fatima",
            date = "05-13",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "blessed_virgin_mary" },
        },
        {
            id = "matthias-apostle",
            date = "05-14",
            rank = "feast",
            precedence = 7,
            colors = { "red" },
            saints = { "matthias-apostle" },
        },
        {
            id = "john-i-pope",
            date = "05-18",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "red" },
            commons = { "martyrs", "pope_or_bishop" },
            saints = { "john-i-pope" },
        },
        {
            id = "bernardine-of-siena-priest",
            date = "05-20",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "missionaries", "religious" },
            saints = { "bernardine-of-siena-priest" },
        },
        {
            id = "christopher-magallanes-priest-and-companions-martyrs",
            date = "05-21",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "red" },
            commons = { "martyrs" },
            plural = true,
            saints = {
                "christopher-magallanes-priest",
                "companions-of-christopher-magallanes-priest",
            },
        },
        {
            id = "rita-of-cascia-religious",
            date = "05-22",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "religious" },
            saints = { "rita-of-cascia-religious" },
        },
        {
            id = "bede-the-venerable-priest",
            date = "05-25",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "doctors_of_the_church", "monks" },
            saints = { "bede-the-venerable-priest" },
        },
        {
            id = "gregory-vii-pope",
            date = "05-25",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "pope_or_bishop" },
            saints = { "gregory-vii-pope" },
        },
        {
            id = "mary-magdalene-de-pazzi-virgin",
            date = "05-25",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "virgins", "religious" },
            saints = { "mary-magdalene-de-pazzi-virgin" },
        },
        {
            id = "philip-neri-priest",
            date = "05-26",
            rank = "memorial",
            precedence = 10,
            colors = { "white" },
            saints = { "philip-neri-priest" },
        },
        {
            id = "augustine-of-canterbury-bishop",
            date = "05-27",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "missionaries", "bishops" },
            saints = { "augustine-of-canterbury-bishop" },
        },
        {
            id = "paul-vi-pope",
            date = "05-29",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "pope_or_bishop" },
            saints = { "paul-vi-pope" },
        },
        {
            id = "visitation-of-mary",
            date = "05-31",
            rank = "feast",
            precedence = 7,
            colors = { "white" },
        },
        {
            id = "justin-martyr",
            date = "06-01",
            rank = "memorial",
            precedence = 10,
            colors = { "red" },
            saints = { "justin-martyr" },
        },
        {
            id = "marcellinus-of-rome-and-peter-the-exorcist-martyrs",
            date = "06-02",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "red" },
            commons = { "martyrs" },
            plural = true,
            saints = { "marcellinus-of-rome-martyr", "peter-the-exorcist-martyr" },
        },
        {
            id = "charles-lwanga-and-companions-martyrs",
            date = "06-03",
            rank = "memorial",
            precedence = 10,
            colors = { "red" },
            saints = { "charles-lwanga-martyr", "companions-of-charles-lwanga-martyr" },
        },
        {
            id = "boniface-of-mainz-bishop",
            date = "06-05",
            rank = "memorial",
            precedence = 10,
            colors = { "red" },
            commons = { "martyrs", "missionaries" },
            saints = { "boniface-of-mainz-bishop" },
        },
        {
            id = "norbert-of-xanten-bishop",
            date = "06-06",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "bishops", "religious" },
            saints = { "norbert-of-xanten-bishop" },
        },
        {
            id = "ephrem-the-syrian-deacon",
            date = "06-09",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "doctors_of_the_church" },
            saints = { "ephrem-the-syrian-deacon" },
        },
        {
            id = "barnabas-apostle",
            date = "06-11",
            rank = "memorial",
            precedence = 10,
            colors = { "red" },
            saints = { "barnabas-apostle" },
        },
        {
            id = "anthony-of-padua-priest",
            date = "06-13",
            rank = "memorial",
            precedence = 10,
            colors = { "white" },
            commons = { "pastors", "doctors_of_the_church", "religious" },
            saints = { "anthony-of-padua-priest" },
        },
        {
            id = "romuald-of-ravenna-abbot",
            date = "06-19",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "abbots" },
            saints = { "romuald-of-ravenna-abbot" },
        },
        {
            id = "aloysius-gonzaga-religious",
            date = "06-21",
            rank = "memorial",
            precedence = 10,
            colors = { "white" },
            saints = { "aloysius-gonzaga-religious" },
        },
        {
            id = "john-fisher-bishop-and-thomas-more-martyrs",
            date = "06-22",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "red" },
            commons = { "martyrs" },
            plural = true,
            saints = { "john-fisher-bishop", "thomas-more-martyr" },
        },
        {
            id = "paulinus-of-nola-bishop",
            date = "06-22",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "bishops" },
            saints = { "paulinus-of-nola-bishop" },
        },
        {
            id = "cyril-of-alexandria-bishop",
            date = "06-27",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "bishops", "doctors_of_the_church" },
            saints = { "cyril-of-alexandria-bishop" },
        },
        {
            id = "irenaeus-of-lyon-bishop",
            date = "06-28",
            rank = "memorial",
            precedence = 10,
            colors = { "red" },
            saints = { "irenaeus-of-lyon-bishop" },
        },
        {
            id = "first-martyrs-of-the-holy-roman-church",
            date = "06-30",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "red" },
            commons = { "martyrs" },
        },
        {
            id = "thomas-apostle",
            date = "07-03",
            rank = "feast",
            precedence = 7,
            colors = { "red" },
            saints = { "thomas-apostle" },
        },
        {
            id = "elizabeth-of-portugal",
            date = "07-04",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "mercy_workers" },
            saints = { "elizabeth-of-portugal" },
        },
        {
            id = "anthony-zaccaria-priest",
            date = "07-05",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "pastors", "educators", "religious" },
            saints = { "anthony-zaccaria-priest" },
        },
        {
            id = "maria-goretti-virgin",
            date = "07-06",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "red" },
            commons = { "virgin_martyrs", "virgins" },
            saints = { "maria-goretti-virgin" },
        },
        {
            id = "augustine-zhao-rong-priest-and-companions-martyrs",
            date = "07-09",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "red" },
            commons = { "martyrs" },
            plural = true,
            saints = { "augustine-zhao-rong-priest", "companions-of-augustine-zhao-rong-priest" },
        },
        {
            id = "benedict-of-nursia-abbot",
            date = "07-11",
            rank = "memorial",
            precedence = 10,
            colors = { "white" },
            saints = { "benedict-of-nursia-abbot" },
        },
        {
            id = "henry-ii-emperor",
            date = "07-13",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "saints" },
            saints = { "henry-ii-emperor" },
        },
        {
            id = "camillus-de-lellis-priest",
            date = "07-14",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "mercy_workers" },
            saints = { "camillus-de-lellis-priest" },
        },
        {
            id = "bonaventure-of-bagnoregio-bishop",
            date = "07-15",
            rank = "memorial",
            precedence = 10,
            colors = { "white" },
            commons = { "bishops", "doctors_of_the_church" },
            saints = { "bonaventure-of-bagnoregio-bishop" },
        },
        {
            id = "our-lady-of-mount-carmel",
            date = "07-16",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "blessed_virgin_mary" },
        },
        {
            id = "apollinaris-of-ravenna-bishop",
            date = "07-20",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "red" },
            commons = { "martyrs", "bishops" },
            saints = { "apollinaris-of-ravenna-bishop" },
        },
        {
            id = "lawrence-of-brindisi-priest",
            date = "07-21",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "pastors", "doctors_of_the_church", "religious" },
            saints = { "lawrence-of-brindisi-priest" },
        },
        {
            id = "mary-magdalene",
            date = "07-22",
            rank = "feast",
            precedence = 7,
            colors = { "white" },
            saints = { "mary-magdalene" },
        },
        {
            id = "bridget-of-sweden-religious",
            date = "07-23",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "holy_women", "religious" },
            saints = { "bridget-of-sweden-religious" },
        },
        {
            id = "sharbel-makhluf-priest",
            date = "07-24",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "pastors", "monks" },
            saints = { "sharbel-makhluf-priest" },
        },
        {
            id = "james-apostle",
            date = "07-25",
            rank = "feast",
            precedence = 7,
            colors = { "red" },
            saints = { "james-apostle" },
        },
        {
            id = "joachim-and-anne-parents-of-mary",
            date = "07-26",
            rank = "memorial",
            precedence = 10,
            colors = { "white" },
            saints = { "joachim-father-of-mary", "anne-mother-of-mary" },
        },
        {
            id = "martha-of-bethany-mary-of-bethany-and-lazarus-of-bethany",
            date = "07-29",
            rank = "memorial",
            precedence = 10,
            colors = { "white" },
            saints = { "martha-of-bethany", "mary-of-bethany", "lazarus-of-bethany" },
        },
        {
            id = "peter-chrysologus-bishop",
            date = "07-30",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "bishops", "doctors_of_the_church" },
            saints = { "peter-chrysologus-bishop" },
        },
        {
            id = "ignatius-of-loyola-priest",
            date = "07-31",
            rank = "memorial",
            precedence = 10,
            colors = { "white" },
            saints = { "ignatius-of-loyola-priest" },
        },
        {
            id = "alphonsus-mary-liguori-bishop",
            date = "08-01",
            rank = "memorial",
            precedence = 10,
            colors = { "white" },
            commons = { "bishops", "doctors_of_the_church" },
            saints = { "alphonsus-mary-liguori-bishop" },
        },
        {
            id = "eusebius-of-vercelli-bishop",
            date = "08-02",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "bishops" },
            saints = { "eusebius-of-vercelli-bishop" },
        },
        {
            id = "peter-julian-eymard-priest",
            date = "08-02",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "religious", "pastors" },
            saints = { "peter-julian-eymard-priest" },
        },
        {
            id = "john-mary-vianney-priest",
            date = "08-04",
            rank = "memorial",
            precedence = 10,
            colors = { "white" },
            commons = { "pastors" },
            saints = { "john-mary-vianney-priest" },
        },
        {
            id = "dedication-of-the-basilica-of-saint-mary-major",
            date = "08-05",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "blessed_virgin_mary" },
        },
        {
            id = "cajetan-of-thiene-priest",
            date = "08-07",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "pastors", "religious" },
            saints = { "cajetan-of-thiene-priest" },
        },
        {
            id = "sixtus-ii-pope-and-companions-martyrs",
            date = "08-07",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "red" },
            commons = { "martyrs" },
            plural = true,
            saints = { "sixtus-ii-pope", "companions-of-sixtus-ii-pope" },
        },
        {
            id = "dominic-de-guzman-priest",
            date = "08-08",
            rank = "memorial",
            precedence = 10,
            colors = { "white" },
            saints = { "dominic-de-guzman-priest" },
        },
        {
            id = "teresa-benedicta-of-the-cross-stein-virgin",
            date = "08-09",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "red" },
            commons = { "martyrs", "virgins" },
            saints = { "teresa-benedicta-of-the-cross-stein-virgin" },
        },
        {
            id = "lawrence-of-rome-deacon",
            date = "08-10",
            rank = "feast",
            precedence = 7,
            colors = { "red" },
            saints = { "lawrence-of-rome-deacon" },
        },
        {
            id = "clare-of-assisi-virgin",
            date = "08-11",
            rank = "memorial",
            precedence = 10,
            colors = { "white" },
            commons = { "virgins", "nuns" },
            saints = { "clare-of-assisi-virgin" },
        },
        {
            id = "jane-frances-de-chantal-religious",
            date = "08-12",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "religious" },
            saints = { "jane-frances-de-chantal-religious" },
        },
        {
            id = "pontian-i-pope-and-hippolytus-of-rome-priest",
            date = "08-13",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "red" },
            commons = { "martyrs", "pastors" },
            plural = true,
            saints = { "pontian-i-pope", "hippolytus-of-rome-priest" },
        },
        {
            id = "maximilian-mary-raymund-kolbe-priest",
            date = "08-14",
            rank = "memorial",
            precedence = 10,
            colors = { "red" },
            commons = { "martyrs" },
            saints = { "maximilian-mary-raymund-kolbe-priest" },
        },
        {
            id = "stephen-i-of-hungary",
            date = "08-16",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "saints" },
            saints = { "stephen-i-of-hungary" },
        },
        {
            id = "john-eudes-priest",
            date = "08-19",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "pastors", "religious" },
            saints = { "john-eudes-priest" },
        },
        {
            id = "bernard-of-clairvaux-abbot",
            date = "08-20",
            rank = "memorial",
            precedence = 10,
            colors = { "white" },
            saints = { "bernard-of-clairvaux-abbot" },
        },
        {
            id = "pius-x-pope",
            date = "08-21",
            rank = "memorial",
            precedence = 10,
            colors = { "white" },
            commons = { "pope_or_bishop" },
            saints = { "pius-x-pope" },
        },
        {
            id = "queenship-of-the-blessed-virgin-mary",
            date = "08-22",
            rank = "memorial",
            precedence = 10,
            colors = { "white" },
        },
        {
            id = "rose-of-lima-virgin",
            date = "08-23",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "virgins" },
            saints = { "rose-of-lima-virgin" },
        },
        {
            id = "bartholomew-apostle",
            date = "08-24",
            rank = "feast",
            precedence = 7,
            colors = { "red" },
            saints = { "bartholomew-apostle" },
        },
        {
            id = "joseph-of-calasanz-priest",
            date = "08-25",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "educators", "pastors" },
            saints = { "joseph-of-calasanz-priest" },
        },
        {
            id = "louis-ix-of-france",
            date = "08-25",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "saints" },
            saints = { "louis-ix-of-france" },
        },
        {
            id = "monica-of-hippo",
            date = "08-27",
            rank = "memorial",
            precedence = 10,
            colors = { "white" },
            commons = { "holy_women" },
            saints = { "monica-of-hippo" },
        },
        {
            id = "augustine-of-hippo-bishop",
            date = "08-28",
            rank = "memorial",
            precedence = 10,
            colors = { "white" },
            saints = { "augustine-of-hippo-bishop" },
        },
        {
            id = "passion-of-saint-john-the-baptist",
            date = "08-29",
            rank = "memorial",
            precedence = 10,
            colors = { "red" },
        },
        {
            id = "gregory-i-the-great-pope",
            date = "09-03",
            rank = "memorial",
            precedence = 10,
            colors = { "white" },
            saints = { "gregory-i-the-great-pope" },
        },
        {
            id = "teresa-of-calcutta-virgin",
            date = "09-05",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "virgins" },
            saints = { "teresa-of-calcutta-virgin" },
        },
        {
            id = "nativity-of-the-blessed-virgin-mary",
            date = "09-08",
            rank = "feast",
            precedence = 7,
            colors = { "white" },
        },
        {
            id = "peter-claver-priest",
            date = "09-09",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "pastors", "mercy_workers" },
            saints = { "peter-claver-priest" },
        },
        {
            id = "most-holy-name-of-mary",
            date = "09-12",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "john-chrysostom-bishop",
            date = "09-13",
            rank = "memorial",
            precedence = 10,
            colors = { "white" },
            saints = { "john-chrysostom-bishop" },
        },
        {
            id = "our-lady-of-sorrows",
            date = "09-15",
            rank = "memorial",
            precedence = 10,
            colors = { "white" },
        },
        {
            id = "cornelius-i-pope-and-cyprian-of-carthage-bishop-martyrs",
            date = "09-16",
            rank = "memorial",
            precedence = 10,
            colors = { "red" },
            commons = { "martyrs", "pastors" },
            plural = true,
            saints = { "cornelius-i-pope", "cyprian-of-carthage-bishop" },
        },
        {
            id = "hildegard-of-bingen-abbess",
            date = "09-17",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "virgins", "nuns" },
            saints = { "hildegard-of-bingen-abbess" },
        },
        {
            id = "robert-bellarmine-bishop",
            date = "09-17",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "bishops", "doctors_of_the_church" },
            saints = { "robert-bellarmine-bishop" },
        },
        {
            id = "januarius-i-of-benevento-bishop",
            date = "09-19",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "red" },
            commons = { "martyrs", "bishops" },
            saints = { "januarius-i-of-benevento-bishop" },
        },
        {
            id = "andrew-kim-tae-gon-priest-paul-chong-ha-sang-and-companions-martyrs",
            date = "09-20",
            rank = "memorial",
            precedence = 10,
            colors = { "red" },
            commons = { "martyrs" },
            plural = true,
            saints = {
                "andrew-kim-tae-gon-priest",
                "paul-chong-ha-sang-martyr",
                "companions-of-andrew-kim-tae-gon-priest",
            },
        },
        {
            id = "matthew-apostle",
            date = "09-21",
            rank = "feast",
            precedence = 7,
            colors = { "red" },
            saints = { "matthew-apostle" },
        },
        {
            id = "pius-francesco-forgione-priest",
            date = "09-23",
            rank = "memorial",
            precedence = 10,
            colors = { "white" },
            commons = { "pastors", "religious" },
            saints = { "pius-francesco-forgione-priest" },
        },
        {
            id = "cosmas-of-cilicia-and-damian-of-cilicia-martyrs",
            date = "09-26",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "red" },
            commons = { "martyrs" },
            plural = true,
            saints = { "cosmas-of-cilicia-martyr", "damian-of-cilicia-martyr" },
        },
        {
            id = "vincent-de-paul-priest",
            date = "09-27",
            rank = "memorial",
            precedence = 10,
            colors = { "white" },
            saints = { "vincent-de-paul-priest" },
        },
        {
            id = "lawrence-ruiz-and-companions-martyrs",
            date = "09-28",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "red" },
            commons = { "martyrs" },
            plural = true,
            saints = { "lawrence-ruiz-martyr", "companions-of-lawrence-ruiz-martyr" },
        },
        {
            id = "wenceslaus-i-of-bohemia-martyr",
            date = "09-28",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "red" },
            commons = { "martyrs" },
            saints = { "wenceslaus-i-of-bohemia-martyr" },
        },
        {
            id = "michael-gabriel-and-raphael-archangels",
            date = "09-29",
            rank = "feast",
            precedence = 7,
            colors = { "white" },
            saints = { "michael-archangel", "gabriel-archangel", "raphael-archangel" },
        },
        {
            id = "jerome-of-stridon-priest",
            date = "09-30",
            rank = "memorial",
            precedence = 10,
            colors = { "white" },
            saints = { "jerome-of-stridon-priest" },
        },
        {
            id = "therese-of-the-child-jesus-and-the-holy-face-of-lisieux-virgin",
            date = "10-01",
            rank = "memorial",
            precedence = 10,
            colors = { "white" },
            saints = { "therese-of-the-child-jesus-and-the-holy-face-of-lisieux-virgin" },
        },
        {
            id = "holy-guardian-angels",
            date = "10-02",
            rank = "memorial",
            precedence = 10,
            colors = { "white" },
        },
        {
            id = "francis-of-assisi",
            date = "10-04",
            rank = "memorial",
            precedence = 10,
            colors = { "white" },
            saints = { "francis-of-assisi" },
        },
        {
            id = "faustina-kowalska-virgin",
            date = "10-05",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "virgins", "nuns" },
            saints = { "faustina-kowalska-virgin" },
        },
        {
            id = "bruno-of-cologne-priest",
            date = "10-06",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "monks", "pastors" },
            saints = { "bruno-of-cologne-priest" },
        },
        {
            id = "our-lady-of-the-rosary",
            date = "10-07",
            rank = "memorial",
            precedence = 10,
            colors = { "white" },
        },
        {
            id = "denis-of-paris-bishop-and-companions-martyrs",
            date = "10-09",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "red" },
            commons = { "martyrs" },
            plural = true,
            saints = { "denis-of-paris-bishop", "companions-of-denis-of-paris-bishop" },
        },
        {
            id = "john-henry-newman-priest",
            date = "10-09",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "pastors", "doctors_of_the_church" },
            saints = { "john-henry-newman-priest" },
        },
        {
            id = "john-leonardi-priest",
            date = "10-09",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "missionaries", "mercy_workers" },
            saints = { "john-leonardi-priest" },
        },
        {
            id = "john-xxiii-pope",
            date = "10-11",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "pope_or_bishop" },
            saints = { "john-xxiii-pope" },
        },
        {
            id = "callistus-i-pope",
            date = "10-14",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "red" },
            commons = { "martyrs", "pope_or_bishop" },
            saints = { "callistus-i-pope" },
        },
        {
            id = "teresa-of-jesus-of-avila-virgin",
            date = "10-15",
            rank = "memorial",
            precedence = 10,
            colors = { "white" },
            commons = { "virgins", "doctors_of_the_church" },
            saints = { "teresa-of-jesus-of-avila-virgin" },
        },
        {
            id = "hedwig-of-silesia-religious",
            date = "10-16",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "religious", "holy_women" },
            saints = { "hedwig-of-silesia-religious" },
        },
        {
            id = "margaret-mary-alacoque-virgin",
            date = "10-16",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "virgins" },
            saints = { "margaret-mary-alacoque-virgin" },
        },
        {
            id = "ignatius-of-antioch-bishop",
            date = "10-17",
            rank = "memorial",
            precedence = 10,
            colors = { "red" },
            saints = { "ignatius-of-antioch-bishop" },
        },
        {
            id = "luke-evangelist",
            date = "10-18",
            rank = "feast",
            precedence = 7,
            colors = { "red" },
            saints = { "luke-evangelist" },
        },
        {
            id = "john-de-brebeuf-isaac-jogues-priests-and-companions-martyrs",
            date = "10-19",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "red" },
            commons = { "missionary_martyrs" },
            plural = true,
            saints = {
                "john-de-brebeuf-priest",
                "isaac-jogues-priest",
                "companions-of-john-de-brebeuf-priest",
            },
        },
        {
            id = "paul-of-the-cross-priest",
            date = "10-19",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            saints = { "paul-of-the-cross-priest" },
        },
        {
            id = "john-paul-ii-pope",
            date = "10-22",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "pope_or_bishop" },
            saints = { "john-paul-ii-pope" },
        },
        {
            id = "john-of-capistrano-priest",
            date = "10-23",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "missionaries", "religious" },
            saints = { "john-of-capistrano-priest" },
        },
        {
            id = "anthony-mary-claret-bishop",
            date = "10-24",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "missionaries", "bishops" },
            saints = { "anthony-mary-claret-bishop" },
        },
        {
            id = "simon-and-jude-apostles",
            date = "10-28",
            rank = "feast",
            precedence = 7,
            colors = { "red" },
            saints = { "simon-apostle", "jude-apostle" },
        },
        {
            id = "commemoration-of-all-the-faithful-departed",
            date = "11-02",
            rank = "commemoration",
            precedence = 3,
            colors = { "violet", "black" },
        },
        {
            id = "martin-de-porres-religious",
            date = "11-03",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "religious" },
            saints = { "martin-de-porres-religious" },
        },
        {
            id = "charles-borromeo-bishop",
            date = "11-04",
            rank = "memorial",
            precedence = 10,
            colors = { "white" },
            commons = { "bishops" },
            saints = { "charles-borromeo-bishop" },
        },
        {
            id = "dedication-of-the-lateran-basilica",
            date = "11-09",
            rank = "feast",
            precedence = 5,
            colors = { "white" },
        },
        {
            id = "leo-i-the-great-pope",
            date = "11-10",
            rank = "memorial",
            precedence = 10,
            colors = { "white" },
            saints = { "leo-i-the-great-pope" },
        },
        {
            id = "martin-of-tours-bishop",
            date = "11-11",
            rank = "memorial",
            precedence = 10,
            colors = { "white" },
            saints = { "martin-of-tours-bishop" },
        },
        {
            id = "josaphat-kuntsevych-bishop",
            date = "11-12",
            rank = "memorial",
            precedence = 10,
            colors = { "red" },
            saints = { "josaphat-kuntsevych-bishop" },
        },
        {
            id = "albert-the-great-bishop",
            date = "11-15",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "bishops", "doctors_of_the_church" },
            saints = { "albert-the-great-bishop" },
        },
        {
            id = "gertrude-the-great-virgin",
            date = "11-16",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "virgins", "nuns" },
            saints = { "gertrude-the-great-virgin" },
        },
        {
            id = "margaret-of-scotland",
            date = "11-16",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "mercy_workers" },
            saints = { "margaret-of-scotland" },
        },
        {
            id = "elizabeth-of-hungary-religious",
            date = "11-17",
            rank = "memorial",
            precedence = 10,
            colors = { "white" },
            commons = { "mercy_workers" },
            saints = { "elizabeth-of-hungary-religious" },
        },
        {
            id = "dedication-of-the-basilicas-of-saints-peter-and-paul-apostles",
            date = "11-18",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "presentation-of-the-blessed-virgin-mary",
            date = "11-21",
            rank = "memorial",
            precedence = 10,
            colors = { "white" },
            commons = { "blessed_virgin_mary" },
        },
        {
            id = "cecilia-of-rome-virgin",
            date = "11-22",
            rank = "memorial",
            precedence = 10,
            colors = { "red" },
            commons = { "virgin_martyrs", "virgins" },
            saints = { "cecilia-of-rome-virgin" },
        },
        {
            id = "clement-i-pope",
            date = "11-23",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "red" },
            commons = { "martyrs", "pope_or_bishop" },
            saints = { "clement-i-pope" },
        },
        {
            id = "columban-of-luxeuil-abbot",
            date = "11-23",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "missionaries", "abbots" },
            saints = { "columban-of-luxeuil-abbot" },
        },
        {
            id = "andrew-dung-lac-priest-and-companions-martyrs",
            date = "11-24",
            rank = "memorial",
            precedence = 10,
            colors = { "red" },
            commons = { "martyrs" },
            plural = true,
            saints = { "andrew-dung-lac-priest", "companions-of-andrew-dung-lac-priest" },
        },
        {
            id = "catherine-of-alexandria-virgin",
            date = "11-25",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "red" },
            commons = { "virgin_martyrs", "virgins" },
            saints = { "catherine-of-alexandria-virgin" },
        },
        {
            id = "andrew-apostle",
            date = "11-30",
            rank = "feast",
            precedence = 7,
            colors = { "red" },
            saints = { "andrew-apostle" },
        },
        {
            id = "francis-xavier-priest",
            date = "12-03",
            rank = "memorial",
            precedence = 10,
            colors = { "white" },
            saints = { "francis-xavier-priest" },
        },
        {
            id = "john-damascene-priest",
            date = "12-04",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "pastors", "doctors_of_the_church" },
            saints = { "john-damascene-priest" },
        },
        {
            id = "nicholas-of-myra-bishop",
            date = "12-06",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "bishops" },
            saints = { "nicholas-of-myra-bishop" },
        },
        {
            id = "ambrose-of-milan-bishop",
            date = "12-07",
            rank = "memorial",
            precedence = 10,
            colors = { "white" },
            saints = { "ambrose-of-milan-bishop" },
        },
        {
            id = "juan-diego-cuauhtlatoatzin",
            date = "12-09",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "saints" },
            saints = { "juan-diego-cuauhtlatoatzin" },
        },
        {
            id = "our-lady-of-loreto",
            date = "12-10",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "blessed_virgin_mary" },
        },
        {
            id = "damasus-i-pope",
            date = "12-11",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "pope_or_bishop" },
            saints = { "damasus-i-pope" },
        },
        {
            id = "our-lady-of-guadalupe",
            date = "12-12",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "blessed_virgin_mary" },
        },
        {
            id = "lucy-of-syracuse-virgin",
            date = "12-13",
            rank = "memorial",
            precedence = 10,
            colors = { "red" },
            commons = { "virgin_martyrs", "virgins" },
            saints = { "lucy-of-syracuse-virgin" },
        },
        {
            id = "john-of-the-cross-priest",
            date = "12-14",
            rank = "memorial",
            precedence = 10,
            colors = { "white" },
            saints = { "john-of-the-cross-priest" },
        },
        {
            id = "peter-canisius-priest",
            date = "12-21",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "pastors", "doctors_of_the_church" },
            saints = { "peter-canisius-priest" },
        },
        {
            id = "john-of-kanty-priest",
            date = "12-23",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "pastors", "mercy_workers" },
            saints = { "john-of-kanty-priest" },
        },
        {
            id = "stephen-the-first-martyr",
            date = "12-26",
            rank = "feast",
            precedence = 7,
            colors = { "red" },
            saints = { "stephen-the-first-martyr" },
        },
        {
            id = "john-apostle",
            date = "12-27",
            rank = "feast",
            precedence = 7,
            colors = { "white" },
            saints = { "john-apostle" },
        },
        {
            id = "holy-innocents-martyrs",
            date = "12-28",
            rank = "feast",
            precedence = 7,
            colors = { "red" },
        },
        {
            id = "thomas-becket-bishop",
            date = "12-29",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "red" },
            commons = { "martyrs", "bishops" },
            saints = { "thomas-becket-bishop" },
        },
        {
            id = "sylvester-i-pope",
            date = "12-31",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "pope_or_bishop" },
            saints = { "sylvester-i-pope" },
        },
        {
            id = "all-saints",
            date = { fn = "all_saints" },
            rank = "solemnity",
            precedence = 3,
            colors = { "white" },
            obligation = true,
        },
        {
            id = "annunciation-of-the-lord",
            date = { fn = "annunciation" },
            rank = "solemnity",
            precedence = 3,
            colors = { "white" },
        },
        {
            id = "assumption-of-the-blessed-virgin-mary",
            date = { fn = "assumption" },
            rank = "solemnity",
            precedence = 2,
            colors = { "white" },
            obligation = true,
        },
        {
            id = "exaltation-of-the-holy-cross",
            date = { fn = "exaltation_of_the_holy_cross" },
            rank = "feast",
            precedence = 5,
            colors = { "red" },
        },
        {
            id = "immaculate-conception-of-the-blessed-virgin-mary",
            date = { fn = "immaculate_conception_of_mary" },
            rank = "solemnity",
            precedence = 3,
            colors = { "white" },
            obligation = true,
        },
        {
            id = "immaculate-heart-of-mary",
            date = { fn = "immaculate_heart_of_mary" },
            rank = "memorial",
            precedence = 10,
            colors = { "white" },
            similar = true,
        },
        {
            id = "mary-mother-of-the-church",
            date = { fn = "mary_mother_of_the_church" },
            rank = "memorial",
            precedence = 10,
            colors = { "white" },
            commons = { "blessed_virgin_mary" },
        },
        {
            id = "nativity-of-john-the-baptist",
            date = { fn = "nativity_of_john_the_baptist" },
            rank = "solemnity",
            precedence = 3,
            colors = { "white" },
        },
        {
            id = "peter-and-paul-apostles",
            date = { fn = "peter_and_paul_apostles" },
            rank = "solemnity",
            precedence = 3,
            colors = { "red" },
            obligation = true,
            saints = { "peter-apostle", "paul-apostle" },
        },
        {
            id = "presentation-of-the-lord",
            date = { fn = "presentation_of_the_lord" },
            rank = "feast",
            precedence = 5,
            colors = { "white" },
        },
        {
            id = "transfiguration-of-the-lord",
            date = { fn = "transfiguration" },
            rank = "feast",
            precedence = 5,
            colors = { "white" },
        },
    },
}
