-- Calendar of IE: changes to the General Roman Calendar.
-- Origin: romcal @ 30344b3 (MIT), normalized in parked/epub/data/calendars/ie-overlay.json;
-- transfers also from parked/epub/data/calendars/transfer-decisions.json.
-- transfers: solemnities moved to Sunday (epiphany, ascension, corpus_christi).
-- celebrations: added, or replacing the general celebration with the same id; title: the
-- calendar's own title for it (tag celebration.<title>), e.g. "..., Patron of Europe".
return {
    celebrations = {
        {
            id = "munchin-of-limerick-bishop",
            date = "01-03",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "ita-of-killeedy-virgin",
            date = "01-15",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "virgins" },
        },
        {
            id = "fursa-of-peronne-abbot",
            date = "01-16",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "aidan-of-ferns-bishop",
            date = "01-30",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "brigid-of-kildare-virgin",
            date = "02-01",
            rank = "feast",
            precedence = 8,
            colors = { "white" },
            commons = { "virgins" },
        },
        {
            id = "mel-of-ardagh-bishop",
            date = "02-07",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "gobnait-of-ballyvourney-virgin",
            date = "02-11",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "cyril-constantine-the-philosopher-monk-and-methodius-michael-of-thessaloniki-bishop",
            date = "02-14",
            title = "cyril-constantine-the-philosopher-monk-and-methodius-michael-of-thessaloniki-bishop-copatrons-of-europe",
            rank = "feast",
            precedence = 8,
            colors = { "white" },
            saints = {
                "cyril-constantine-the-philosopher-monk",
                "methodius-michael-of-thessaloniki-bishop",
            },
        },
        {
            id = "fintan-of-clonenagh-abbot",
            date = "02-17",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "david-of-wales-bishop",
            date = "03-01",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "kieran-of-saigir-bishop",
            date = "03-05",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "senan-of-inis-cathaigh-bishop",
            date = "03-08",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "aengus-of-tallaght-bishop",
            date = "03-11",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "patrick-of-ireland-bishop",
            date = "03-17",
            title = "patrick-of-ireland-bishop-patron-of-ireland",
            rank = "solemnity",
            precedence = 4,
            colors = { "white" },
            commons = { "missionaries", "bishops" },
            obligation = true,
            saints = { "patrick-of-ireland-bishop" },
        },
        {
            id = "enda-of-aran-abbot",
            date = "03-21",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "macartan-of-clogher-bishop",
            date = "03-24",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "ceallach-of-armagh-bishop",
            date = "04-01",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "laserian-of-leighlin-bishop",
            date = "04-18",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "asicus-of-elphin-bishop",
            date = "04-27",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "catherine-of-siena-virgin",
            date = "04-29",
            title = "catherine-of-siena-virgin-copatroness-of-europe",
            rank = "feast",
            precedence = 8,
            colors = { "white" },
            saints = { "catherine-of-siena-virgin" },
        },
        {
            id = "conleth-of-kildare-bishop",
            date = "05-04",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "edmund-ignatius-rice-religious",
            date = "05-05",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "comgall-of-bangor-abbot",
            date = "05-10",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "carthage-of-lismore-bishop",
            date = "05-15",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "brendan-of-clonfert-abbot",
            date = "05-16",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "kevin-of-glendalough-abbot",
            date = "06-03",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
        },
        {
            id = "jarlath-of-tuam-bishop",
            date = "06-06",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "colman-of-dromore-bishop",
            date = "06-07",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "columba-of-iona-abbot",
            date = "06-09",
            rank = "feast",
            precedence = 8,
            colors = { "white" },
            commons = { "abbots" },
        },
        {
            id = "davnet-of-sliabh-beagh-virgin",
            date = "06-14",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "irish-martyrs",
            date = "06-20",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "martyrs" },
            plural = true,
        },
        {
            id = "oliver-plunket-bishop",
            date = "07-01",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "martyrs" },
        },
        {
            id = "moninne-of-killeavy-virgin",
            date = "07-06",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "maelruain-of-tallaght-bishop",
            date = "07-07",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "kilian-of-wurzburg-bishop",
            date = "07-08",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "benedict-of-nursia-abbot",
            date = "07-11",
            title = "benedict-of-nursia-abbot-patron-of-europe",
            rank = "feast",
            precedence = 8,
            colors = { "white" },
            saints = { "benedict-of-nursia-abbot" },
        },
        {
            id = "bridget-of-sweden-religious",
            date = "07-23",
            title = "bridget-of-sweden-religious-copatroness-of-europe",
            rank = "feast",
            precedence = 8,
            colors = { "white" },
            commons = { "holy_women", "religious" },
            saints = { "bridget-of-sweden-religious" },
        },
        {
            id = "declan-of-ardmore-bishop",
            date = "07-24",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "teresa-benedicta-of-the-cross-stein-virgin",
            date = "08-09",
            title = "teresa-benedicta-of-the-cross-stein-virgin-copatroness-of-europe",
            rank = "feast",
            precedence = 8,
            colors = { "red" },
            commons = { "martyrs", "virgins" },
            saints = { "teresa-benedicta-of-the-cross-stein-virgin" },
        },
        {
            id = "attracta-of-killaraght-virgin",
            date = "08-12",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "lelia-of-killeely-virgin",
            date = "08-12",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "muredach-of-killala-bishop",
            date = "08-12",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "fachtna-of-rosscarbery-bishop",
            date = "08-13",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "our-lady-of-knock",
            date = "08-17",
            rank = "feast",
            precedence = 8,
            colors = { "white" },
            commons = { "blessed_virgin_mary" },
        },
        {
            id = "eoghan-of-ardstraw-bishop",
            date = "08-23",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "fiacre-of-breuil-monk",
            date = "08-30",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "aidan-of-lindisfarne-bishop",
            date = "08-31",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "mac-nissi-of-connor-bishop",
            date = "09-04",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "ciaran-of-clonmacnoise-abbot",
            date = "09-09",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "abbots" },
        },
        {
            id = "ailbe-of-emly-bishop",
            date = "09-12",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "finbarr-of-cork-bishop",
            date = "09-25",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "columba-marmion-priest",
            date = "10-03",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "canice-of-kilkenny-abbot",
            date = "10-11",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "gall-of-switzerland-abbot",
            date = "10-16",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "otteran-of-iona-monk",
            date = "10-27",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "colman-of-kilmacduagh-bishop",
            date = "10-29",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "malachy-of-armagh-bishop",
            date = "11-03",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "bishops" },
        },
        {
            id = "all-saints-of-ireland",
            date = "11-06",
            rank = "feast",
            precedence = 8,
            colors = { "white" },
            commons = { "saints" },
            office = "all-saints",
        },
        {
            id = "willibrord-of-utrecht-bishop",
            date = "11-07",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "laurence-otoole-bishop",
            date = "11-14",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "columban-of-luxeuil-abbot",
            date = "11-23",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "missionaries", "abbots" },
            saints = { "columban-of-luxeuil-abbot" },
        },
        {
            id = "colman-of-cloyne-bishop",
            date = "11-25",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "virgilius-of-salzburg-bishop",
            date = "11-27",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "finnian-of-clonard-bishop",
            date = "12-12",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "flannan-of-killaloe-bishop",
            date = "12-18",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "fachanan-of-kilfenora-bishop",
            date = "12-20",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
    },
    transfers = {},
}
