-- Calendar of MX: changes to the General Roman Calendar.
-- Origin: romcal @ 30344b3 (MIT), normalized in parked/epub/data/calendars/mx-overlay.json;
-- transfers also from parked/epub/data/calendars/transfer-decisions.json.
-- transfers: solemnities moved to Sunday (epiphany, ascension, corpus_christi).
-- celebrations: added, or replacing the general celebration with the same id; title: the
-- calendar's own title for it (tag celebration.<title>), e.g. "..., Patron of Europe".
return {
    celebrations = {
        {
            id = "philip-of-jesus-de-las-casas-martyr",
            date = "02-05",
            rank = "feast",
            precedence = 8,
            colors = { "white" },
            commons = { "martyrs" },
        },
        {
            id = "sebastian-de-aparicio-religious",
            date = "02-25",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "maria-guadalupe-garcia-zavala-virgin",
            date = "04-27",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "finding-of-the-holy-cross",
            date = "05-03",
            rank = "feast",
            precedence = 8,
            colors = { "white" },
            office = "exaltation-of-the-holy-cross",
            readings = "exaltation-of-the-holy-cross",
        },
        {
            id = "philip-and-james-apostles",
            date = "05-04",
            rank = "feast",
            precedence = 7,
            colors = { "red" },
            saints = { "philip-apostle", "james-apostle" },
        },
        {
            id = "isidore-the-farmer",
            date = "05-15",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "saints" },
        },
        {
            id = "john-nepomucene-priest",
            date = "05-16",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "martyrs" },
        },
        {
            id = "christopher-magallanes-priest-and-companions-martyrs",
            date = "05-21",
            rank = "memorial",
            precedence = 11,
            colors = { "red" },
            commons = { "martyrs" },
            plural = true,
            saints = { "christopher-magallanes-priest", "companions-martyrs" },
        },
        {
            id = "our-lady-of-perpetual-help",
            date = "06-27",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "our-lady-refuge-of-sinners",
            date = "07-04",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "mary-of-jesus-in-the-blessed-sacrament-venegas-de-la-torre-virgin",
            date = "07-30",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "bartholomew-dias-laurel-religious",
            date = "08-16",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "peter-de-zuniga-and-louis-flores-priests",
            date = "08-16",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            saints = { "peter-de-zuniga-priest", "louis-flores-priest" },
        },
        {
            id = "junipero-serra-priest",
            date = "08-26",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "rose-of-lima-virgin",
            date = "08-30",
            rank = "feast",
            precedence = 8,
            colors = { "white" },
            commons = { "virgins" },
            saints = { "rose-of-lima-virgin" },
        },
        {
            id = "jose-maria-de-yermo-y-parres-priest",
            date = "09-19",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "our-lady-of-mercy",
            date = "09-24",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "blessed_virgin_mary" },
        },
        {
            id = "raphael-guizar-y-valencia-bishop",
            date = "10-24",
            rank = "feast",
            precedence = 8,
            colors = { "white" },
            commons = { "bishops" },
        },
        {
            id = "miguel-agustin-pro-priest",
            date = "11-23",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "juan-diego-cuauhtlatoatzin",
            date = "12-09",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "saints" },
            saints = { "juan-diego-cuauhtlatoatzin" },
        },
        {
            id = "our-lady-of-guadalupe",
            date = "12-12",
            title = "our-lady-of-guadalupe-patroness-of-the-americas",
            rank = "solemnity",
            precedence = 4,
            colors = { "white" },
            commons = { "blessed_virgin_mary" },
        },
        {
            id = "our-lord-jesus-christ-the-eternal-high-priest",
            date = { fn = "pentecost_sunday", offset = 4 },
            rank = "feast",
            precedence = 8,
            colors = { "white" },
            office = "weekday",
        },
    },
    transfers = {},
}
