-- Calendar of PL: changes to the General Roman Calendar.
-- Origin: romcal @ 30344b3 (MIT), normalized in parked/epub/data/calendars/pl-overlay.json;
-- transfers also from parked/epub/data/calendars/transfer-decisions.json.
-- transfers: solemnities moved to Sunday (epiphany, ascension, corpus_christi).
-- celebrations: added, or replacing the general celebration with the same id; title: the
-- calendar's own title for it (tag celebration.<title>), e.g. "..., Patron of Europe".
return {
    celebrations = {
        {
            id = "joseph-sebastian-pelczar-bishop",
            date = "01-19",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "bishops" },
        },
        {
            id = "vincent-pallotti-priest",
            date = "01-22",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "vincent-lewoniuk-and-companions-martyrs",
            date = "01-23",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            saints = { "vincent-lewoniuk-martyr", "companions-martyrs" },
        },
        {
            id = "george-matulaitis-bishop",
            date = "01-27",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "angela-merici-virgin",
            date = "01-29",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "virgins", "educators" },
            saints = { "angela-merici-virgin" },
        },
        {
            id = "boleslawa-mary-lament-virgin",
            date = "01-29",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "cyril-constantine-the-philosopher-monk-and-methodius-michael-of-thessaloniki-bishop",
            date = "02-14",
            title = "cyril-constantine-the-philosopher-monk-and-methodius-michael-of-thessaloniki-bishop-copatrons-of-europe",
            rank = "feast",
            precedence = 8,
            colors = { "white" },
            saints = {
                "cyril-constantine-the-philosopher-monk",
                "methodius-michael-of-thessaloniki-bishop",
            },
        },
        {
            id = "casimir-of-poland",
            date = "03-04",
            rank = "feast",
            precedence = 8,
            colors = { "white" },
            commons = { "saints" },
            saints = { "casimir-of-poland" },
        },
        {
            id = "adalbert-of-prague-bishop",
            date = "04-23",
            title = "adalbert-of-prague-bishop-patron-of-poland",
            rank = "solemnity",
            precedence = 4,
            colors = { "red" },
            commons = { "martyrs", "bishops" },
            exceptions = {
                {
                    move = { fn = "divine_mercy_sunday", offset = 1 },
                    when = { between = { "palm_sunday", "divine_mercy_sunday" }, inclusive = true },
                },
            },
            saints = { "adalbert-of-prague-bishop" },
        },
        {
            id = "catherine-of-siena-virgin",
            date = "04-29",
            title = "catherine-of-siena-virgin-copatroness-of-europe",
            rank = "feast",
            precedence = 8,
            colors = { "white" },
            saints = { "catherine-of-siena-virgin" },
        },
        {
            id = "our-lady-queen-of-poland",
            date = "05-03",
            rank = "solemnity",
            precedence = 4,
            colors = { "white" },
            commons = { "blessed_virgin_mary" },
        },
        {
            id = "florian-of-lorch-martyr",
            date = "05-04",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "martyrs" },
        },
        {
            id = "stanislaus-kazimierczyk-priest",
            date = "05-05",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "philip-and-james-apostles",
            date = "05-06",
            rank = "feast",
            precedence = 7,
            colors = { "red" },
            saints = { "philip-apostle", "james-apostle" },
        },
        {
            id = "stanislaus-of-szczepanow-bishop",
            date = "05-08",
            title = "stanislaus-of-szczepanow-bishop-patron-of-poland",
            rank = "solemnity",
            precedence = 4,
            colors = { "red" },
            commons = { "martyrs", "bishops" },
            saints = { "stanislaus-of-szczepanow-bishop" },
        },
        {
            id = "andrew-bobola-priest",
            date = "05-16",
            rank = "feast",
            precedence = 8,
            colors = { "white" },
            commons = { "martyrs" },
        },
        {
            id = "our-lady-help-of-christians",
            date = "05-24",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "blessed_virgin_mary" },
        },
        {
            id = "mary-ursula-of-jesus-ledochowska-virgin",
            date = "05-29",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "virgins" },
        },
        {
            id = "john-sarkander-priest",
            date = "05-30",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "zdislava-of-lemberk",
            date = "05-30",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "hedwig-of-poland",
            date = "06-08",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "holy_women" },
        },
        {
            id = "bogumilus-of-dobrow-bishop",
            date = "06-10",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "bishops" },
        },
        {
            id = "anthony-julian-nowowiejski-bishop-and-companions-martyrs",
            date = "06-12",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            saints = { "anthony-julian-nowowiejski-bishop", "companions-martyrs" },
        },
        {
            id = "michael-kozal-bishop",
            date = "06-14",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "martyrs" },
        },
        {
            id = "yolanda-of-poland-religious",
            date = "06-15",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "religious" },
        },
        {
            id = "albert-chmielowski-religious",
            date = "06-17",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "religious" },
        },
        {
            id = "zygmunt-gorazdowski-priest",
            date = "06-26",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "otto-of-bamberg-bishop",
            date = "07-01",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "maria-goretti-virgin",
            date = "07-05",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "red" },
            commons = { "virgin_martyrs", "virgins" },
            saints = { "maria-goretti-virgin" },
        },
        {
            id = "mary-theresa-ledochowska-virgin",
            date = "07-06",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "virgins" },
        },
        {
            id = "john-of-dukla-priest",
            date = "07-08",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "pastors" },
        },
        {
            id = "benedict-of-nursia-abbot",
            date = "07-11",
            title = "benedict-of-nursia-abbot-patron-of-europe",
            rank = "feast",
            precedence = 8,
            colors = { "white" },
            saints = { "benedict-of-nursia-abbot" },
        },
        {
            id = "bruno-of-querfurt-bishop",
            date = "07-12",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "martyrs" },
        },
        {
            id = "andrew-zorard-of-nitra-and-benedict-of-skalka-hermits",
            date = "07-13",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "religious" },
            saints = { "andrew-zorard-of-nitra-hermit", "benedict-of-skalka-hermit" },
        },
        {
            id = "henry-ii-emperor",
            date = "07-14",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "saints" },
            saints = { "henry-ii-emperor" },
        },
        {
            id = "our-lady-of-mount-carmel",
            date = "07-16",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "blessed_virgin_mary" },
        },
        {
            id = "simon-of-lipnica-priest",
            date = "07-18",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "ceslaus-of-poland-priest",
            date = "07-20",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "pastors" },
        },
        {
            id = "apollinaris-of-ravenna-bishop",
            date = "07-21",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "red" },
            commons = { "martyrs", "bishops" },
            saints = { "apollinaris-of-ravenna-bishop" },
        },
        {
            id = "bridget-of-sweden-religious",
            date = "07-23",
            title = "bridget-of-sweden-religious-copatroness-of-europe",
            rank = "feast",
            precedence = 8,
            colors = { "white" },
            commons = { "holy_women", "religious" },
            saints = { "bridget-of-sweden-religious" },
        },
        {
            id = "kinga-of-poland-virgin",
            date = "07-24",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "virgins" },
        },
        {
            id = "sharbel-makhluf-priest",
            date = "07-28",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "pastors", "monks" },
            saints = { "sharbel-makhluf-priest" },
        },
        {
            id = "edmund-bojanowski",
            date = "08-07",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "teresa-benedicta-of-the-cross-stein-virgin",
            date = "08-09",
            title = "teresa-benedicta-of-the-cross-stein-virgin-copatroness-of-europe",
            rank = "feast",
            precedence = 8,
            colors = { "red" },
            commons = { "martyrs", "virgins" },
            saints = { "teresa-benedicta-of-the-cross-stein-virgin" },
        },
        {
            id = "hyacinth-of-poland-priest",
            date = "08-17",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "missionaries" },
        },
        {
            id = "our-lady-of-czestochowa",
            date = "08-26",
            rank = "solemnity",
            precedence = 4,
            colors = { "white" },
            commons = { "blessed_virgin_mary" },
        },
        {
            id = "bronislava-of-poland-virgin",
            date = "09-01",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "virgins" },
        },
        {
            id = "mary-stella-of-the-blessed-sacrament-mardosewicz-and-companions-virgins",
            date = "09-04",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            saints = {
                "mary-stella-of-the-blessed-sacrament-mardosewicz-virgin",
                "companions-martyrs",
            },
        },
        {
            id = "melchior-grodziecki-priest",
            date = "09-07",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "martyrs" },
        },
        {
            id = "angela-salawa-virgin",
            date = "09-09",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "denis-of-paris-bishop-and-companions-martyrs",
            date = "09-10",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "red" },
            commons = { "martyrs" },
            plural = true,
            saints = { "denis-of-paris-bishop", "companions-martyrs" },
        },
        {
            id = "john-leonardi-priest",
            date = "09-10",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "missionaries", "mercy_workers" },
            saints = { "john-leonardi-priest" },
        },
        {
            id = "sigmund-felix-felinski-bishop",
            date = "09-17",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "stanislaus-kostka-religious",
            date = "09-18",
            rank = "feast",
            precedence = 8,
            colors = { "white" },
            commons = { "religious" },
        },
        {
            id = "ladislas-of-gielniow-priest",
            date = "09-25",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "lawrence-ruiz-and-companions-martyrs",
            date = "09-26",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "red" },
            commons = { "martyrs" },
            plural = true,
            saints = { "lawrence-ruiz-martyr", "companions-martyrs" },
        },
        {
            id = "wenceslaus-i-of-bohemia-martyr",
            date = "09-28",
            rank = "memorial",
            precedence = 11,
            colors = { "red" },
            commons = { "martyrs" },
            saints = { "wenceslaus-i-of-bohemia-martyr" },
        },
        {
            id = "faustina-kowalska-virgin",
            date = "10-05",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "virgins", "nuns" },
            saints = { "faustina-kowalska-virgin" },
        },
        {
            id = "vincent-kadlubek-bishop",
            date = "10-09",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "bishops" },
        },
        {
            id = "mary-angela-truszkowska-virgin",
            date = "10-10",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "john-beyzym-priest",
            date = "10-12",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "missionaries" },
        },
        {
            id = "honorat-kozminski-priest",
            date = "10-13",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "margaret-mary-alacoque-virgin",
            date = "10-14",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "virgins" },
            saints = { "margaret-mary-alacoque-virgin" },
        },
        {
            id = "hedwig-of-silesia-religious",
            date = "10-16",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "religious", "holy_women" },
            saints = { "hedwig-of-silesia-religious" },
        },
        {
            id = "john-of-kanty-priest",
            date = "10-20",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "pastors", "mercy_workers" },
            saints = { "john-of-kanty-priest" },
        },
        {
            id = "james-strzemie-bishop",
            date = "10-21",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "bishops" },
        },
        {
            id = "john-paul-ii-pope",
            date = "10-22",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "pope_or_bishop" },
            saints = { "john-paul-ii-pope" },
        },
        {
            id = "joseph-bilczewski-bishop",
            date = "10-23",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "first-polish-martyrs",
            date = "11-13",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "martyrs" },
            plural = true,
        },
        {
            id = "caroline-kozka-virgin",
            date = "11-18",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "virgins" },
        },
        {
            id = "salomea-of-poland-religious",
            date = "11-19",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "religious" },
        },
        {
            id = "raphael-of-saint-joseph-kalinowski-priest",
            date = "11-20",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "religious" },
        },
        {
            id = "mary-of-jesus-the-good-shepherd-siedliska-virgin",
            date = "11-25",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "raphael-chylinski-priest",
            date = "12-02",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "barbara-of-heliopolis-virgin",
            date = "12-04",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "mary-mother-of-the-church",
            date = { fn = "pentecost_sunday", offset = 1 },
            rank = "feast",
            precedence = 8,
            colors = { "white" },
            commons = { "blessed_virgin_mary" },
        },
        {
            id = "our-lord-jesus-christ-the-eternal-high-priest",
            date = { fn = "pentecost_sunday", offset = 4 },
            rank = "feast",
            precedence = 8,
            colors = { "white" },
            office = "weekday",
        },
        {
            id = "dedication-of-consecrated-churches",
            date = { last = "sunday", month = 10 },
            rank = "solemnity",
            precedence = 4,
            colors = { "white" },
            commons = { "dedication_anniversary__inside" },
            omissible = true,
        },
    },
    transfers = {},
}
