-- Calendar of US: changes to the General Roman Calendar.
-- Origin: romcal @ 30344b3 (MIT), normalized in parked/epub/data/calendars/us-overlay.json;
-- transfers also from parked/epub/data/calendars/transfer-decisions.json and the USCCB policy.
-- transfers: solemnities moved to Sunday (epiphany, ascension, corpus_christi).
-- celebrations: added, or replacing the general celebration with the same id; title: the
-- calendar's own title for it (tag celebration.<title>), e.g. "..., Patron of Europe".
return {
    celebrations = {
        {
            id = "elizabeth-ann-seton-religious",
            date = "01-04",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
        },
        {
            id = "john-nepomucene-neumann-bishop",
            date = "01-05",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
        },
        {
            id = "andre-bessette-religious",
            date = "01-06",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "religious" },
        },
        {
            id = "day-of-prayer-for-the-legal-protection-of-unborn-children",
            date = "01-22",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white", "violet" },
            exceptions = { { move = { offset = 1 }, when = { weekday = "sunday" } } },
            office = "weekday",
        },
        {
            id = "marianne-cope-virgin",
            date = "01-23",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "virgins", "mercy_workers" },
        },
        {
            id = "vincent-of-saragossa-deacon",
            date = "01-23",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "red" },
            commons = { "martyrs" },
            saints = { "vincent-of-saragossa-deacon" },
        },
        {
            id = "katharine-drexel-virgin",
            date = "03-03",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "virgins" },
        },
        {
            id = "joseph-spouse-of-mary",
            date = "03-19",
            rank = "solemnity",
            precedence = 3,
            colors = { "white" },
            exceptions = {
                { move = { offset = 1 }, when = { weekday = "sunday" } },
                {
                    move = { fn = "palm_sunday", offset = -1 },
                    when = { between = { "palm_sunday", "divine_mercy_sunday" }, inclusive = true },
                },
            },
            saints = { "joseph-spouse-of-mary" },
        },
        {
            id = "damien-de-veuster-priest",
            date = "05-10",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "missionaries" },
        },
        {
            id = "isidore-the-farmer",
            date = "05-15",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "saints" },
        },
        {
            id = "junipero-serra-priest",
            date = "07-01",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "missionaries", "pastors" },
        },
        {
            id = "independence-day",
            date = "07-04",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
        {
            id = "elizabeth-of-portugal",
            date = "07-05",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "mercy_workers" },
            saints = { "elizabeth-of-portugal" },
        },
        {
            id = "kateri-tekakwitha-virgin",
            date = "07-14",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "virgins" },
        },
        {
            id = "camillus-de-lellis-priest",
            date = "07-18",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "mercy_workers" },
            saints = { "camillus-de-lellis-priest" },
        },
        {
            id = "peter-claver-priest",
            date = "09-09",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "pastors", "mercy_workers" },
            saints = { "peter-claver-priest" },
        },
        {
            id = "francis-xavier-seelos-priest",
            date = "10-05",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "missionaries" },
        },
        {
            id = "marie-rose-durocher-virgin",
            date = "10-06",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "virgins" },
        },
        {
            id = "john-de-brebeuf-isaac-jogues-priests-and-companions-martyrs",
            date = "10-19",
            rank = "memorial",
            precedence = 11,
            colors = { "red" },
            commons = { "missionary_martyrs" },
            plural = true,
            saints = { "john-de-brebeuf-priest", "isaac-jogues-priest", "companions-martyrs" },
        },
        {
            id = "paul-of-the-cross-priest",
            date = "10-20",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            saints = { "paul-of-the-cross-priest" },
        },
        {
            id = "frances-xavier-cabrini-virgin",
            date = "11-13",
            rank = "memorial",
            precedence = 11,
            colors = { "white" },
            commons = { "virgins", "mercy_workers" },
        },
        {
            id = "rose-philippine-duchesne-virgin",
            date = "11-18",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "virgins" },
        },
        {
            id = "miguel-agustin-pro-priest",
            date = "11-23",
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
            commons = { "martyrs", "pastors" },
        },
        {
            id = "our-lady-of-guadalupe",
            date = "12-12",
            title = "our-lady-of-guadalupe-patroness-of-the-americas",
            rank = "feast",
            precedence = 8,
            colors = { "white" },
            commons = { "blessed_virgin_mary" },
        },
        {
            id = "immaculate-conception-of-the-blessed-virgin-mary",
            date = { fn = "immaculate_conception_of_mary" },
            title = "immaculate-conception-of-the-blessed-virgin-mary-patroness-of-the-usa",
            rank = "solemnity",
            precedence = 4,
            colors = { "white" },
            obligation = true,
        },
        {
            id = "peter-and-paul-apostles",
            date = { fn = "peter_and_paul_apostles" },
            rank = "solemnity",
            precedence = 3,
            colors = { "red" },
            saints = { "peter-apostle", "paul-apostle" },
        },
        {
            id = "thanksgiving-day",
            date = { month = 11, nth = 4, weekday = "thursday" },
            rank = "optional_memorial",
            precedence = 12,
            colors = { "white" },
        },
    },
    transfers = { ascension = true, corpus_christi = true, epiphany = true },
    variants = {
        ascension_thursday = {
            provinces = { "Boston", "Hartford", "New York", "Omaha", "Philadelphia" },
        },
    },
}
